/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * https://pikadoc.readthedocs.io/zh/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#include <stdio.h>
#include <stdlib.h>
#include "BaseObj.h"
#include "PikaDebug.h"
#include "TinyObj.h"
#include "PikaDebug_Debuger.h"
#include "TinyObj.h"
#include "PikaMain.h"
#include "PikaStdLib_SysObj.h"
#include "PikaStdData.h"
#include "TinyObj.h"
#include "PikaStdData_ByteArray.h"
#include "TinyObj.h"
#include "PikaStdData_Dict.h"
#include "TinyObj.h"
#include "PikaStdData_FILEIO.h"
#include "TinyObj.h"
#include "PikaStdData_List.h"
#include "PikaStdData_Tuple.h"
#include "PikaStdData_String.h"
#include "TinyObj.h"
#include "PikaStdData_Tuple.h"
#include "TinyObj.h"
#include "PikaStdData_Utils.h"
#include "TinyObj.h"
#include "PikaStdData_dict_items.h"
#include "TinyObj.h"
#include "PikaStdData_dict_keys.h"
#include "TinyObj.h"
#include "PikaStdLib.h"
#include "TinyObj.h"
#include "PikaStdLib_MemChecker.h"
#include "TinyObj.h"
#include "PikaStdLib_RangeObj.h"
#include "TinyObj.h"
#include "PikaStdLib_StringObj.h"
#include "TinyObj.h"
#include "PikaStdLib_SysObj.h"
#include "TinyObj.h"
#include "PikaStdTask.h"
#include "TinyObj.h"
#include "PikaStdTask_Task.h"
#include "PikaStdLib_SysObj.h"
#include "PikaStdData_List.h"

#ifndef PIKA_MODULE_PIKADEBUG_DISABLE
void PikaDebug_DebugerMethod(PikaObj *self, Args *args){
    Arg* res = PikaDebug_Debuger(self);
    method_returnArg(args, res);
}
method_typedef(
    PikaDebug_Debuger,
    "Debuger", ""
);

class_def(PikaDebug){
    __BEFORE_MOETHOD_DEF
    constructor_def(PikaDebug_Debuger, 1761613187),
};
class_inhert(PikaDebug, TinyObj);

PikaObj *New_PikaDebug(Args *args){
    PikaObj *self = New_TinyObj(args);
    obj_setClass(self, PikaDebug);
    return self;
}
#endif

#ifndef PIKA_MODULE_PIKADEBUG_DISABLE
void PikaDebug_Debuger___init__Method(PikaObj *self, Args *args){
    PikaDebug_Debuger___init__(self);
}
method_typedef(
    PikaDebug_Debuger___init__,
    "__init__", ""
);

void PikaDebug_Debuger_set_traceMethod(PikaObj *self, Args *args){
    PikaDebug_Debuger_set_trace(self);
}
method_typedef(
    PikaDebug_Debuger_set_trace,
    "set_trace", ""
);

class_def(PikaDebug_Debuger){
    __BEFORE_MOETHOD_DEF
    method_def(PikaDebug_Debuger___init__, 904762485),
    method_def(PikaDebug_Debuger_set_trace, 1131228543),
};
class_inhert(PikaDebug_Debuger, TinyObj);

PikaObj *New_PikaDebug_Debuger(Args *args){
    PikaObj *self = New_TinyObj(args);
    obj_setClass(self, PikaDebug_Debuger);
    return self;
}

Arg *PikaDebug_Debuger(PikaObj *self){
    return obj_newObjInPackage(New_PikaDebug_Debuger);
}
#endif

#ifndef PIKA_MODULE_MAIN_DISABLE
class_def(PikaMain){
    __BEFORE_MOETHOD_DEF
};
class_inhert(PikaMain, PikaStdLib_SysObj);

PikaObj *New_PikaMain(Args *args){
    PikaObj *self = New_PikaStdLib_SysObj(args);
    obj_setClass(self, PikaMain);
    return self;
}

Arg *PikaMain(PikaObj *self){
    return obj_newObjInPackage(New_PikaMain);
}
#endif

#ifndef PIKA_MODULE_PIKASTDDATA_DISABLE
void PikaStdData_ByteArrayMethod(PikaObj *self, Args *args){
    Arg* res = PikaStdData_ByteArray(self);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdData_ByteArray,
    "ByteArray", ""
);

void PikaStdData_DictMethod(PikaObj *self, Args *args){
    Arg* res = PikaStdData_Dict(self);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdData_Dict,
    "Dict", ""
);

void PikaStdData_FILEIOMethod(PikaObj *self, Args *args){
    Arg* res = PikaStdData_FILEIO(self);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdData_FILEIO,
    "FILEIO", ""
);

void PikaStdData_ListMethod(PikaObj *self, Args *args){
    Arg* res = PikaStdData_List(self);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdData_List,
    "List", ""
);

void PikaStdData_StringMethod(PikaObj *self, Args *args){
    Arg* res = PikaStdData_String(self);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdData_String,
    "String", ""
);

void PikaStdData_TupleMethod(PikaObj *self, Args *args){
    Arg* res = PikaStdData_Tuple(self);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdData_Tuple,
    "Tuple", ""
);

void PikaStdData_UtilsMethod(PikaObj *self, Args *args){
    Arg* res = PikaStdData_Utils(self);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdData_Utils,
    "Utils", ""
);

void PikaStdData_dict_itemsMethod(PikaObj *self, Args *args){
    Arg* res = PikaStdData_dict_items(self);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdData_dict_items,
    "dict_items", ""
);

void PikaStdData_dict_keysMethod(PikaObj *self, Args *args){
    Arg* res = PikaStdData_dict_keys(self);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdData_dict_keys,
    "dict_keys", ""
);

class_def(PikaStdData){
    __BEFORE_MOETHOD_DEF
    constructor_def(PikaStdData_Tuple, 238099855),
    constructor_def(PikaStdData_Utils, 239242230),
    constructor_def(PikaStdData_FILEIO, 813431197),
    constructor_def(PikaStdData_dict_keys, 872966404),
    constructor_def(PikaStdData_dict_items, 888749258),
    constructor_def(PikaStdData_String, 1374591964),
    constructor_def(PikaStdData_ByteArray, 1998882840),
    constructor_def(PikaStdData_Dict, 2089035049),
    constructor_def(PikaStdData_List, 2089323073),
};
class_inhert(PikaStdData, TinyObj);

PikaObj *New_PikaStdData(Args *args){
    PikaObj *self = New_TinyObj(args);
    obj_setClass(self, PikaStdData);
    return self;
}
#endif

#ifndef PIKA_MODULE_PIKASTDDATA_DISABLE
void PikaStdData_ByteArray___getitem__Method(PikaObj *self, Args *args){
    int __key = args_getInt(args, "__key");
    int res = PikaStdData_ByteArray___getitem__(self, __key);
    method_returnInt(args, res);
}
method_typedef(
    PikaStdData_ByteArray___getitem__,
    "__getitem__", "__key"
);

void PikaStdData_ByteArray___init__Method(PikaObj *self, Args *args){
    Arg* bytes = args_getArg(args, "bytes");
    PikaStdData_ByteArray___init__(self, bytes);
}
method_typedef(
    PikaStdData_ByteArray___init__,
    "__init__", "bytes"
);

void PikaStdData_ByteArray___iter__Method(PikaObj *self, Args *args){
    Arg* res = PikaStdData_ByteArray___iter__(self);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdData_ByteArray___iter__,
    "__iter__", ""
);

void PikaStdData_ByteArray___next__Method(PikaObj *self, Args *args){
    Arg* res = PikaStdData_ByteArray___next__(self);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdData_ByteArray___next__,
    "__next__", ""
);

void PikaStdData_ByteArray___setitem__Method(PikaObj *self, Args *args){
    int __key = args_getInt(args, "__key");
    int __val = args_getInt(args, "__val");
    PikaStdData_ByteArray___setitem__(self, __key, __val);
}
method_typedef(
    PikaStdData_ByteArray___setitem__,
    "__setitem__", "__key,__val"
);

void PikaStdData_ByteArray___str__Method(PikaObj *self, Args *args){
    char* res = PikaStdData_ByteArray___str__(self);
    method_returnStr(args, res);
}
method_typedef(
    PikaStdData_ByteArray___str__,
    "__str__", ""
);

void PikaStdData_ByteArray_decodeMethod(PikaObj *self, Args *args){
    char* res = PikaStdData_ByteArray_decode(self);
    method_returnStr(args, res);
}
method_typedef(
    PikaStdData_ByteArray_decode,
    "decode", ""
);

class_def(PikaStdData_ByteArray){
    __BEFORE_MOETHOD_DEF
    method_def(PikaStdData_ByteArray___init__, 904762485),
    method_def(PikaStdData_ByteArray___iter__, 911732085),
    method_def(PikaStdData_ByteArray___next__, 1090305216),
    method_def(PikaStdData_ByteArray___setitem__, 1364865276),
    method_def(PikaStdData_ByteArray___getitem__, 1535436016),
    method_def(PikaStdData_ByteArray_decode, 2021571977),
    method_def(PikaStdData_ByteArray___str__, 2056834106),
};
class_inhert(PikaStdData_ByteArray, TinyObj);

PikaObj *New_PikaStdData_ByteArray(Args *args){
    PikaObj *self = New_TinyObj(args);
    obj_setClass(self, PikaStdData_ByteArray);
    return self;
}

Arg *PikaStdData_ByteArray(PikaObj *self){
    return obj_newObjInPackage(New_PikaStdData_ByteArray);
}
#endif

#ifndef PIKA_MODULE_PIKASTDDATA_DISABLE
void PikaStdData_Dict___contains__Method(PikaObj *self, Args *args){
    Arg* val = args_getArg(args, "val");
    int res = PikaStdData_Dict___contains__(self, val);
    method_returnInt(args, res);
}
method_typedef(
    PikaStdData_Dict___contains__,
    "__contains__", "val"
);

void PikaStdData_Dict___del__Method(PikaObj *self, Args *args){
    PikaStdData_Dict___del__(self);
}
method_typedef(
    PikaStdData_Dict___del__,
    "__del__", ""
);

void PikaStdData_Dict___getitem__Method(PikaObj *self, Args *args){
    Arg* __key = args_getArg(args, "__key");
    Arg* res = PikaStdData_Dict___getitem__(self, __key);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdData_Dict___getitem__,
    "__getitem__", "__key"
);

void PikaStdData_Dict___init__Method(PikaObj *self, Args *args){
    PikaStdData_Dict___init__(self);
}
method_typedef(
    PikaStdData_Dict___init__,
    "__init__", ""
);

void PikaStdData_Dict___iter__Method(PikaObj *self, Args *args){
    Arg* res = PikaStdData_Dict___iter__(self);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdData_Dict___iter__,
    "__iter__", ""
);

void PikaStdData_Dict___len__Method(PikaObj *self, Args *args){
    int res = PikaStdData_Dict___len__(self);
    method_returnInt(args, res);
}
method_typedef(
    PikaStdData_Dict___len__,
    "__len__", ""
);

void PikaStdData_Dict___next__Method(PikaObj *self, Args *args){
    Arg* res = PikaStdData_Dict___next__(self);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdData_Dict___next__,
    "__next__", ""
);

void PikaStdData_Dict___setitem__Method(PikaObj *self, Args *args){
    Arg* __key = args_getArg(args, "__key");
    Arg* __val = args_getArg(args, "__val");
    PikaStdData_Dict___setitem__(self, __key, __val);
}
method_typedef(
    PikaStdData_Dict___setitem__,
    "__setitem__", "__key,__val"
);

void PikaStdData_Dict___str__Method(PikaObj *self, Args *args){
    char* res = PikaStdData_Dict___str__(self);
    method_returnStr(args, res);
}
method_typedef(
    PikaStdData_Dict___str__,
    "__str__", ""
);

void PikaStdData_Dict_getMethod(PikaObj *self, Args *args){
    char* key = args_getStr(args, "key");
    Arg* res = PikaStdData_Dict_get(self, key);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdData_Dict_get,
    "get", "key"
);

void PikaStdData_Dict_itemsMethod(PikaObj *self, Args *args){
    PikaObj* res = PikaStdData_Dict_items(self);
    method_returnObj(args, res);
}
method_typedef(
    PikaStdData_Dict_items,
    "items", ""
);

void PikaStdData_Dict_keysMethod(PikaObj *self, Args *args){
    PikaObj* res = PikaStdData_Dict_keys(self);
    method_returnObj(args, res);
}
method_typedef(
    PikaStdData_Dict_keys,
    "keys", ""
);

void PikaStdData_Dict_removeMethod(PikaObj *self, Args *args){
    char* key = args_getStr(args, "key");
    PikaStdData_Dict_remove(self, key);
}
method_typedef(
    PikaStdData_Dict_remove,
    "remove", "key"
);

void PikaStdData_Dict_setMethod(PikaObj *self, Args *args){
    char* key = args_getStr(args, "key");
    Arg* arg = args_getArg(args, "arg");
    PikaStdData_Dict_set(self, key, arg);
}
method_typedef(
    PikaStdData_Dict_set,
    "set", "key,arg"
);

void PikaStdData_Dict_updateMethod(PikaObj *self, Args *args){
    PikaObj* other = args_getPtr(args, "other");
    PikaStdData_Dict_update(self, other);
}
method_typedef(
    PikaStdData_Dict_update,
    "update", "other"
);

class_def(PikaStdData_Dict){
    __BEFORE_MOETHOD_DEF
    method_def(PikaStdData_Dict_get, 193492613),
    method_def(PikaStdData_Dict_set, 193505681),
    method_def(PikaStdData_Dict_items, 262956327),
    method_def(PikaStdData_Dict_remove, 422343795),
    method_def(PikaStdData_Dict_update, 552456360),
    method_def(PikaStdData_Dict___init__, 904762485),
    method_def(PikaStdData_Dict___iter__, 911732085),
    method_def(PikaStdData_Dict___next__, 1090305216),
    method_def(PikaStdData_Dict___setitem__, 1364865276),
    method_def(PikaStdData_Dict___getitem__, 1535436016),
    method_def(PikaStdData_Dict___contains__, 1644201824),
    method_def(PikaStdData_Dict___del__, 2038499702),
    method_def(PikaStdData_Dict___len__, 2047989248),
    method_def(PikaStdData_Dict___str__, 2056834106),
    method_def(PikaStdData_Dict_keys, 2090432961),
};
class_inhert(PikaStdData_Dict, TinyObj);

PikaObj *New_PikaStdData_Dict(Args *args){
    PikaObj *self = New_TinyObj(args);
    obj_setClass(self, PikaStdData_Dict);
    return self;
}

Arg *PikaStdData_Dict(PikaObj *self){
    return obj_newObjInPackage(New_PikaStdData_Dict);
}
#endif

#ifndef PIKA_MODULE_PIKASTDDATA_DISABLE
void PikaStdData_FILEIO_closeMethod(PikaObj *self, Args *args){
    PikaStdData_FILEIO_close(self);
}
method_typedef(
    PikaStdData_FILEIO_close,
    "close", ""
);

void PikaStdData_FILEIO_initMethod(PikaObj *self, Args *args){
    char* path = args_getStr(args, "path");
    char* mode = args_getStr(args, "mode");
    int res = PikaStdData_FILEIO_init(self, path, mode);
    method_returnInt(args, res);
}
method_typedef(
    PikaStdData_FILEIO_init,
    "init", "path,mode"
);

void PikaStdData_FILEIO_readMethod(PikaObj *self, Args *args){
    PikaTuple* size = args_getTuple(args, "size");
    Arg* res = PikaStdData_FILEIO_read(self, size);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdData_FILEIO_read,
    "read", "*size"
);

void PikaStdData_FILEIO_readlineMethod(PikaObj *self, Args *args){
    char* res = PikaStdData_FILEIO_readline(self);
    method_returnStr(args, res);
}
method_typedef(
    PikaStdData_FILEIO_readline,
    "readline", ""
);

void PikaStdData_FILEIO_readlinesMethod(PikaObj *self, Args *args){
    PikaObj* res = PikaStdData_FILEIO_readlines(self);
    method_returnObj(args, res);
}
method_typedef(
    PikaStdData_FILEIO_readlines,
    "readlines", ""
);

void PikaStdData_FILEIO_seekMethod(PikaObj *self, Args *args){
    int offset = args_getInt(args, "offset");
    PikaTuple* fromwhere = args_getTuple(args, "fromwhere");
    int res = PikaStdData_FILEIO_seek(self, offset, fromwhere);
    method_returnInt(args, res);
}
method_typedef(
    PikaStdData_FILEIO_seek,
    "seek", "offset,*fromwhere"
);

void PikaStdData_FILEIO_tellMethod(PikaObj *self, Args *args){
    int res = PikaStdData_FILEIO_tell(self);
    method_returnInt(args, res);
}
method_typedef(
    PikaStdData_FILEIO_tell,
    "tell", ""
);

void PikaStdData_FILEIO_writeMethod(PikaObj *self, Args *args){
    Arg* s = args_getArg(args, "s");
    int res = PikaStdData_FILEIO_write(self, s);
    method_returnInt(args, res);
}
method_typedef(
    PikaStdData_FILEIO_write,
    "write", "s"
);

void PikaStdData_FILEIO_writelinesMethod(PikaObj *self, Args *args){
    PikaObj* lines = args_getPtr(args, "lines");
    PikaStdData_FILEIO_writelines(self, lines);
}
method_typedef(
    PikaStdData_FILEIO_writelines,
    "writelines", "lines"
);

class_def(PikaStdData_FILEIO){
    __BEFORE_MOETHOD_DEF
    method_def(PikaStdData_FILEIO_close, 255564379),
    method_def(PikaStdData_FILEIO_write, 279491920),
    method_def(PikaStdData_FILEIO_readlines, 594708860),
    method_def(PikaStdData_FILEIO_writelines, 836522731),
    method_def(PikaStdData_FILEIO_readline, 2035354601),
    method_def(PikaStdData_FILEIO_init, 2090370361),
    method_def(PikaStdData_FILEIO_read, 2090683713),
    method_def(PikaStdData_FILEIO_seek, 2090719789),
    method_def(PikaStdData_FILEIO_tell, 2090755958),
};
class_inhert(PikaStdData_FILEIO, TinyObj);

PikaObj *New_PikaStdData_FILEIO(Args *args){
    PikaObj *self = New_TinyObj(args);
    obj_setClass(self, PikaStdData_FILEIO);
    return self;
}

Arg *PikaStdData_FILEIO(PikaObj *self){
    return obj_newObjInPackage(New_PikaStdData_FILEIO);
}
#endif

#ifndef PIKA_MODULE_PIKASTDDATA_DISABLE
void PikaStdData_List___add__Method(PikaObj *self, Args *args){
    PikaObj* others = args_getPtr(args, "others");
    PikaObj* res = PikaStdData_List___add__(self, others);
    method_returnObj(args, res);
}
method_typedef(
    PikaStdData_List___add__,
    "__add__", "others"
);

void PikaStdData_List___init__Method(PikaObj *self, Args *args){
    PikaStdData_List___init__(self);
}
method_typedef(
    PikaStdData_List___init__,
    "__init__", ""
);

void PikaStdData_List___setitem__Method(PikaObj *self, Args *args){
    Arg* __key = args_getArg(args, "__key");
    Arg* __val = args_getArg(args, "__val");
    PikaStdData_List___setitem__(self, __key, __val);
}
method_typedef(
    PikaStdData_List___setitem__,
    "__setitem__", "__key,__val"
);

void PikaStdData_List___str__Method(PikaObj *self, Args *args){
    char* res = PikaStdData_List___str__(self);
    method_returnStr(args, res);
}
method_typedef(
    PikaStdData_List___str__,
    "__str__", ""
);

void PikaStdData_List_appendMethod(PikaObj *self, Args *args){
    Arg* arg = args_getArg(args, "arg");
    PikaStdData_List_append(self, arg);
}
method_typedef(
    PikaStdData_List_append,
    "append", "arg"
);

void PikaStdData_List_insertMethod(PikaObj *self, Args *args){
    int i = args_getInt(args, "i");
    Arg* arg = args_getArg(args, "arg");
    PikaStdData_List_insert(self, i, arg);
}
method_typedef(
    PikaStdData_List_insert,
    "insert", "i,arg"
);

void PikaStdData_List_popMethod(PikaObj *self, Args *args){
    Arg* res = PikaStdData_List_pop(self);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdData_List_pop,
    "pop", ""
);

void PikaStdData_List_removeMethod(PikaObj *self, Args *args){
    Arg* val = args_getArg(args, "val");
    PikaStdData_List_remove(self, val);
}
method_typedef(
    PikaStdData_List_remove,
    "remove", "val"
);

void PikaStdData_List_reverseMethod(PikaObj *self, Args *args){
    PikaStdData_List_reverse(self);
}
method_typedef(
    PikaStdData_List_reverse,
    "reverse", ""
);

void PikaStdData_List_setMethod(PikaObj *self, Args *args){
    int i = args_getInt(args, "i");
    Arg* arg = args_getArg(args, "arg");
    PikaStdData_List_set(self, i, arg);
}
method_typedef(
    PikaStdData_List_set,
    "set", "i,arg"
);

class_def(PikaStdData_List){
    __BEFORE_MOETHOD_DEF
    method_def(PikaStdData_List_insert, 81003162),
    method_def(PikaStdData_List_pop, 193502740),
    method_def(PikaStdData_List_set, 193505681),
    method_def(PikaStdData_List_remove, 422343795),
    method_def(PikaStdData_List___init__, 904762485),
    method_def(PikaStdData_List_reverse, 1062753473),
    method_def(PikaStdData_List___setitem__, 1364865276),
    method_def(PikaStdData_List_append, 1917667549),
    method_def(PikaStdData_List___add__, 2034897290),
    method_def(PikaStdData_List___str__, 2056834106),
};
class_inhert(PikaStdData_List, PikaStdData_Tuple);

PikaObj *New_PikaStdData_List(Args *args){
    PikaObj *self = New_PikaStdData_Tuple(args);
    obj_setClass(self, PikaStdData_List);
    return self;
}

Arg *PikaStdData_List(PikaObj *self){
    return obj_newObjInPackage(New_PikaStdData_List);
}
#endif

#ifndef PIKA_MODULE_PIKASTDDATA_DISABLE
void PikaStdData_String___getitem__Method(PikaObj *self, Args *args){
    Arg* __key = args_getArg(args, "__key");
    Arg* res = PikaStdData_String___getitem__(self, __key);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdData_String___getitem__,
    "__getitem__", "__key"
);

void PikaStdData_String___init__Method(PikaObj *self, Args *args){
    char* s = args_getStr(args, "s");
    PikaStdData_String___init__(self, s);
}
method_typedef(
    PikaStdData_String___init__,
    "__init__", "s"
);

void PikaStdData_String___iter__Method(PikaObj *self, Args *args){
    Arg* res = PikaStdData_String___iter__(self);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdData_String___iter__,
    "__iter__", ""
);

void PikaStdData_String___len__Method(PikaObj *self, Args *args){
    int res = PikaStdData_String___len__(self);
    method_returnInt(args, res);
}
method_typedef(
    PikaStdData_String___len__,
    "__len__", ""
);

void PikaStdData_String___next__Method(PikaObj *self, Args *args){
    Arg* res = PikaStdData_String___next__(self);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdData_String___next__,
    "__next__", ""
);

void PikaStdData_String___setitem__Method(PikaObj *self, Args *args){
    Arg* __key = args_getArg(args, "__key");
    Arg* __val = args_getArg(args, "__val");
    PikaStdData_String___setitem__(self, __key, __val);
}
method_typedef(
    PikaStdData_String___setitem__,
    "__setitem__", "__key,__val"
);

void PikaStdData_String___str__Method(PikaObj *self, Args *args){
    char* res = PikaStdData_String___str__(self);
    method_returnStr(args, res);
}
method_typedef(
    PikaStdData_String___str__,
    "__str__", ""
);

void PikaStdData_String_encodeMethod(PikaObj *self, Args *args){
    PikaTuple* encoding = args_getTuple(args, "encoding");
    Arg* res = PikaStdData_String_encode(self, encoding);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdData_String_encode,
    "encode", "*encoding"
);

void PikaStdData_String_endswithMethod(PikaObj *self, Args *args){
    char* suffix = args_getStr(args, "suffix");
    int res = PikaStdData_String_endswith(self, suffix);
    method_returnInt(args, res);
}
method_typedef(
    PikaStdData_String_endswith,
    "endswith", "suffix"
);

void PikaStdData_String_formatMethod(PikaObj *self, Args *args){
    PikaTuple* vars = args_getTuple(args, "vars");
    char* res = PikaStdData_String_format(self, vars);
    method_returnStr(args, res);
}
method_typedef(
    PikaStdData_String_format,
    "format", "*vars"
);

void PikaStdData_String_getMethod(PikaObj *self, Args *args){
    char* res = PikaStdData_String_get(self);
    method_returnStr(args, res);
}
method_typedef(
    PikaStdData_String_get,
    "get", ""
);

void PikaStdData_String_isalnumMethod(PikaObj *self, Args *args){
    int res = PikaStdData_String_isalnum(self);
    method_returnInt(args, res);
}
method_typedef(
    PikaStdData_String_isalnum,
    "isalnum", ""
);

void PikaStdData_String_isalphaMethod(PikaObj *self, Args *args){
    int res = PikaStdData_String_isalpha(self);
    method_returnInt(args, res);
}
method_typedef(
    PikaStdData_String_isalpha,
    "isalpha", ""
);

void PikaStdData_String_isdigitMethod(PikaObj *self, Args *args){
    int res = PikaStdData_String_isdigit(self);
    method_returnInt(args, res);
}
method_typedef(
    PikaStdData_String_isdigit,
    "isdigit", ""
);

void PikaStdData_String_islowerMethod(PikaObj *self, Args *args){
    int res = PikaStdData_String_islower(self);
    method_returnInt(args, res);
}
method_typedef(
    PikaStdData_String_islower,
    "islower", ""
);

void PikaStdData_String_isspaceMethod(PikaObj *self, Args *args){
    int res = PikaStdData_String_isspace(self);
    method_returnInt(args, res);
}
method_typedef(
    PikaStdData_String_isspace,
    "isspace", ""
);

void PikaStdData_String_replaceMethod(PikaObj *self, Args *args){
    char* old = args_getStr(args, "old");
    char* new = args_getStr(args, "new");
    char* res = PikaStdData_String_replace(self, old, new);
    method_returnStr(args, res);
}
method_typedef(
    PikaStdData_String_replace,
    "replace", "old,new"
);

void PikaStdData_String_setMethod(PikaObj *self, Args *args){
    char* s = args_getStr(args, "s");
    PikaStdData_String_set(self, s);
}
method_typedef(
    PikaStdData_String_set,
    "set", "s"
);

void PikaStdData_String_splitMethod(PikaObj *self, Args *args){
    char* s = args_getStr(args, "s");
    PikaObj* res = PikaStdData_String_split(self, s);
    method_returnObj(args, res);
}
method_typedef(
    PikaStdData_String_split,
    "split", "s"
);

void PikaStdData_String_startswithMethod(PikaObj *self, Args *args){
    char* prefix = args_getStr(args, "prefix");
    int res = PikaStdData_String_startswith(self, prefix);
    method_returnInt(args, res);
}
method_typedef(
    PikaStdData_String_startswith,
    "startswith", "prefix"
);

void PikaStdData_String_stripMethod(PikaObj *self, Args *args){
    PikaTuple* chrs = args_getTuple(args, "chrs");
    char* res = PikaStdData_String_strip(self, chrs);
    method_returnStr(args, res);
}
method_typedef(
    PikaStdData_String_strip,
    "strip", "*chrs"
);

class_def(PikaStdData_String){
    __BEFORE_MOETHOD_DEF
    method_def(PikaStdData_String_get, 193492613),
    method_def(PikaStdData_String_set, 193505681),
    method_def(PikaStdData_String_split, 274679281),
    method_def(PikaStdData_String_strip, 274829559),
    method_def(PikaStdData_String_isalnum, 700198430),
    method_def(PikaStdData_String_isalpha, 700200167),
    method_def(PikaStdData_String_isdigit, 703640370),
    method_def(PikaStdData_String_islower, 713360650),
    method_def(PikaStdData_String_isspace, 721673997),
    method_def(PikaStdData_String_startswith, 841709250),
    method_def(PikaStdData_String___init__, 904762485),
    method_def(PikaStdData_String___iter__, 911732085),
    method_def(PikaStdData_String_endswith, 920277419),
    method_def(PikaStdData_String_replace, 1055870465),
    method_def(PikaStdData_String___next__, 1090305216),
    method_def(PikaStdData_String___setitem__, 1364865276),
    method_def(PikaStdData_String___getitem__, 1535436016),
    method_def(PikaStdData_String___len__, 2047989248),
    method_def(PikaStdData_String___str__, 2056834106),
    method_def(PikaStdData_String_encode, 2071380659),
    method_def(PikaStdData_String_format, 2112238766),
};
class_inhert(PikaStdData_String, TinyObj);

PikaObj *New_PikaStdData_String(Args *args){
    PikaObj *self = New_TinyObj(args);
    obj_setClass(self, PikaStdData_String);
    return self;
}

Arg *PikaStdData_String(PikaObj *self){
    return obj_newObjInPackage(New_PikaStdData_String);
}
#endif

#ifndef PIKA_MODULE_PIKASTDDATA_DISABLE
void PikaStdData_Tuple___contains__Method(PikaObj *self, Args *args){
    Arg* val = args_getArg(args, "val");
    int res = PikaStdData_Tuple___contains__(self, val);
    method_returnInt(args, res);
}
method_typedef(
    PikaStdData_Tuple___contains__,
    "__contains__", "val"
);

void PikaStdData_Tuple___del__Method(PikaObj *self, Args *args){
    PikaStdData_Tuple___del__(self);
}
method_typedef(
    PikaStdData_Tuple___del__,
    "__del__", ""
);

void PikaStdData_Tuple___getitem__Method(PikaObj *self, Args *args){
    Arg* __key = args_getArg(args, "__key");
    Arg* res = PikaStdData_Tuple___getitem__(self, __key);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdData_Tuple___getitem__,
    "__getitem__", "__key"
);

void PikaStdData_Tuple___init__Method(PikaObj *self, Args *args){
    PikaStdData_Tuple___init__(self);
}
method_typedef(
    PikaStdData_Tuple___init__,
    "__init__", ""
);

void PikaStdData_Tuple___iter__Method(PikaObj *self, Args *args){
    Arg* res = PikaStdData_Tuple___iter__(self);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdData_Tuple___iter__,
    "__iter__", ""
);

void PikaStdData_Tuple___len__Method(PikaObj *self, Args *args){
    int res = PikaStdData_Tuple___len__(self);
    method_returnInt(args, res);
}
method_typedef(
    PikaStdData_Tuple___len__,
    "__len__", ""
);

void PikaStdData_Tuple___next__Method(PikaObj *self, Args *args){
    Arg* res = PikaStdData_Tuple___next__(self);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdData_Tuple___next__,
    "__next__", ""
);

void PikaStdData_Tuple___str__Method(PikaObj *self, Args *args){
    char* res = PikaStdData_Tuple___str__(self);
    method_returnStr(args, res);
}
method_typedef(
    PikaStdData_Tuple___str__,
    "__str__", ""
);

void PikaStdData_Tuple_getMethod(PikaObj *self, Args *args){
    int i = args_getInt(args, "i");
    Arg* res = PikaStdData_Tuple_get(self, i);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdData_Tuple_get,
    "get", "i"
);

void PikaStdData_Tuple_lenMethod(PikaObj *self, Args *args){
    int res = PikaStdData_Tuple_len(self);
    method_returnInt(args, res);
}
method_typedef(
    PikaStdData_Tuple_len,
    "len", ""
);

class_def(PikaStdData_Tuple){
    __BEFORE_MOETHOD_DEF
    method_def(PikaStdData_Tuple_get, 193492613),
    method_def(PikaStdData_Tuple_len, 193498052),
    method_def(PikaStdData_Tuple___init__, 904762485),
    method_def(PikaStdData_Tuple___iter__, 911732085),
    method_def(PikaStdData_Tuple___next__, 1090305216),
    method_def(PikaStdData_Tuple___getitem__, 1535436016),
    method_def(PikaStdData_Tuple___contains__, 1644201824),
    method_def(PikaStdData_Tuple___del__, 2038499702),
    method_def(PikaStdData_Tuple___len__, 2047989248),
    method_def(PikaStdData_Tuple___str__, 2056834106),
};
class_inhert(PikaStdData_Tuple, TinyObj);

PikaObj *New_PikaStdData_Tuple(Args *args){
    PikaObj *self = New_TinyObj(args);
    obj_setClass(self, PikaStdData_Tuple);
    return self;
}

Arg *PikaStdData_Tuple(PikaObj *self){
    return obj_newObjInPackage(New_PikaStdData_Tuple);
}
#endif

#ifndef PIKA_MODULE_PIKASTDDATA_DISABLE
void PikaStdData_Utils_int_to_bytesMethod(PikaObj *self, Args *args){
    int val = args_getInt(args, "val");
    Arg* res = PikaStdData_Utils_int_to_bytes(self, val);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdData_Utils_int_to_bytes,
    "int_to_bytes", "val"
);

class_def(PikaStdData_Utils){
    __BEFORE_MOETHOD_DEF
    method_def(PikaStdData_Utils_int_to_bytes, 476200216),
};
class_inhert(PikaStdData_Utils, TinyObj);

PikaObj *New_PikaStdData_Utils(Args *args){
    PikaObj *self = New_TinyObj(args);
    obj_setClass(self, PikaStdData_Utils);
    return self;
}

Arg *PikaStdData_Utils(PikaObj *self){
    return obj_newObjInPackage(New_PikaStdData_Utils);
}
#endif

#ifndef PIKA_MODULE_PIKASTDDATA_DISABLE
void PikaStdData_dict_items___iter__Method(PikaObj *self, Args *args){
    Arg* res = PikaStdData_dict_items___iter__(self);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdData_dict_items___iter__,
    "__iter__", ""
);

void PikaStdData_dict_items___len__Method(PikaObj *self, Args *args){
    int res = PikaStdData_dict_items___len__(self);
    method_returnInt(args, res);
}
method_typedef(
    PikaStdData_dict_items___len__,
    "__len__", ""
);

void PikaStdData_dict_items___next__Method(PikaObj *self, Args *args){
    Arg* res = PikaStdData_dict_items___next__(self);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdData_dict_items___next__,
    "__next__", ""
);

void PikaStdData_dict_items___str__Method(PikaObj *self, Args *args){
    char* res = PikaStdData_dict_items___str__(self);
    method_returnStr(args, res);
}
method_typedef(
    PikaStdData_dict_items___str__,
    "__str__", ""
);

class_def(PikaStdData_dict_items){
    __BEFORE_MOETHOD_DEF
    method_def(PikaStdData_dict_items___iter__, 911732085),
    method_def(PikaStdData_dict_items___next__, 1090305216),
    method_def(PikaStdData_dict_items___len__, 2047989248),
    method_def(PikaStdData_dict_items___str__, 2056834106),
};
class_inhert(PikaStdData_dict_items, TinyObj);

PikaObj *New_PikaStdData_dict_items(Args *args){
    PikaObj *self = New_TinyObj(args);
    obj_setClass(self, PikaStdData_dict_items);
    return self;
}

Arg *PikaStdData_dict_items(PikaObj *self){
    return obj_newObjInPackage(New_PikaStdData_dict_items);
}
#endif

#ifndef PIKA_MODULE_PIKASTDDATA_DISABLE
void PikaStdData_dict_keys___iter__Method(PikaObj *self, Args *args){
    Arg* res = PikaStdData_dict_keys___iter__(self);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdData_dict_keys___iter__,
    "__iter__", ""
);

void PikaStdData_dict_keys___len__Method(PikaObj *self, Args *args){
    int res = PikaStdData_dict_keys___len__(self);
    method_returnInt(args, res);
}
method_typedef(
    PikaStdData_dict_keys___len__,
    "__len__", ""
);

void PikaStdData_dict_keys___next__Method(PikaObj *self, Args *args){
    Arg* res = PikaStdData_dict_keys___next__(self);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdData_dict_keys___next__,
    "__next__", ""
);

void PikaStdData_dict_keys___str__Method(PikaObj *self, Args *args){
    char* res = PikaStdData_dict_keys___str__(self);
    method_returnStr(args, res);
}
method_typedef(
    PikaStdData_dict_keys___str__,
    "__str__", ""
);

class_def(PikaStdData_dict_keys){
    __BEFORE_MOETHOD_DEF
    method_def(PikaStdData_dict_keys___iter__, 911732085),
    method_def(PikaStdData_dict_keys___next__, 1090305216),
    method_def(PikaStdData_dict_keys___len__, 2047989248),
    method_def(PikaStdData_dict_keys___str__, 2056834106),
};
class_inhert(PikaStdData_dict_keys, TinyObj);

PikaObj *New_PikaStdData_dict_keys(Args *args){
    PikaObj *self = New_TinyObj(args);
    obj_setClass(self, PikaStdData_dict_keys);
    return self;
}

Arg *PikaStdData_dict_keys(PikaObj *self){
    return obj_newObjInPackage(New_PikaStdData_dict_keys);
}
#endif

#ifndef PIKA_MODULE_PIKASTDLIB_DISABLE
void PikaStdLib_MemCheckerMethod(PikaObj *self, Args *args){
    Arg* res = PikaStdLib_MemChecker(self);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdLib_MemChecker,
    "MemChecker", ""
);

void PikaStdLib_RangeObjMethod(PikaObj *self, Args *args){
    Arg* res = PikaStdLib_RangeObj(self);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdLib_RangeObj,
    "RangeObj", ""
);

void PikaStdLib_StringObjMethod(PikaObj *self, Args *args){
    Arg* res = PikaStdLib_StringObj(self);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdLib_StringObj,
    "StringObj", ""
);

void PikaStdLib_SysObjMethod(PikaObj *self, Args *args){
    Arg* res = PikaStdLib_SysObj(self);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdLib_SysObj,
    "SysObj", ""
);

class_def(PikaStdLib){
    __BEFORE_MOETHOD_DEF
#if 0
    constructor_def(PikaStdLib_StringObj, 145144695),
#endif
    constructor_def(PikaStdLib_MemChecker, 426635353),
    constructor_def(PikaStdLib_SysObj, 1380528799),
#if 0
    constructor_def(PikaStdLib_RangeObj, 1538428845),
#endif
};
class_inhert(PikaStdLib, TinyObj);

PikaObj *New_PikaStdLib(Args *args){
    PikaObj *self = New_TinyObj(args);
    obj_setClass(self, PikaStdLib);
    return self;
}
#endif

#ifndef PIKA_MODULE_PIKASTDLIB_DISABLE
void PikaStdLib_MemChecker_getMaxMethod(PikaObj *self, Args *args){
    pika_float res = PikaStdLib_MemChecker_getMax(self);
    method_returnFloat(args, res);
}
method_typedef(
    PikaStdLib_MemChecker_getMax,
    "getMax", ""
);

void PikaStdLib_MemChecker_getNowMethod(PikaObj *self, Args *args){
    pika_float res = PikaStdLib_MemChecker_getNow(self);
    method_returnFloat(args, res);
}
method_typedef(
    PikaStdLib_MemChecker_getNow,
    "getNow", ""
);

void PikaStdLib_MemChecker_maxMethod(PikaObj *self, Args *args){
    PikaStdLib_MemChecker_max(self);
}
method_typedef(
    PikaStdLib_MemChecker_max,
    "max", ""
);

void PikaStdLib_MemChecker_nowMethod(PikaObj *self, Args *args){
    PikaStdLib_MemChecker_now(self);
}
method_typedef(
    PikaStdLib_MemChecker_now,
    "now", ""
);

void PikaStdLib_MemChecker_resetMaxMethod(PikaObj *self, Args *args){
    PikaStdLib_MemChecker_resetMax(self);
}
method_typedef(
    PikaStdLib_MemChecker_resetMax,
    "resetMax", ""
);

class_def(PikaStdLib_MemChecker){
    __BEFORE_MOETHOD_DEF
    method_def(PikaStdLib_MemChecker_max, 193499019),
    method_def(PikaStdLib_MemChecker_now, 193500569),
#if !PIKA_NANO_ENABLE
    method_def(PikaStdLib_MemChecker_resetMax, 593750542),
#endif
#if !PIKA_NANO_ENABLE
    method_def(PikaStdLib_MemChecker_getMax, 2139551979),
#endif
#if !PIKA_NANO_ENABLE
    method_def(PikaStdLib_MemChecker_getNow, 2139553529),
#endif
};
class_inhert(PikaStdLib_MemChecker, TinyObj);

PikaObj *New_PikaStdLib_MemChecker(Args *args){
    PikaObj *self = New_TinyObj(args);
    obj_setClass(self, PikaStdLib_MemChecker);
    return self;
}

Arg *PikaStdLib_MemChecker(PikaObj *self){
    return obj_newObjInPackage(New_PikaStdLib_MemChecker);
}
#endif

#ifndef PIKA_MODULE_PIKASTDLIB_DISABLE
void PikaStdLib_RangeObj___next__Method(PikaObj *self, Args *args){
    Arg* res = PikaStdLib_RangeObj___next__(self);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdLib_RangeObj___next__,
    "__next__", ""
);

class_def(PikaStdLib_RangeObj){
    __BEFORE_MOETHOD_DEF
    method_def(PikaStdLib_RangeObj___next__, 1090305216),
};
class_inhert(PikaStdLib_RangeObj, TinyObj);

PikaObj *New_PikaStdLib_RangeObj(Args *args){
    PikaObj *self = New_TinyObj(args);
    obj_setClass(self, PikaStdLib_RangeObj);
    return self;
}

Arg *PikaStdLib_RangeObj(PikaObj *self){
    return obj_newObjInPackage(New_PikaStdLib_RangeObj);
}
#endif

#ifndef PIKA_MODULE_PIKASTDLIB_DISABLE
void PikaStdLib_StringObj___next__Method(PikaObj *self, Args *args){
    Arg* res = PikaStdLib_StringObj___next__(self);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdLib_StringObj___next__,
    "__next__", ""
);

class_def(PikaStdLib_StringObj){
    __BEFORE_MOETHOD_DEF
    method_def(PikaStdLib_StringObj___next__, 1090305216),
};
class_inhert(PikaStdLib_StringObj, TinyObj);

PikaObj *New_PikaStdLib_StringObj(Args *args){
    PikaObj *self = New_TinyObj(args);
    obj_setClass(self, PikaStdLib_StringObj);
    return self;
}

Arg *PikaStdLib_StringObj(PikaObj *self){
    return obj_newObjInPackage(New_PikaStdLib_StringObj);
}
#endif

#ifndef PIKA_MODULE_PIKASTDLIB_DISABLE
void PikaStdLib_SysObj___getitem__Method(PikaObj *self, Args *args){
    Arg* obj = args_getArg(args, "obj");
    Arg* key = args_getArg(args, "key");
    Arg* res = PikaStdLib_SysObj___getitem__(self, obj, key);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdLib_SysObj___getitem__,
    "__getitem__", "obj,key"
);

void PikaStdLib_SysObj___setitem__Method(PikaObj *self, Args *args){
    Arg* obj = args_getArg(args, "obj");
    Arg* key = args_getArg(args, "key");
    Arg* val = args_getArg(args, "val");
    Arg* res = PikaStdLib_SysObj___setitem__(self, obj, key, val);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdLib_SysObj___setitem__,
    "__setitem__", "obj,key,val"
);

void PikaStdLib_SysObj_bytesMethod(PikaObj *self, Args *args){
    Arg* val = args_getArg(args, "val");
    Arg* res = PikaStdLib_SysObj_bytes(self, val);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdLib_SysObj_bytes,
    "bytes", "val"
);

void PikaStdLib_SysObj_cformatMethod(PikaObj *self, Args *args){
    char* fmt = args_getStr(args, "fmt");
    PikaTuple* var = args_getTuple(args, "var");
    char* res = PikaStdLib_SysObj_cformat(self, fmt, var);
    method_returnStr(args, res);
}
method_typedef(
    PikaStdLib_SysObj_cformat,
    "cformat", "fmt,*var"
);

void PikaStdLib_SysObj_chrMethod(PikaObj *self, Args *args){
    int val = args_getInt(args, "val");
    char* res = PikaStdLib_SysObj_chr(self, val);
    method_returnStr(args, res);
}
method_typedef(
    PikaStdLib_SysObj_chr,
    "chr", "val"
);

void PikaStdLib_SysObj_dictMethod(PikaObj *self, Args *args){
    PikaTuple* val = args_getTuple(args, "val");
    Arg* res = PikaStdLib_SysObj_dict(self, val);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdLib_SysObj_dict,
    "dict", "*val"
);

void PikaStdLib_SysObj_dirMethod(PikaObj *self, Args *args){
    PikaObj* obj = args_getPtr(args, "obj");
    PikaObj* res = PikaStdLib_SysObj_dir(self, obj);
    method_returnObj(args, res);
}
method_typedef(
    PikaStdLib_SysObj_dir,
    "dir", "obj"
);

void PikaStdLib_SysObj_evalMethod(PikaObj *self, Args *args){
    char* code = args_getStr(args, "code");
    Arg* res = PikaStdLib_SysObj_eval(self, code);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdLib_SysObj_eval,
    "eval", "code"
);

void PikaStdLib_SysObj_execMethod(PikaObj *self, Args *args){
    char* code = args_getStr(args, "code");
    PikaStdLib_SysObj_exec(self, code);
}
method_typedef(
    PikaStdLib_SysObj_exec,
    "exec", "code"
);

void PikaStdLib_SysObj_exitMethod(PikaObj *self, Args *args){
    PikaStdLib_SysObj_exit(self);
}
method_typedef(
    PikaStdLib_SysObj_exit,
    "exit", ""
);

void PikaStdLib_SysObj_floatMethod(PikaObj *self, Args *args){
    Arg* arg = args_getArg(args, "arg");
    pika_float res = PikaStdLib_SysObj_float(self, arg);
    method_returnFloat(args, res);
}
method_typedef(
    PikaStdLib_SysObj_float,
    "float", "arg"
);

void PikaStdLib_SysObj_getattrMethod(PikaObj *self, Args *args){
    PikaObj* obj = args_getPtr(args, "obj");
    char* name = args_getStr(args, "name");
    Arg* res = PikaStdLib_SysObj_getattr(self, obj, name);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdLib_SysObj_getattr,
    "getattr", "obj,name"
);

void PikaStdLib_SysObj_hasattrMethod(PikaObj *self, Args *args){
    PikaObj* obj = args_getPtr(args, "obj");
    char* name = args_getStr(args, "name");
    int res = PikaStdLib_SysObj_hasattr(self, obj, name);
    method_returnInt(args, res);
}
method_typedef(
    PikaStdLib_SysObj_hasattr,
    "hasattr", "obj,name"
);

void PikaStdLib_SysObj_helpMethod(PikaObj *self, Args *args){
    char* name = args_getStr(args, "name");
    PikaStdLib_SysObj_help(self, name);
}
method_typedef(
    PikaStdLib_SysObj_help,
    "help", "name"
);

void PikaStdLib_SysObj_hexMethod(PikaObj *self, Args *args){
    int val = args_getInt(args, "val");
    char* res = PikaStdLib_SysObj_hex(self, val);
    method_returnStr(args, res);
}
method_typedef(
    PikaStdLib_SysObj_hex,
    "hex", "val"
);

void PikaStdLib_SysObj_idMethod(PikaObj *self, Args *args){
    Arg* obj = args_getArg(args, "obj");
    int res = PikaStdLib_SysObj_id(self, obj);
    method_returnInt(args, res);
}
method_typedef(
    PikaStdLib_SysObj_id,
    "id", "obj"
);

void PikaStdLib_SysObj_inputMethod(PikaObj *self, Args *args){
    PikaTuple* info = args_getTuple(args, "info");
    char* res = PikaStdLib_SysObj_input(self, info);
    method_returnStr(args, res);
}
method_typedef(
    PikaStdLib_SysObj_input,
    "input", "*info"
);

void PikaStdLib_SysObj_intMethod(PikaObj *self, Args *args){
    Arg* arg = args_getArg(args, "arg");
    int res = PikaStdLib_SysObj_int(self, arg);
    method_returnInt(args, res);
}
method_typedef(
    PikaStdLib_SysObj_int,
    "int", "arg"
);

void PikaStdLib_SysObj_iterMethod(PikaObj *self, Args *args){
    Arg* arg = args_getArg(args, "arg");
    Arg* res = PikaStdLib_SysObj_iter(self, arg);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdLib_SysObj_iter,
    "iter", "arg"
);

void PikaStdLib_SysObj_lenMethod(PikaObj *self, Args *args){
    Arg* arg = args_getArg(args, "arg");
    int res = PikaStdLib_SysObj_len(self, arg);
    method_returnInt(args, res);
}
method_typedef(
    PikaStdLib_SysObj_len,
    "len", "arg"
);

void PikaStdLib_SysObj_listMethod(PikaObj *self, Args *args){
    PikaTuple* val = args_getTuple(args, "val");
    Arg* res = PikaStdLib_SysObj_list(self, val);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdLib_SysObj_list,
    "list", "*val"
);

void PikaStdLib_SysObj_openMethod(PikaObj *self, Args *args){
    char* path = args_getStr(args, "path");
    char* mode = args_getStr(args, "mode");
    PikaObj* res = PikaStdLib_SysObj_open(self, path, mode);
    method_returnObj(args, res);
}
method_typedef(
    PikaStdLib_SysObj_open,
    "open", "path,mode"
);

void PikaStdLib_SysObj_ordMethod(PikaObj *self, Args *args){
    char* val = args_getStr(args, "val");
    int res = PikaStdLib_SysObj_ord(self, val);
    method_returnInt(args, res);
}
method_typedef(
    PikaStdLib_SysObj_ord,
    "ord", "val"
);

void PikaStdLib_SysObj_printMethod(PikaObj *self, Args *args){
    PikaTuple* val = args_getTuple(args, "val");
    PikaDict* ops = args_getDict(args, "ops");
    PikaStdLib_SysObj_print(self, val, ops);
}
method_typedef(
    PikaStdLib_SysObj_print,
    "print", "*val,**ops"
);

void PikaStdLib_SysObj_rangeMethod(PikaObj *self, Args *args){
    PikaTuple* ax = args_getTuple(args, "ax");
    Arg* res = PikaStdLib_SysObj_range(self, ax);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdLib_SysObj_range,
    "range", "*ax"
);

void PikaStdLib_SysObj_setattrMethod(PikaObj *self, Args *args){
    PikaObj* obj = args_getPtr(args, "obj");
    char* name = args_getStr(args, "name");
    Arg* val = args_getArg(args, "val");
    PikaStdLib_SysObj_setattr(self, obj, name, val);
}
method_typedef(
    PikaStdLib_SysObj_setattr,
    "setattr", "obj,name,val"
);

void PikaStdLib_SysObj_strMethod(PikaObj *self, Args *args){
    Arg* arg = args_getArg(args, "arg");
    char* res = PikaStdLib_SysObj_str(self, arg);
    method_returnStr(args, res);
}
method_typedef(
    PikaStdLib_SysObj_str,
    "str", "arg"
);

void PikaStdLib_SysObj_typeMethod(PikaObj *self, Args *args){
    Arg* arg = args_getArg(args, "arg");
    Arg* res = PikaStdLib_SysObj_type(self, arg);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdLib_SysObj_type,
    "type", "arg"
);

class_def(PikaStdLib_SysObj){
    __BEFORE_MOETHOD_DEF
#if !PIKA_NANO_ENABLE
    method_def(PikaStdLib_SysObj_id, 5863474),
#endif
#if !PIKA_NANO_ENABLE
    method_def(PikaStdLib_SysObj_chr, 193488354),
#endif
#if !PIKA_NANO_ENABLE
    method_def(PikaStdLib_SysObj_dir, 193489476),
#endif
#if !PIKA_NANO_ENABLE
    method_def(PikaStdLib_SysObj_hex, 193493706),
#endif
    method_def(PikaStdLib_SysObj_int, 193495088),
    method_def(PikaStdLib_SysObj_len, 193498052),
#if !PIKA_NANO_ENABLE
    method_def(PikaStdLib_SysObj_ord, 193501738),
#endif
    method_def(PikaStdLib_SysObj_str, 193506174),
#if !PIKA_NANO_ENABLE
    method_def(PikaStdLib_SysObj_setattr, 204224428),
#endif
#if !PIKA_NANO_ENABLE
    method_def(PikaStdLib_SysObj_bytes, 254850636),
#endif
    method_def(PikaStdLib_SysObj_float, 259121563),
#if !PIKA_NANO_ENABLE
    method_def(PikaStdLib_SysObj_input, 262752949),
#endif
    method_def(PikaStdLib_SysObj_print, 271190290),
    method_def(PikaStdLib_SysObj_range, 272956402),
#if !PIKA_NANO_ENABLE
    method_def(PikaStdLib_SysObj_hasattr, 872734812),
#endif
#if PIKA_SYNTAX_FORMAT_ENABLE
    method_def(PikaStdLib_SysObj_cformat, 1049381873),
#endif
    method_def(PikaStdLib_SysObj___setitem__, 1364865276),
    method_def(PikaStdLib_SysObj___getitem__, 1535436016),
#if !PIKA_NANO_ENABLE
    method_def(PikaStdLib_SysObj_getattr, 1886477984),
#endif
#if PIKA_BUILTIN_STRUCT_ENABLE
    method_def(PikaStdLib_SysObj_dict, 2090185033),
#endif
#if PIKA_EXEC_ENABLE
    method_def(PikaStdLib_SysObj_eval, 2090235053),
#endif
#if PIKA_EXEC_ENABLE
    method_def(PikaStdLib_SysObj_exec, 2090237354),
#endif
#if !PIKA_NANO_ENABLE
    method_def(PikaStdLib_SysObj_exit, 2090237503),
#endif
#if !PIKA_NANO_ENABLE
    method_def(PikaStdLib_SysObj_help, 2090324718),
#endif
    method_def(PikaStdLib_SysObj_iter, 2090376761),
#if PIKA_BUILTIN_STRUCT_ENABLE
    method_def(PikaStdLib_SysObj_list, 2090473057),
#endif
#if PIKA_FILEIO_ENABLE
    method_def(PikaStdLib_SysObj_open, 2090588023),
#endif
#if !PIKA_NANO_ENABLE
    method_def(PikaStdLib_SysObj_type, 2090777863),
#endif
};
class_inhert(PikaStdLib_SysObj, TinyObj);

PikaObj *New_PikaStdLib_SysObj(Args *args){
    PikaObj *self = New_TinyObj(args);
    obj_setClass(self, PikaStdLib_SysObj);
    return self;
}

Arg *PikaStdLib_SysObj(PikaObj *self){
    return obj_newObjInPackage(New_PikaStdLib_SysObj);
}
#endif

#ifndef PIKA_MODULE_PIKASTDTASK_DISABLE
void PikaStdTask_TaskMethod(PikaObj *self, Args *args){
    Arg* res = PikaStdTask_Task(self);
    method_returnArg(args, res);
}
method_typedef(
    PikaStdTask_Task,
    "Task", ""
);

class_def(PikaStdTask){
    __BEFORE_MOETHOD_DEF
    constructor_def(PikaStdTask_Task, 2089601848),
};
class_inhert(PikaStdTask, TinyObj);

PikaObj *New_PikaStdTask(Args *args){
    PikaObj *self = New_TinyObj(args);
    obj_setClass(self, PikaStdTask);
    return self;
}
#endif

#ifndef PIKA_MODULE_PIKASTDTASK_DISABLE
void PikaStdTask_Task___init__Method(PikaObj *self, Args *args){
    PikaStdTask_Task___init__(self);
}
method_typedef(
    PikaStdTask_Task___init__,
    "__init__", ""
);

void PikaStdTask_Task_call_alwaysMethod(PikaObj *self, Args *args){
    Arg* fun_todo = args_getArg(args, "fun_todo");
    PikaStdTask_Task_call_always(self, fun_todo);
}
method_typedef(
    PikaStdTask_Task_call_always,
    "call_always", "fun_todo"
);

void PikaStdTask_Task_call_period_msMethod(PikaObj *self, Args *args){
    Arg* fun_todo = args_getArg(args, "fun_todo");
    int period_ms = args_getInt(args, "period_ms");
    PikaStdTask_Task_call_period_ms(self, fun_todo, period_ms);
}
method_typedef(
    PikaStdTask_Task_call_period_ms,
    "call_period_ms", "fun_todo,period_ms"
);

void PikaStdTask_Task_call_whenMethod(PikaObj *self, Args *args){
    Arg* fun_todo = args_getArg(args, "fun_todo");
    Arg* fun_when = args_getArg(args, "fun_when");
    PikaStdTask_Task_call_when(self, fun_todo, fun_when);
}
method_typedef(
    PikaStdTask_Task_call_when,
    "call_when", "fun_todo,fun_when"
);

void PikaStdTask_Task_platformGetTickMethod(PikaObj *self, Args *args){
    PikaStdTask_Task_platformGetTick(self);
}
method_typedef(
    PikaStdTask_Task_platformGetTick,
    "platformGetTick", ""
);

void PikaStdTask_Task_run_foreverMethod(PikaObj *self, Args *args){
    PikaStdTask_Task_run_forever(self);
}
method_typedef(
    PikaStdTask_Task_run_forever,
    "run_forever", ""
);

void PikaStdTask_Task_run_onceMethod(PikaObj *self, Args *args){
    PikaStdTask_Task_run_once(self);
}
method_typedef(
    PikaStdTask_Task_run_once,
    "run_once", ""
);

void PikaStdTask_Task_run_until_msMethod(PikaObj *self, Args *args){
    int until_ms = args_getInt(args, "until_ms");
    PikaStdTask_Task_run_until_ms(self, until_ms);
}
method_typedef(
    PikaStdTask_Task_run_until_ms,
    "run_until_ms", "until_ms"
);

class_def(PikaStdTask_Task){
    __BEFORE_MOETHOD_DEF
    method_def(PikaStdTask_Task_run_forever, 408322738),
    method_def(PikaStdTask_Task_run_until_ms, 854930212),
    method_def(PikaStdTask_Task___init__, 904762485),
    method_def(PikaStdTask_Task_call_always, 1368427953),
    method_def(PikaStdTask_Task_call_period_ms, 1674236450),
    method_def(PikaStdTask_Task_run_once, 1726949022),
    method_def(PikaStdTask_Task_platformGetTick, 1897947957),
    method_def(PikaStdTask_Task_call_when, 2141638002),
};
class_inhert(PikaStdTask_Task, PikaStdLib_SysObj);

PikaObj *New_PikaStdTask_Task(Args *args){
    PikaObj *self = New_PikaStdLib_SysObj(args);
    obj_newObj(self, "calls", "PikaStdData_List", New_PikaStdData_List);
    obj_setClass(self, PikaStdTask_Task);
    return self;
}

Arg *PikaStdTask_Task(PikaObj *self){
    return obj_newObjInPackage(New_PikaStdTask_Task);
}
#endif

