/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * https://pikadoc.readthedocs.io/zh/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___mqtt__H
#define ___mqtt__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__mqtt(Args *args);

Arg* _mqtt__MQTT(PikaObj *self);
void _mqtt___del__(PikaObj *self);

#endif
