/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * https://pikadoc.readthedocs.io/zh/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___requests_Response__H
#define ___requests_Response__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__requests_Response(Args *args);

void _requests_Response___del__(PikaObj *self);
void _requests_Response___init__(PikaObj *self);
int _requests_Response_header_write(PikaObj *self, char* header, char* value);
PikaObj* _requests_Response_json(PikaObj *self);
int _requests_Response_proto_write(PikaObj *self, char* proto);
int _requests_Response_request(PikaObj *self, char* method, char* url, pika_float timeout, char* data);
PikaObj* _requests_Response_request_del(PikaObj *self);
int _requests_Response_request_init(PikaObj *self, char* method);
int _requests_Response_urlencode_write(PikaObj *self, char* s1, char* s2, char* start, char* connect);

#endif
