/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * https://pikadoc.readthedocs.io/zh/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __pika_cjson__H
#define __pika_cjson__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_pika_cjson(Args *args);

Arg* pika_cjson_Array(PikaObj *self);
Arg* pika_cjson_ArrayReference(PikaObj *self);
Arg* pika_cjson_Bool(PikaObj *self);
Arg* pika_cjson_False_(PikaObj *self);
Arg* pika_cjson_Null(PikaObj *self);
Arg* pika_cjson_Number(PikaObj *self);
Arg* pika_cjson_Object(PikaObj *self);
Arg* pika_cjson_ObjectReference(PikaObj *self);
PikaObj* pika_cjson_Parse(PikaObj *self, char* value);
Arg* pika_cjson_Raw(PikaObj *self);
Arg* pika_cjson_String(PikaObj *self);
Arg* pika_cjson_StringReference(PikaObj *self);
Arg* pika_cjson_True_(PikaObj *self);
Arg* pika_cjson_cJSON(PikaObj *self);

#endif
