/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * https://pikadoc.readthedocs.io/zh/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __PikaMath_Math__H
#define __PikaMath_Math__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_PikaMath_Math(Args *args);

void PikaMath_Math___init__(PikaObj *self);
pika_float PikaMath_Math_acos(PikaObj *self, pika_float x);
pika_float PikaMath_Math_asin(PikaObj *self, pika_float x);
pika_float PikaMath_Math_atan(PikaObj *self, pika_float x);
pika_float PikaMath_Math_atan2(PikaObj *self, pika_float x, pika_float y);
int PikaMath_Math_ceil(PikaObj *self, pika_float x);
pika_float PikaMath_Math_cos(PikaObj *self, pika_float x);
pika_float PikaMath_Math_cosh(PikaObj *self, pika_float x);
pika_float PikaMath_Math_degrees(PikaObj *self, pika_float x);
pika_float PikaMath_Math_exp(PikaObj *self, pika_float x);
pika_float PikaMath_Math_fabs(PikaObj *self, pika_float x);
int PikaMath_Math_floor(PikaObj *self, pika_float x);
pika_float PikaMath_Math_fmod(PikaObj *self, pika_float x, pika_float y);
pika_float PikaMath_Math_log(PikaObj *self, pika_float x);
pika_float PikaMath_Math_log10(PikaObj *self, pika_float x);
pika_float PikaMath_Math_log2(PikaObj *self, pika_float x);
pika_float PikaMath_Math_pow(PikaObj *self, pika_float x, pika_float y);
pika_float PikaMath_Math_radians(PikaObj *self, pika_float x);
pika_float PikaMath_Math_remainder(PikaObj *self, pika_float x, pika_float y);
pika_float PikaMath_Math_sin(PikaObj *self, pika_float x);
pika_float PikaMath_Math_sinh(PikaObj *self, pika_float x);
pika_float PikaMath_Math_sqrt(PikaObj *self, pika_float x);
pika_float PikaMath_Math_tan(PikaObj *self, pika_float x);
pika_float PikaMath_Math_tanh(PikaObj *self, pika_float x);
pika_float PikaMath_Math_trunc(PikaObj *self, pika_float x);

#endif
