/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * https://pikadoc.readthedocs.io/zh/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __pika_cjson_cJSON__H
#define __pika_cjson_cJSON__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_pika_cjson_cJSON(Args *args);

void pika_cjson_cJSON___del__(PikaObj *self);
void pika_cjson_cJSON___init__(PikaObj *self);
void pika_cjson_cJSON_addItemToArray(PikaObj *self, PikaObj* item);
void pika_cjson_cJSON_addItemToObject(PikaObj *self, char* string, PikaObj* item);
PikaObj* pika_cjson_cJSON_getArrayItem(PikaObj *self, int index);
int pika_cjson_cJSON_getArraySize(PikaObj *self);
PikaObj* pika_cjson_cJSON_getChild(PikaObj *self);
PikaObj* pika_cjson_cJSON_getNext(PikaObj *self);
PikaObj* pika_cjson_cJSON_getObjectItem(PikaObj *self, char* string);
PikaObj* pika_cjson_cJSON_getPrev(PikaObj *self);
char* pika_cjson_cJSON_getString(PikaObj *self);
int pika_cjson_cJSON_getType(PikaObj *self);
Arg* pika_cjson_cJSON_getValue(PikaObj *self);
pika_float pika_cjson_cJSON_getValueDouble(PikaObj *self);
int pika_cjson_cJSON_getValueInt(PikaObj *self);
char* pika_cjson_cJSON_getValueString(PikaObj *self);
int pika_cjson_cJSON_isArray(PikaObj *self);
int pika_cjson_cJSON_isBool(PikaObj *self);
int pika_cjson_cJSON_isFalse(PikaObj *self);
int pika_cjson_cJSON_isInvalid(PikaObj *self);
int pika_cjson_cJSON_isNull(PikaObj *self);
int pika_cjson_cJSON_isNumber(PikaObj *self);
int pika_cjson_cJSON_isObject(PikaObj *self);
int pika_cjson_cJSON_isRaw(PikaObj *self);
int pika_cjson_cJSON_isString(PikaObj *self);
int pika_cjson_cJSON_isTrue(PikaObj *self);
char* pika_cjson_cJSON_print(PikaObj *self);

#endif
