/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * https://pikadoc.readthedocs.io/zh/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __PikaMath_Operator__H
#define __PikaMath_Operator__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_PikaMath_Operator(Args *args);

int PikaMath_Operator_AND(PikaObj *self, int flag1, int flag2);
int PikaMath_Operator_NOT(PikaObj *self, int flag);
int PikaMath_Operator_OR(PikaObj *self, int flag1, int flag2);
void PikaMath_Operator___del__(PikaObj *self);
char* PikaMath_Operator___str__(PikaObj *self);
int PikaMath_Operator_equalFloat(PikaObj *self, pika_float num1, pika_float num2);
int PikaMath_Operator_equalInt(PikaObj *self, int num1, int num2);
int PikaMath_Operator_graterThanFloat(PikaObj *self, pika_float num1, pika_float num2);
int PikaMath_Operator_graterThanInt(PikaObj *self, int num1, int num2);
int PikaMath_Operator_lessThanFloat(PikaObj *self, pika_float num1, pika_float num2);
int PikaMath_Operator_lessThanInt(PikaObj *self, int num1, int num2);
pika_float PikaMath_Operator_minusFloat(PikaObj *self, pika_float num1, pika_float num2);
int PikaMath_Operator_minusInt(PikaObj *self, int num1, int num2);
pika_float PikaMath_Operator_plusFloat(PikaObj *self, pika_float num1, pika_float num2);
int PikaMath_Operator_plusInt(PikaObj *self, int num1, int num2);

#endif
