/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * https://pikadoc.readthedocs.io/zh/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __re__H
#define __re__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_re(Args *args);

Arg* re_Match(PikaObj *self);
Arg* re_Pattern(PikaObj *self);
void re___init__(PikaObj *self);
PikaObj* re_compile(PikaObj *self, char* pattern, PikaTuple* flags);
char* re_escape(PikaObj *self, char* pattern);
PikaObj* re_findall(PikaObj *self, char* pattern, char* subject, PikaTuple* flags);
PikaObj* re_fullmatch(PikaObj *self, char* pattern, char* subject, PikaTuple* flags);
PikaObj* re_match(PikaObj *self, char* pattern, char* subject, PikaTuple* flags);
PikaObj* re_search(PikaObj *self, char* pattern, char* subject, PikaTuple* flags);
PikaObj* re_split(PikaObj *self, char* pattern, char* subject, PikaTuple* maxsplit__flags);
char* re_sub(PikaObj *self, char* pattern, char* repl, char* subjet, PikaTuple* count__flags);
PikaObj* re_subn(PikaObj *self, char* pattern, char* repl, char* subjet, PikaTuple* count__flags);

#endif
