/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * https://pikadoc.readthedocs.io/zh/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __re_Match__H
#define __re_Match__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_re_Match(Args *args);

void re_Match___del__(PikaObj *self);
void re_Match___init__(PikaObj *self);
char* re_Match_group(PikaObj *self, PikaTuple* n);
PikaObj* re_Match_groups(PikaObj *self);
PikaObj* re_Match_span(PikaObj *self, PikaTuple* group_n);

#endif
