#include "bflb_core.h"
#include "bl702l_irq.h"
#include "bl702l_memorymap.h"

#define DMA_CHANNEL_OFFSET 0x100

struct bflb_device_s bl702l_device_table[] = {
    { .name = BFLB_NAME_ADC0,
      .reg_base = 0x40000000 - 0x400,
      .irq_num = BL702L_IRQ_GPADC_DMA,
      .idx = 0,
      .sub_idx = 0,
      .dev_type = BFLB_DEVICE_TYPE_ADC,
      .user_data = NULL },
    { .name = BFLB_NAME_EF_CTRL,
      .reg_base = EF_CTRL_BASE,
      .irq_num = 0xff,
      .idx = 0,
      .sub_idx = 0,
      .dev_type = BFLB_DEVICE_TYPE_EF_CTRL,
      .user_data = NULL },
    { .name = BFLB_NAME_GPIO,
      .reg_base = GLB_BASE,
      .irq_num = BL702L_IRQ_GPIO_INT0,
      .idx = 0,
      .sub_idx = 0,
      .dev_type = BFLB_DEVICE_TYPE_GPIO,
      .user_data = NULL },
    { .name = BFLB_NAME_UART0,
      .reg_base = UART0_BASE,
      .irq_num = BL702L_IRQ_UART0,
      .idx = 0,
      .dev_type = BFLB_DEVICE_TYPE_UART,
      .user_data = NULL },
    { .name = BFLB_NAME_SPI0,
      .reg_base = SPI_BASE,
      .irq_num = BL702L_IRQ_SPI0,
      .idx = 0,
      .dev_type = BFLB_DEVICE_TYPE_SPI,
      .user_data = NULL },
    { .name = BFLB_NAME_PWM_V1,
      .reg_base = PWM_BASE + 0x20,
      .irq_num = BL702L_IRQ_PWM,
      .idx = 0,
      .dev_type = BFLB_DEVICE_TYPE_PWM,
      .user_data = NULL },
    { .name = BFLB_NAME_PWM_V2_PWM0,
      .reg_base = PWM_BASE + 0x40,
      .irq_num = BL702L_IRQ_PWM,
      .idx = 0,
      .dev_type = BFLB_DEVICE_TYPE_PWM,
      .user_data = NULL },
    { .name = BFLB_NAME_DMA0_CH0,
      .reg_base = DMA_BASE + 1 * DMA_CHANNEL_OFFSET,
      .irq_num = BL702L_IRQ_DMA0_ALL,
      .idx = 0,
      .sub_idx = 0,
      .dev_type = BFLB_DEVICE_TYPE_DMA,
      .user_data = NULL },
    { .name = BFLB_NAME_DMA0_CH1,
      .reg_base = DMA_BASE + 2 * DMA_CHANNEL_OFFSET,
      .irq_num = BL702L_IRQ_DMA0_ALL,
      .idx = 0,
      .sub_idx = 1,
      .dev_type = BFLB_DEVICE_TYPE_DMA,
      .user_data = NULL },
    { .name = BFLB_NAME_DMA0_CH2,
      .reg_base = DMA_BASE + 3 * DMA_CHANNEL_OFFSET,
      .irq_num = BL702L_IRQ_DMA0_ALL,
      .idx = 0,
      .sub_idx = 2,
      .dev_type = BFLB_DEVICE_TYPE_DMA,
      .user_data = NULL },
    { .name = BFLB_NAME_DMA0_CH3,
      .reg_base = DMA_BASE + 4 * DMA_CHANNEL_OFFSET,
      .irq_num = BL702L_IRQ_DMA0_ALL,
      .idx = 0,
      .sub_idx = 3,
      .dev_type = BFLB_DEVICE_TYPE_DMA,
      .user_data = NULL },
    { .name = BFLB_NAME_I2C0,
      .reg_base = I2C_BASE,
      .irq_num = BL702L_IRQ_I2C0,
      .idx = 0,
      .sub_idx = 0,
      .dev_type = BFLB_DEVICE_TYPE_I2C,
      .user_data = NULL },
    { .name = BFLB_NAME_TIMER0,
      .reg_base = TIMER_BASE,
      .irq_num = BL702L_IRQ_TIMER0,
      .idx = 0,
      .sub_idx = 0,
      .dev_type = BFLB_DEVICE_TYPE_TIMER,
      .user_data = NULL },
    { .name = BFLB_NAME_TIMER1,
      .reg_base = TIMER_BASE,
      .irq_num = BL702L_IRQ_TIMER1,
      .idx = 1,
      .sub_idx = 0,
      .dev_type = BFLB_DEVICE_TYPE_TIMER,
      .user_data = NULL },
    { .name = BFLB_NAME_RTC,
      .reg_base = HBN_BASE,
      .irq_num = BL702L_IRQ_HBN_OUT0,
      .idx = 0,
      .sub_idx = 0,
      .dev_type = BFLB_DEVICE_TYPE_RTC,
      .user_data = NULL },
    { .name = BFLB_NAME_AES,
      .reg_base = SEC_ENG_BASE,
      .irq_num = 0xff,
      .idx = 0,
      .sub_idx = 0,
      .dev_type = BFLB_DEVICE_TYPE_AES,
      .user_data = NULL },
    { .name = BFLB_NAME_SHA,
      .reg_base = SEC_ENG_BASE,
      .irq_num = 0xff,
      .idx = 0,
      .sub_idx = 0,
      .dev_type = BFLB_DEVICE_TYPE_SHA,
      .user_data = NULL },
    { .name = BFLB_NAME_TRNG,
      .reg_base = SEC_ENG_BASE,
      .irq_num = 0xff,
      .idx = 0,
      .sub_idx = 0,
      .dev_type = BFLB_DEVICE_TYPE_TRNG,
      .user_data = NULL },
    { .name = BFLB_NAME_PKA,
      .reg_base = SEC_ENG_BASE,
      .irq_num = 0xff,
      .idx = 0,
      .sub_idx = 0,
      .dev_type = BFLB_DEVICE_TYPE_PKA,
      .user_data = NULL },
    { .name = BFLB_NAME_WDT,
      .reg_base = TIMER_BASE,
      .irq_num = BL702L_IRQ_WDT,
      .idx = 0,
      .sub_idx = 0,
      .dev_type = BFLB_DEVICE_TYPE_TIMER,
      .user_data = NULL },
    { .name = BFLB_NAME_CKS,
      .reg_base = CKS_BASE,
      .irq_num = 0xff,
      .idx = 0,
      .sub_idx = 0,
      .dev_type = BFLB_DEVICE_TYPE_CKS,
      .user_data = NULL },
    { .name = BFLB_NAME_IRTX,
      .reg_base = IR_BASE,
      .irq_num = BL702L_IRQ_IRTX,
      .idx = 0,
      .sub_idx = 0,
      .dev_type = BFLB_DEVICE_TYPE_IR,
      .user_data = NULL },
    { .name = BFLB_NAME_KYS,
      .reg_base = KYS_BASE,
      .irq_num = BL702L_IRQ_KYS,
      .idx = 0,
      .sub_idx = 0,
      .dev_type = BFLB_DEVICE_TYPE_KYS,
      .user_data = NULL },
    { .name = BFLB_NAME_AUADC,
      .reg_base = AUADC_BASE,
      .irq_num = BL702L_IRQ_AUADC,
      .idx = 0,
      .sub_idx = 0,
      .dev_type = BFLB_DEVICE_TYPE_AUDIOADC,
      .user_data = NULL },
};

struct bflb_device_s *bflb_device_get_by_name(const char *name)
{
    for (uint8_t i = 0; i < sizeof(bl702l_device_table) / sizeof(bl702l_device_table[0]); i++) {
        if (strcmp(bl702l_device_table[i].name, name) == 0) {
            return &bl702l_device_table[i];
        }
    }
    LHAL_PARAM_ASSERT(0);
    return NULL;
}

void bflb_device_set_userdata(struct bflb_device_s *device, void *user_data)
{
    device->user_data = user_data;
}