#!/usr/bin/env python3
"""Generate flash_prog_cfg.ini from a Bouffalo partition table."""

import argparse
import os
import re
import sys

TOOLS_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(TOOLS_DIR, "pylib"))

import toml


class ConfigError(ValueError):
    pass


SECTION_RE = re.compile(r"^[A-Za-z0-9_.-]+$")


def load_partition_table(path):
    try:
        data = toml.load(path)
    except (OSError, toml.TomlDecodeError) as error:
        raise ConfigError("unable to read partition table {}: {}".format(path, error)) from error

    table = data.get("pt_table")
    entries = data.get("pt_entry")
    if not isinstance(table, dict) or not isinstance(entries, list):
        raise ConfigError("partition table must contain [pt_table] and [[pt_entry]]")
    if not isinstance(table.get("address0"), int):
        raise ConfigError("pt_table.address0 must be an integer")

    by_name = {}
    for index, entry in enumerate(entries):
        if not isinstance(entry, dict):
            raise ConfigError("pt_entry[{}] must be a table".format(index))
        name = entry.get("name")
        address = entry.get("address0")
        size = entry.get("size0")
        if not isinstance(name, str) or not name:
            raise ConfigError("pt_entry[{}].name must be a non-empty string".format(index))
        if name in by_name:
            raise ConfigError("duplicate partition name: {}".format(name))
        if not isinstance(address, int) or not isinstance(size, int):
            raise ConfigError("{}.address0 and size0 must be integers".format(name))
        by_name[name] = (address, size)
    return table["address0"], by_name


def validate_section(section):
    if not SECTION_RE.fullmatch(section):
        raise ConfigError("invalid INI section name: {!r}".format(section))


def generate(args):
    pt_address, partitions = load_partition_table(args.partition_table)
    images = []
    sections = {"cfg"}
    used_partitions = {"FW"}

    def add_image(section, path, address):
        validate_section(section)
        if section in sections:
            raise ConfigError("duplicate INI section: {}".format(section))
        sections.add(section)
        images.append((section, os.path.abspath(path), address))

    if args.standard:
        boot2 = partitions.get("Boot2")
        if boot2 is None:
            raise ConfigError("partition not found: Boot2")
        used_partitions.add("Boot2")
        add_image("boot2", args.boot2, boot2[0])
        add_image("partition", args.partition_bin, pt_address)

    for partition, path in args.image:
        entry = partitions.get(partition)
        if entry is None:
            raise ConfigError("partition not found: {}".format(partition))
        if partition in used_partitions:
            raise ConfigError("partition already registered: {}".format(partition))
        if entry[1] <= 0:
            raise ConfigError("partition {} has an invalid size0".format(partition))
        used_partitions.add(partition)
        add_image(partition, path, entry[0])

    if args.standard:
        app_entry = partitions.get("FW")
        if app_entry is None:
            raise ConfigError("partition not found: FW")
        add_image("FW", args.application, app_entry[0])
    else:
        add_image("FW", args.application, 0)

    lines = [
        "# Auto-generated by CMake. Do not edit.",
        "[cfg]",
        "erase = {}".format(args.erase),
        "skip_mode = 0x0, 0x0",
        "boot2_isp_mode = 0",
        "",
    ]
    for section, path, address in images:
        lines.extend(
            (
                "[{}]".format(section),
                "filedir = {}".format(path),
                "address = 0x{:X}".format(address),
                "",
            )
        )

    output = os.path.abspath(args.output)
    os.makedirs(os.path.dirname(output), exist_ok=True)
    with open(output, "w", encoding="utf-8", newline="\n") as stream:
        stream.write("\n".join(lines))
    return output


def create_parser():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--partition-table", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--application", required=True)
    parser.add_argument("--erase", type=int, choices=(0, 1, 2), default=1)
    parser.add_argument("--standard", action="store_true")
    parser.add_argument("--boot2")
    parser.add_argument("--partition-bin")
    parser.add_argument(
        "--image",
        action="append",
        nargs=2,
        default=[],
        metavar=("PARTITION", "FILE"),
    )
    return parser


def main(argv=None):
    parser = create_parser()
    args = parser.parse_args(argv)
    if args.standard and (not args.boot2 or not args.partition_bin):
        parser.error("--standard requires --boot2 and --partition-bin")
    try:
        output = generate(args)
    except ConfigError as error:
        parser.error(str(error))
    print("Generated {}".format(output))
    return 0


if __name__ == "__main__":
    sys.exit(main())
