
#ifndef __MSP_GLB_REG_H__
#define __MSP_GLB_REG_H__

/* 0x580 : cgen_m */
#define GLB_CGEN_CFG0_OFFSET (0x580)
#define GLB_CGEN_M_CPU       GLB_CGEN_M_CPU
#define GLB_CGEN_M_CPU_POS   (0U)
#define GLB_CGEN_M_CPU_LEN   (1U)
#define GLB_CGEN_M_CPU_MSK   (((1U << GLB_CGEN_M_CPU_LEN) - 1) << GLB_CGEN_M_CPU_POS)
#define GLB_CGEN_M_CPU_UMSK  (~(((1U << GLB_CGEN_M_CPU_LEN) - 1) << GLB_CGEN_M_CPU_POS))
#define GLB_CGEN_M_SDU       GLB_CGEN_M_SDU
#define GLB_CGEN_M_SDU_POS   (1U)
#define GLB_CGEN_M_SDU_LEN   (1U)
#define GLB_CGEN_M_SDU_MSK   (((1U << GLB_CGEN_M_SDU_LEN) - 1) << GLB_CGEN_M_SDU_POS)
#define GLB_CGEN_M_SDU_UMSK  (~(((1U << GLB_CGEN_M_SDU_LEN) - 1) << GLB_CGEN_M_SDU_POS))
#define GLB_CGEN_M_SEC       GLB_CGEN_M_SEC
#define GLB_CGEN_M_SEC_POS   (2U)
#define GLB_CGEN_M_SEC_LEN   (1U)
#define GLB_CGEN_M_SEC_MSK   (((1U << GLB_CGEN_M_SEC_LEN) - 1) << GLB_CGEN_M_SEC_POS)
#define GLB_CGEN_M_SEC_UMSK  (~(((1U << GLB_CGEN_M_SEC_LEN) - 1) << GLB_CGEN_M_SEC_POS))
#define GLB_CGEN_M_DMA       GLB_CGEN_M_DMA
#define GLB_CGEN_M_DMA_POS   (3U)
#define GLB_CGEN_M_DMA_LEN   (1U)
#define GLB_CGEN_M_DMA_MSK   (((1U << GLB_CGEN_M_DMA_LEN) - 1) << GLB_CGEN_M_DMA_POS)
#define GLB_CGEN_M_DMA_UMSK  (~(((1U << GLB_CGEN_M_DMA_LEN) - 1) << GLB_CGEN_M_DMA_POS))
#define GLB_CGEN_M_CCI       GLB_CGEN_M_CCI
#define GLB_CGEN_M_CCI_POS   (4U)
#define GLB_CGEN_M_CCI_LEN   (1U)
#define GLB_CGEN_M_CCI_MSK   (((1U << GLB_CGEN_M_CCI_LEN) - 1) << GLB_CGEN_M_CCI_POS)
#define GLB_CGEN_M_CCI_UMSK  (~(((1U << GLB_CGEN_M_CCI_LEN) - 1) << GLB_CGEN_M_CCI_POS))

/* 0x584 : cgen_s1a + cgen_s1 */
#define GLB_CGEN_CFG1_OFFSET     (0x584)
#define GLB_CGEN_S1_RSVD0        GLB_CGEN_S1_RSVD0
#define GLB_CGEN_S1_RSVD0_POS    (0U)
#define GLB_CGEN_S1_RSVD0_LEN    (1U)
#define GLB_CGEN_S1_RSVD0_MSK    (((1U << GLB_CGEN_S1_RSVD0_LEN) - 1) << GLB_CGEN_S1_RSVD0_POS)
#define GLB_CGEN_S1_RSVD0_UMSK   (~(((1U << GLB_CGEN_S1_RSVD0_LEN) - 1) << GLB_CGEN_S1_RSVD0_POS))
#define GLB_CGEN_S1_GPIP         GLB_CGEN_S1_GPIP
#define GLB_CGEN_S1_GPIP_POS     (2U)
#define GLB_CGEN_S1_GPIP_LEN     (1U)
#define GLB_CGEN_S1_GPIP_MSK     (((1U << GLB_CGEN_S1_GPIP_LEN) - 1) << GLB_CGEN_S1_GPIP_POS)
#define GLB_CGEN_S1_GPIP_UMSK    (~(((1U << GLB_CGEN_S1_GPIP_LEN) - 1) << GLB_CGEN_S1_GPIP_POS))
#define GLB_CGEN_S1_SEC_DBG      GLB_CGEN_S1_SEC_DBG
#define GLB_CGEN_S1_SEC_DBG_POS  (3U)
#define GLB_CGEN_S1_SEC_DBG_LEN  (1U)
#define GLB_CGEN_S1_SEC_DBG_MSK  (((1U << GLB_CGEN_S1_SEC_DBG_LEN) - 1) << GLB_CGEN_S1_SEC_DBG_POS)
#define GLB_CGEN_S1_SEC_DBG_UMSK (~(((1U << GLB_CGEN_S1_SEC_DBG_LEN) - 1) << GLB_CGEN_S1_SEC_DBG_POS))
#define GLB_CGEN_S1_SEC_ENG      GLB_CGEN_S1_SEC_ENG
#define GLB_CGEN_S1_SEC_ENG_POS  (4U)
#define GLB_CGEN_S1_SEC_ENG_LEN  (1U)
#define GLB_CGEN_S1_SEC_ENG_MSK  (((1U << GLB_CGEN_S1_SEC_ENG_LEN) - 1) << GLB_CGEN_S1_SEC_ENG_POS)
#define GLB_CGEN_S1_SEC_ENG_UMSK (~(((1U << GLB_CGEN_S1_SEC_ENG_LEN) - 1) << GLB_CGEN_S1_SEC_ENG_POS))
#define GLB_CGEN_S1_TZ           GLB_CGEN_S1_TZ
#define GLB_CGEN_S1_TZ_POS       (5U)
#define GLB_CGEN_S1_TZ_LEN       (1U)
#define GLB_CGEN_S1_TZ_MSK       (((1U << GLB_CGEN_S1_TZ_LEN) - 1) << GLB_CGEN_S1_TZ_POS)
#define GLB_CGEN_S1_TZ_UMSK      (~(((1U << GLB_CGEN_S1_TZ_LEN) - 1) << GLB_CGEN_S1_TZ_POS))
#define GLB_CGEN_S1_RSVD6        GLB_CGEN_S1_RSVD6
#define GLB_CGEN_S1_RSVD6_POS    (6U)
#define GLB_CGEN_S1_RSVD6_LEN    (1U)
#define GLB_CGEN_S1_RSVD6_MSK    (((1U << GLB_CGEN_S1_RSVD6_LEN) - 1) << GLB_CGEN_S1_RSVD6_POS)
#define GLB_CGEN_S1_RSVD6_UMSK   (~(((1U << GLB_CGEN_S1_RSVD6_LEN) - 1) << GLB_CGEN_S1_RSVD6_POS))
#define GLB_CGEN_S1_EF_CTRL      GLB_CGEN_S1_EF_CTRL
#define GLB_CGEN_S1_EF_CTRL_POS  (7U)
#define GLB_CGEN_S1_EF_CTRL_LEN  (1U)
#define GLB_CGEN_S1_EF_CTRL_MSK  (((1U << GLB_CGEN_S1_EF_CTRL_LEN) - 1) << GLB_CGEN_S1_EF_CTRL_POS)
#define GLB_CGEN_S1_EF_CTRL_UMSK (~(((1U << GLB_CGEN_S1_EF_CTRL_LEN) - 1) << GLB_CGEN_S1_EF_CTRL_POS))
#define GLB_CGEN_S1_RSVD8        GLB_CGEN_S1_RSVD8
#define GLB_CGEN_S1_RSVD8_POS    (8U)
#define GLB_CGEN_S1_RSVD8_LEN    (1U)
#define GLB_CGEN_S1_RSVD8_MSK    (((1U << GLB_CGEN_S1_RSVD8_LEN) - 1) << GLB_CGEN_S1_RSVD8_POS)
#define GLB_CGEN_S1_RSVD8_UMSK   (~(((1U << GLB_CGEN_S1_RSVD8_LEN) - 1) << GLB_CGEN_S1_RSVD8_POS))
#define GLB_CGEN_S1_RSVD9        GLB_CGEN_S1_RSVD9
#define GLB_CGEN_S1_RSVD9_POS    (9U)
#define GLB_CGEN_S1_RSVD9_LEN    (1U)
#define GLB_CGEN_S1_RSVD9_MSK    (((1U << GLB_CGEN_S1_RSVD9_LEN) - 1) << GLB_CGEN_S1_RSVD9_POS)
#define GLB_CGEN_S1_RSVD9_UMSK   (~(((1U << GLB_CGEN_S1_RSVD9_LEN) - 1) << GLB_CGEN_S1_RSVD9_POS))
#define GLB_CGEN_S1_RSVD10       GLB_CGEN_S1_RSVD10
#define GLB_CGEN_S1_RSVD10_POS   (10U)
#define GLB_CGEN_S1_RSVD10_LEN   (1U)
#define GLB_CGEN_S1_RSVD10_MSK   (((1U << GLB_CGEN_S1_RSVD10_LEN) - 1) << GLB_CGEN_S1_RSVD10_POS)
#define GLB_CGEN_S1_RSVD10_UMSK  (~(((1U << GLB_CGEN_S1_RSVD10_LEN) - 1) << GLB_CGEN_S1_RSVD10_POS))
#define GLB_CGEN_S1_SF_CTRL      GLB_CGEN_S1_SF_CTRL
#define GLB_CGEN_S1_SF_CTRL_POS  (11U)
#define GLB_CGEN_S1_SF_CTRL_LEN  (1U)
#define GLB_CGEN_S1_SF_CTRL_MSK  (((1U << GLB_CGEN_S1_SF_CTRL_LEN) - 1) << GLB_CGEN_S1_SF_CTRL_POS)
#define GLB_CGEN_S1_SF_CTRL_UMSK (~(((1U << GLB_CGEN_S1_SF_CTRL_LEN) - 1) << GLB_CGEN_S1_SF_CTRL_POS))
#define GLB_CGEN_S1_DMA          GLB_CGEN_S1_DMA
#define GLB_CGEN_S1_DMA_POS      (12U)
#define GLB_CGEN_S1_DMA_LEN      (1U)
#define GLB_CGEN_S1_DMA_MSK      (((1U << GLB_CGEN_S1_DMA_LEN) - 1) << GLB_CGEN_S1_DMA_POS)
#define GLB_CGEN_S1_DMA_UMSK     (~(((1U << GLB_CGEN_S1_DMA_LEN) - 1) << GLB_CGEN_S1_DMA_POS))
#define GLB_CGEN_S1_RSVD13       GLB_CGEN_S1_RSVD13
#define GLB_CGEN_S1_RSVD13_POS   (13U)
#define GLB_CGEN_S1_RSVD13_LEN   (1U)
#define GLB_CGEN_S1_RSVD13_MSK   (((1U << GLB_CGEN_S1_RSVD13_LEN) - 1) << GLB_CGEN_S1_RSVD13_POS)
#define GLB_CGEN_S1_RSVD13_UMSK  (~(((1U << GLB_CGEN_S1_RSVD13_LEN) - 1) << GLB_CGEN_S1_RSVD13_POS))
#define GLB_CGEN_S1_RSVD14       GLB_CGEN_S1_RSVD14
#define GLB_CGEN_S1_RSVD14_POS   (14U)
#define GLB_CGEN_S1_RSVD14_LEN   (1U)
#define GLB_CGEN_S1_RSVD14_MSK   (((1U << GLB_CGEN_S1_RSVD14_LEN) - 1) << GLB_CGEN_S1_RSVD14_POS)
#define GLB_CGEN_S1_RSVD14_UMSK  (~(((1U << GLB_CGEN_S1_RSVD14_LEN) - 1) << GLB_CGEN_S1_RSVD14_POS))
#define GLB_CGEN_S1_RSVD15       GLB_CGEN_S1_RSVD15
#define GLB_CGEN_S1_RSVD15_POS   (15U)
#define GLB_CGEN_S1_RSVD15_LEN   (1U)
#define GLB_CGEN_S1_RSVD15_MSK   (((1U << GLB_CGEN_S1_RSVD15_LEN) - 1) << GLB_CGEN_S1_RSVD15_POS)
#define GLB_CGEN_S1_RSVD15_UMSK  (~(((1U << GLB_CGEN_S1_RSVD15_LEN) - 1) << GLB_CGEN_S1_RSVD15_POS))
#define GLB_CGEN_S1A_UART0       GLB_CGEN_S1A_UART0
#define GLB_CGEN_S1A_UART0_POS   (16U)
#define GLB_CGEN_S1A_UART0_LEN   (1U)
#define GLB_CGEN_S1A_UART0_MSK   (((1U << GLB_CGEN_S1A_UART0_LEN) - 1) << GLB_CGEN_S1A_UART0_POS)
#define GLB_CGEN_S1A_UART0_UMSK  (~(((1U << GLB_CGEN_S1A_UART0_LEN) - 1) << GLB_CGEN_S1A_UART0_POS))
#define GLB_CGEN_S1A_UART1       GLB_CGEN_S1A_UART1
#define GLB_CGEN_S1A_UART1_POS   (17U)
#define GLB_CGEN_S1A_UART1_LEN   (1U)
#define GLB_CGEN_S1A_UART1_MSK   (((1U << GLB_CGEN_S1A_UART1_LEN) - 1) << GLB_CGEN_S1A_UART1_POS)
#define GLB_CGEN_S1A_UART1_UMSK  (~(((1U << GLB_CGEN_S1A_UART1_LEN) - 1) << GLB_CGEN_S1A_UART1_POS))
#define GLB_CGEN_S1A_SPI         GLB_CGEN_S1A_SPI
#define GLB_CGEN_S1A_SPI_POS     (18U)
#define GLB_CGEN_S1A_SPI_LEN     (1U)
#define GLB_CGEN_S1A_SPI_MSK     (((1U << GLB_CGEN_S1A_SPI_LEN) - 1) << GLB_CGEN_S1A_SPI_POS)
#define GLB_CGEN_S1A_SPI_UMSK    (~(((1U << GLB_CGEN_S1A_SPI_LEN) - 1) << GLB_CGEN_S1A_SPI_POS))
#define GLB_CGEN_S1A_I2C         GLB_CGEN_S1A_I2C
#define GLB_CGEN_S1A_I2C_POS     (19U)
#define GLB_CGEN_S1A_I2C_LEN     (1U)
#define GLB_CGEN_S1A_I2C_MSK     (((1U << GLB_CGEN_S1A_I2C_LEN) - 1) << GLB_CGEN_S1A_I2C_POS)
#define GLB_CGEN_S1A_I2C_UMSK    (~(((1U << GLB_CGEN_S1A_I2C_LEN) - 1) << GLB_CGEN_S1A_I2C_POS))
#define GLB_CGEN_S1A_PWM         GLB_CGEN_S1A_PWM
#define GLB_CGEN_S1A_PWM_POS     (20U)
#define GLB_CGEN_S1A_PWM_LEN     (1U)
#define GLB_CGEN_S1A_PWM_MSK     (((1U << GLB_CGEN_S1A_PWM_LEN) - 1) << GLB_CGEN_S1A_PWM_POS)
#define GLB_CGEN_S1A_PWM_UMSK    (~(((1U << GLB_CGEN_S1A_PWM_LEN) - 1) << GLB_CGEN_S1A_PWM_POS))
#define GLB_CGEN_S1A_TIMER       GLB_CGEN_S1A_TIMER
#define GLB_CGEN_S1A_TIMER_POS   (21U)
#define GLB_CGEN_S1A_TIMER_LEN   (1U)
#define GLB_CGEN_S1A_TIMER_MSK   (((1U << GLB_CGEN_S1A_TIMER_LEN) - 1) << GLB_CGEN_S1A_TIMER_POS)
#define GLB_CGEN_S1A_TIMER_UMSK  (~(((1U << GLB_CGEN_S1A_TIMER_LEN) - 1) << GLB_CGEN_S1A_TIMER_POS))
#define GLB_CGEN_S1A_IR          GLB_CGEN_S1A_IR
#define GLB_CGEN_S1A_IR_POS      (22U)
#define GLB_CGEN_S1A_IR_LEN      (1U)
#define GLB_CGEN_S1A_IR_MSK      (((1U << GLB_CGEN_S1A_IR_LEN) - 1) << GLB_CGEN_S1A_IR_POS)
#define GLB_CGEN_S1A_IR_UMSK     (~(((1U << GLB_CGEN_S1A_IR_LEN) - 1) << GLB_CGEN_S1A_IR_POS))
#define GLB_CGEN_S1A_CKS         GLB_CGEN_S1A_CKS
#define GLB_CGEN_S1A_CKS_POS     (23U)
#define GLB_CGEN_S1A_CKS_LEN     (1U)
#define GLB_CGEN_S1A_CKS_MSK     (((1U << GLB_CGEN_S1A_CKS_LEN) - 1) << GLB_CGEN_S1A_CKS_POS)
#define GLB_CGEN_S1A_CKS_UMSK    (~(((1U << GLB_CGEN_S1A_CKS_LEN) - 1) << GLB_CGEN_S1A_CKS_POS))
#define GLB_CGEN_S1A_DBI         GLB_CGEN_S1A_DBI
#define GLB_CGEN_S1A_DBI_POS     (24U)
#define GLB_CGEN_S1A_DBI_LEN     (1U)
#define GLB_CGEN_S1A_DBI_MSK     (((1U << GLB_CGEN_S1A_DBI_LEN) - 1) << GLB_CGEN_S1A_DBI_POS)
#define GLB_CGEN_S1A_DBI_UMSK    (~(((1U << GLB_CGEN_S1A_DBI_LEN) - 1) << GLB_CGEN_S1A_DBI_POS))
#define GLB_CGEN_S1A_I2C1        GLB_CGEN_S1A_I2C1
#define GLB_CGEN_S1A_I2C1_POS    (25U)
#define GLB_CGEN_S1A_I2C1_LEN    (1U)
#define GLB_CGEN_S1A_I2C1_MSK    (((1U << GLB_CGEN_S1A_I2C1_LEN) - 1) << GLB_CGEN_S1A_I2C1_POS)
#define GLB_CGEN_S1A_I2C1_UMSK   (~(((1U << GLB_CGEN_S1A_I2C1_LEN) - 1) << GLB_CGEN_S1A_I2C1_POS))
#define GLB_CGEN_S1A_UART2       GLB_CGEN_S1A_UART2
#define GLB_CGEN_S1A_UART2_POS   (26U)
#define GLB_CGEN_S1A_UART2_LEN   (1U)
#define GLB_CGEN_S1A_UART2_MSK   (((1U << GLB_CGEN_S1A_UART2_LEN) - 1) << GLB_CGEN_S1A_UART2_POS)
#define GLB_CGEN_S1A_UART2_UMSK  (~(((1U << GLB_CGEN_S1A_UART2_LEN) - 1) << GLB_CGEN_S1A_UART2_POS))
#define GLB_CGEN_S1A_RSVD11      GLB_CGEN_S1A_RSVD11
#define GLB_CGEN_S1A_RSVD11_POS  (27U)
#define GLB_CGEN_S1A_RSVD11_LEN  (1U)
#define GLB_CGEN_S1A_RSVD11_MSK  (((1U << GLB_CGEN_S1A_RSVD11_LEN) - 1) << GLB_CGEN_S1A_RSVD11_POS)
#define GLB_CGEN_S1A_RSVD11_UMSK (~(((1U << GLB_CGEN_S1A_RSVD11_LEN) - 1) << GLB_CGEN_S1A_RSVD11_POS))
#define GLB_CGEN_S1A_RSVD12      GLB_CGEN_S1A_RSVD12
#define GLB_CGEN_S1A_RSVD12_POS  (28U)
#define GLB_CGEN_S1A_RSVD12_LEN  (1U)
#define GLB_CGEN_S1A_RSVD12_MSK  (((1U << GLB_CGEN_S1A_RSVD12_LEN) - 1) << GLB_CGEN_S1A_RSVD12_POS)
#define GLB_CGEN_S1A_RSVD12_UMSK (~(((1U << GLB_CGEN_S1A_RSVD12_LEN) - 1) << GLB_CGEN_S1A_RSVD12_POS))
#define GLB_CGEN_S1A_RSVD13      GLB_CGEN_S1A_RSVD13
#define GLB_CGEN_S1A_RSVD13_POS  (29U)
#define GLB_CGEN_S1A_RSVD13_LEN  (1U)
#define GLB_CGEN_S1A_RSVD13_MSK  (((1U << GLB_CGEN_S1A_RSVD13_LEN) - 1) << GLB_CGEN_S1A_RSVD13_POS)
#define GLB_CGEN_S1A_RSVD13_UMSK (~(((1U << GLB_CGEN_S1A_RSVD13_LEN) - 1) << GLB_CGEN_S1A_RSVD13_POS))
#define GLB_CGEN_S1A_RSVD14      GLB_CGEN_S1A_RSVD14
#define GLB_CGEN_S1A_RSVD14_POS  (30U)
#define GLB_CGEN_S1A_RSVD14_LEN  (1U)
#define GLB_CGEN_S1A_RSVD14_MSK  (((1U << GLB_CGEN_S1A_RSVD14_LEN) - 1) << GLB_CGEN_S1A_RSVD14_POS)
#define GLB_CGEN_S1A_RSVD14_UMSK (~(((1U << GLB_CGEN_S1A_RSVD14_LEN) - 1) << GLB_CGEN_S1A_RSVD14_POS))
#define GLB_CGEN_S1A_RSVD15      GLB_CGEN_S1A_RSVD15
#define GLB_CGEN_S1A_RSVD15_POS  (31U)
#define GLB_CGEN_S1A_RSVD15_LEN  (1U)
#define GLB_CGEN_S1A_RSVD15_MSK  (((1U << GLB_CGEN_S1A_RSVD15_LEN) - 1) << GLB_CGEN_S1A_RSVD15_POS)
#define GLB_CGEN_S1A_RSVD15_UMSK (~(((1U << GLB_CGEN_S1A_RSVD15_LEN) - 1) << GLB_CGEN_S1A_RSVD15_POS))

/* 0x588 : cgen_s1_ext + cgen_s3 */
#define GLB_CGEN_CFG2_OFFSET             (0x588)
#define GLB_CGEN_S0                      GLB_CGEN_S0
#define GLB_CGEN_S0_POS                  (0U)
#define GLB_CGEN_S0_LEN                  (1U)
#define GLB_CGEN_S0_MSK                  (((1U << GLB_CGEN_S0_LEN) - 1) << GLB_CGEN_S0_POS)
#define GLB_CGEN_S0_UMSK                 (~(((1U << GLB_CGEN_S0_LEN) - 1) << GLB_CGEN_S0_POS))
#define GLB_CGEN_S2_WIFI                 GLB_CGEN_S2_WIFI
#define GLB_CGEN_S2_WIFI_POS             (4U)
#define GLB_CGEN_S2_WIFI_LEN             (1U)
#define GLB_CGEN_S2_WIFI_MSK             (((1U << GLB_CGEN_S2_WIFI_LEN) - 1) << GLB_CGEN_S2_WIFI_POS)
#define GLB_CGEN_S2_WIFI_UMSK            (~(((1U << GLB_CGEN_S2_WIFI_LEN) - 1) << GLB_CGEN_S2_WIFI_POS))
#define GLB_CGEN_S3_BT_BLE2              GLB_CGEN_S3_BT_BLE2
#define GLB_CGEN_S3_BT_BLE2_POS          (10U)
#define GLB_CGEN_S3_BT_BLE2_LEN          (1U)
#define GLB_CGEN_S3_BT_BLE2_MSK          (((1U << GLB_CGEN_S3_BT_BLE2_LEN) - 1) << GLB_CGEN_S3_BT_BLE2_POS)
#define GLB_CGEN_S3_BT_BLE2_UMSK         (~(((1U << GLB_CGEN_S3_BT_BLE2_LEN) - 1) << GLB_CGEN_S3_BT_BLE2_POS))
#define GLB_CGEN_S3_M1542                GLB_CGEN_S3_M1542
#define GLB_CGEN_S3_M1542_POS            (11U)
#define GLB_CGEN_S3_M1542_LEN            (1U)
#define GLB_CGEN_S3_M1542_MSK            (((1U << GLB_CGEN_S3_M1542_LEN) - 1) << GLB_CGEN_S3_M1542_POS)
#define GLB_CGEN_S3_M1542_UMSK           (~(((1U << GLB_CGEN_S3_M1542_LEN) - 1) << GLB_CGEN_S3_M1542_POS))
#define GLB_CGEN_S1_EXT_EMI_MISC         GLB_CGEN_S1_EXT_EMI_MISC
#define GLB_CGEN_S1_EXT_EMI_MISC_POS     (16U)
#define GLB_CGEN_S1_EXT_EMI_MISC_LEN     (1U)
#define GLB_CGEN_S1_EXT_EMI_MISC_MSK     (((1U << GLB_CGEN_S1_EXT_EMI_MISC_LEN) - 1) << GLB_CGEN_S1_EXT_EMI_MISC_POS)
#define GLB_CGEN_S1_EXT_EMI_MISC_UMSK    (~(((1U << GLB_CGEN_S1_EXT_EMI_MISC_LEN) - 1) << GLB_CGEN_S1_EXT_EMI_MISC_POS))
#define GLB_CGEN_S1_EXT_PSRAM0_CTRL      GLB_CGEN_S1_EXT_PSRAM0_CTRL
#define GLB_CGEN_S1_EXT_PSRAM0_CTRL_POS  (17U)
#define GLB_CGEN_S1_EXT_PSRAM0_CTRL_LEN  (1U)
#define GLB_CGEN_S1_EXT_PSRAM0_CTRL_MSK  (((1U << GLB_CGEN_S1_EXT_PSRAM0_CTRL_LEN) - 1) << GLB_CGEN_S1_EXT_PSRAM0_CTRL_POS)
#define GLB_CGEN_S1_EXT_PSRAM0_CTRL_UMSK (~(((1U << GLB_CGEN_S1_EXT_PSRAM0_CTRL_LEN) - 1) << GLB_CGEN_S1_EXT_PSRAM0_CTRL_POS))
#define GLB_CGEN_S1_EXT_PSRAM_CTRL       GLB_CGEN_S1_EXT_PSRAM_CTRL
#define GLB_CGEN_S1_EXT_PSRAM_CTRL_POS   (18U)
#define GLB_CGEN_S1_EXT_PSRAM_CTRL_LEN   (1U)
#define GLB_CGEN_S1_EXT_PSRAM_CTRL_MSK   (((1U << GLB_CGEN_S1_EXT_PSRAM_CTRL_LEN) - 1) << GLB_CGEN_S1_EXT_PSRAM_CTRL_POS)
#define GLB_CGEN_S1_EXT_PSRAM_CTRL_UMSK  (~(((1U << GLB_CGEN_S1_EXT_PSRAM_CTRL_LEN) - 1) << GLB_CGEN_S1_EXT_PSRAM_CTRL_POS))
#define GLB_CGEN_S1_EXT_USB              GLB_CGEN_S1_EXT_USB
#define GLB_CGEN_S1_EXT_USB_POS          (19U)
#define GLB_CGEN_S1_EXT_USB_LEN          (1U)
#define GLB_CGEN_S1_EXT_USB_MSK          (((1U << GLB_CGEN_S1_EXT_USB_LEN) - 1) << GLB_CGEN_S1_EXT_USB_POS)
#define GLB_CGEN_S1_EXT_USB_UMSK         (~(((1U << GLB_CGEN_S1_EXT_USB_LEN) - 1) << GLB_CGEN_S1_EXT_USB_POS))
#define GLB_CGEN_S1_EXT_MIX2             GLB_CGEN_S1_EXT_MIX2
#define GLB_CGEN_S1_EXT_MIX2_POS         (20U)
#define GLB_CGEN_S1_EXT_MIX2_LEN         (1U)
#define GLB_CGEN_S1_EXT_MIX2_MSK         (((1U << GLB_CGEN_S1_EXT_MIX2_LEN) - 1) << GLB_CGEN_S1_EXT_MIX2_POS)
#define GLB_CGEN_S1_EXT_MIX2_UMSK        (~(((1U << GLB_CGEN_S1_EXT_MIX2_LEN) - 1) << GLB_CGEN_S1_EXT_MIX2_POS))
#define GLB_CGEN_S1_EXT_AUDIO            GLB_CGEN_S1_EXT_AUDIO
#define GLB_CGEN_S1_EXT_AUDIO_POS        (21U)
#define GLB_CGEN_S1_EXT_AUDIO_LEN        (1U)
#define GLB_CGEN_S1_EXT_AUDIO_MSK        (((1U << GLB_CGEN_S1_EXT_AUDIO_LEN) - 1) << GLB_CGEN_S1_EXT_AUDIO_POS)
#define GLB_CGEN_S1_EXT_AUDIO_UMSK       (~(((1U << GLB_CGEN_S1_EXT_AUDIO_LEN) - 1) << GLB_CGEN_S1_EXT_AUDIO_POS))
#define GLB_CGEN_S1_EXT_SDH              GLB_CGEN_S1_EXT_SDH
#define GLB_CGEN_S1_EXT_SDH_POS          (22U)
#define GLB_CGEN_S1_EXT_SDH_LEN          (1U)
#define GLB_CGEN_S1_EXT_SDH_MSK          (((1U << GLB_CGEN_S1_EXT_SDH_LEN) - 1) << GLB_CGEN_S1_EXT_SDH_POS)
#define GLB_CGEN_S1_EXT_SDH_UMSK         (~(((1U << GLB_CGEN_S1_EXT_SDH_LEN) - 1) << GLB_CGEN_S1_EXT_SDH_POS))
#define GLB_CGEN_S1_EXT_EMAC             GLB_CGEN_S1_EXT_EMAC
#define GLB_CGEN_S1_EXT_EMAC_POS         (23U)
#define GLB_CGEN_S1_EXT_EMAC_LEN         (1U)
#define GLB_CGEN_S1_EXT_EMAC_MSK         (((1U << GLB_CGEN_S1_EXT_EMAC_LEN) - 1) << GLB_CGEN_S1_EXT_EMAC_POS)
#define GLB_CGEN_S1_EXT_EMAC_UMSK        (~(((1U << GLB_CGEN_S1_EXT_EMAC_LEN) - 1) << GLB_CGEN_S1_EXT_EMAC_POS))
#define GLB_CGEN_S1_EXT_DMA2             GLB_CGEN_S1_EXT_DMA2
#define GLB_CGEN_S1_EXT_DMA2_POS         (24U)
#define GLB_CGEN_S1_EXT_DMA2_LEN         (1U)
#define GLB_CGEN_S1_EXT_DMA2_MSK         (((1U << GLB_CGEN_S1_EXT_DMA2_LEN) - 1) << GLB_CGEN_S1_EXT_DMA2_POS)
#define GLB_CGEN_S1_EXT_DMA2_UMSK        (~(((1U << GLB_CGEN_S1_EXT_DMA2_LEN) - 1) << GLB_CGEN_S1_EXT_DMA2_POS))
#define GLB_CGEN_S1_EXT_PIO              GLB_CGEN_S1_EXT_PIO
#define GLB_CGEN_S1_EXT_PIO_POS          (25U)
#define GLB_CGEN_S1_EXT_PIO_LEN          (1U)
#define GLB_CGEN_S1_EXT_PIO_MSK          (((1U << GLB_CGEN_S1_EXT_PIO_LEN) - 1) << GLB_CGEN_S1_EXT_PIO_POS)
#define GLB_CGEN_S1_EXT_PIO_UMSK         (~(((1U << GLB_CGEN_S1_EXT_PIO_LEN) - 1) << GLB_CGEN_S1_EXT_PIO_POS))
#define GLB_CGEN_S1_EXT_RSVD10           GLB_CGEN_S1_EXT_RSVD10
#define GLB_CGEN_S1_EXT_RSVD10_POS       (26U)
#define GLB_CGEN_S1_EXT_RSVD10_LEN       (1U)
#define GLB_CGEN_S1_EXT_RSVD10_MSK       (((1U << GLB_CGEN_S1_EXT_RSVD10_LEN) - 1) << GLB_CGEN_S1_EXT_RSVD10_POS)
#define GLB_CGEN_S1_EXT_RSVD10_UMSK      (~(((1U << GLB_CGEN_S1_EXT_RSVD10_LEN) - 1) << GLB_CGEN_S1_EXT_RSVD10_POS))
#define GLB_CGEN_S1_EXT_RSVD11           GLB_CGEN_S1_EXT_RSVD11
#define GLB_CGEN_S1_EXT_RSVD11_POS       (27U)
#define GLB_CGEN_S1_EXT_RSVD11_LEN       (1U)
#define GLB_CGEN_S1_EXT_RSVD11_MSK       (((1U << GLB_CGEN_S1_EXT_RSVD11_LEN) - 1) << GLB_CGEN_S1_EXT_RSVD11_POS)
#define GLB_CGEN_S1_EXT_RSVD11_UMSK      (~(((1U << GLB_CGEN_S1_EXT_RSVD11_LEN) - 1) << GLB_CGEN_S1_EXT_RSVD11_POS))

/* 0x58C : cgen_cfg3 */
#define GLB_CGEN_CFG3_OFFSET              (0x58C)
#define GLB_CGEN_ISP_WIFIPLL_80M          GLB_CGEN_ISP_WIFIPLL_80M
#define GLB_CGEN_ISP_WIFIPLL_80M_POS      (2U)
#define GLB_CGEN_ISP_WIFIPLL_80M_LEN      (1U)
#define GLB_CGEN_ISP_WIFIPLL_80M_MSK      (((1U << GLB_CGEN_ISP_WIFIPLL_80M_LEN) - 1) << GLB_CGEN_ISP_WIFIPLL_80M_POS)
#define GLB_CGEN_ISP_WIFIPLL_80M_UMSK     (~(((1U << GLB_CGEN_ISP_WIFIPLL_80M_LEN) - 1) << GLB_CGEN_ISP_WIFIPLL_80M_POS))
#define GLB_CGEN_ISP_AUPLL_DIV5           GLB_CGEN_ISP_AUPLL_DIV5
#define GLB_CGEN_ISP_AUPLL_DIV5_POS       (3U)
#define GLB_CGEN_ISP_AUPLL_DIV5_LEN       (1U)
#define GLB_CGEN_ISP_AUPLL_DIV5_MSK       (((1U << GLB_CGEN_ISP_AUPLL_DIV5_LEN) - 1) << GLB_CGEN_ISP_AUPLL_DIV5_POS)
#define GLB_CGEN_ISP_AUPLL_DIV5_UMSK      (~(((1U << GLB_CGEN_ISP_AUPLL_DIV5_LEN) - 1) << GLB_CGEN_ISP_AUPLL_DIV5_POS))
#define GLB_CGEN_ISP_AUPLL_DIV6           GLB_CGEN_ISP_AUPLL_DIV6
#define GLB_CGEN_ISP_AUPLL_DIV6_POS       (4U)
#define GLB_CGEN_ISP_AUPLL_DIV6_LEN       (1U)
#define GLB_CGEN_ISP_AUPLL_DIV6_MSK       (((1U << GLB_CGEN_ISP_AUPLL_DIV6_LEN) - 1) << GLB_CGEN_ISP_AUPLL_DIV6_POS)
#define GLB_CGEN_ISP_AUPLL_DIV6_UMSK      (~(((1U << GLB_CGEN_ISP_AUPLL_DIV6_LEN) - 1) << GLB_CGEN_ISP_AUPLL_DIV6_POS))
#define GLB_CGEN_TOP_AUPLL_DIV5           GLB_CGEN_TOP_AUPLL_DIV5
#define GLB_CGEN_TOP_AUPLL_DIV5_POS       (5U)
#define GLB_CGEN_TOP_AUPLL_DIV5_LEN       (1U)
#define GLB_CGEN_TOP_AUPLL_DIV5_MSK       (((1U << GLB_CGEN_TOP_AUPLL_DIV5_LEN) - 1) << GLB_CGEN_TOP_AUPLL_DIV5_POS)
#define GLB_CGEN_TOP_AUPLL_DIV5_UMSK      (~(((1U << GLB_CGEN_TOP_AUPLL_DIV5_LEN) - 1) << GLB_CGEN_TOP_AUPLL_DIV5_POS))
#define GLB_CGEN_TOP_AUPLL_DIV6           GLB_CGEN_TOP_AUPLL_DIV6
#define GLB_CGEN_TOP_AUPLL_DIV6_POS       (6U)
#define GLB_CGEN_TOP_AUPLL_DIV6_LEN       (1U)
#define GLB_CGEN_TOP_AUPLL_DIV6_MSK       (((1U << GLB_CGEN_TOP_AUPLL_DIV6_LEN) - 1) << GLB_CGEN_TOP_AUPLL_DIV6_POS)
#define GLB_CGEN_TOP_AUPLL_DIV6_UMSK      (~(((1U << GLB_CGEN_TOP_AUPLL_DIV6_LEN) - 1) << GLB_CGEN_TOP_AUPLL_DIV6_POS))
#define GLB_CGEN_PSRAMB_WIFIPLL_320M      GLB_CGEN_PSRAMB_WIFIPLL_320M
#define GLB_CGEN_PSRAMB_WIFIPLL_320M_POS  (7U)
#define GLB_CGEN_PSRAMB_WIFIPLL_320M_LEN  (1U)
#define GLB_CGEN_PSRAMB_WIFIPLL_320M_MSK  (((1U << GLB_CGEN_PSRAMB_WIFIPLL_320M_LEN) - 1) << GLB_CGEN_PSRAMB_WIFIPLL_320M_POS)
#define GLB_CGEN_PSRAMB_WIFIPLL_320M_UMSK (~(((1U << GLB_CGEN_PSRAMB_WIFIPLL_320M_LEN) - 1) << GLB_CGEN_PSRAMB_WIFIPLL_320M_POS))
#define GLB_CGEN_PSRAMB_AUPLL_DIV1        GLB_CGEN_PSRAMB_AUPLL_DIV1
#define GLB_CGEN_PSRAMB_AUPLL_DIV1_POS    (8U)
#define GLB_CGEN_PSRAMB_AUPLL_DIV1_LEN    (1U)
#define GLB_CGEN_PSRAMB_AUPLL_DIV1_MSK    (((1U << GLB_CGEN_PSRAMB_AUPLL_DIV1_LEN) - 1) << GLB_CGEN_PSRAMB_AUPLL_DIV1_POS)
#define GLB_CGEN_PSRAMB_AUPLL_DIV1_UMSK   (~(((1U << GLB_CGEN_PSRAMB_AUPLL_DIV1_LEN) - 1) << GLB_CGEN_PSRAMB_AUPLL_DIV1_POS))
#define GLB_CGEN_TOP_WIFIPLL_240M         GLB_CGEN_TOP_WIFIPLL_240M
#define GLB_CGEN_TOP_WIFIPLL_240M_POS     (13U)
#define GLB_CGEN_TOP_WIFIPLL_240M_LEN     (1U)
#define GLB_CGEN_TOP_WIFIPLL_240M_MSK     (((1U << GLB_CGEN_TOP_WIFIPLL_240M_LEN) - 1) << GLB_CGEN_TOP_WIFIPLL_240M_POS)
#define GLB_CGEN_TOP_WIFIPLL_240M_UMSK    (~(((1U << GLB_CGEN_TOP_WIFIPLL_240M_LEN) - 1) << GLB_CGEN_TOP_WIFIPLL_240M_POS))
#define GLB_CGEN_TOP_WIFIPLL_320M         GLB_CGEN_TOP_WIFIPLL_320M
#define GLB_CGEN_TOP_WIFIPLL_320M_POS     (14U)
#define GLB_CGEN_TOP_WIFIPLL_320M_LEN     (1U)
#define GLB_CGEN_TOP_WIFIPLL_320M_MSK     (((1U << GLB_CGEN_TOP_WIFIPLL_320M_LEN) - 1) << GLB_CGEN_TOP_WIFIPLL_320M_POS)
#define GLB_CGEN_TOP_WIFIPLL_320M_UMSK    (~(((1U << GLB_CGEN_TOP_WIFIPLL_320M_LEN) - 1) << GLB_CGEN_TOP_WIFIPLL_320M_POS))
#define GLB_CGEN_TOP_AUPLL_DIV2           GLB_CGEN_TOP_AUPLL_DIV2
#define GLB_CGEN_TOP_AUPLL_DIV2_POS       (15U)
#define GLB_CGEN_TOP_AUPLL_DIV2_LEN       (1U)
#define GLB_CGEN_TOP_AUPLL_DIV2_MSK       (((1U << GLB_CGEN_TOP_AUPLL_DIV2_LEN) - 1) << GLB_CGEN_TOP_AUPLL_DIV2_POS)
#define GLB_CGEN_TOP_AUPLL_DIV2_UMSK      (~(((1U << GLB_CGEN_TOP_AUPLL_DIV2_LEN) - 1) << GLB_CGEN_TOP_AUPLL_DIV2_POS))
#define GLB_CGEN_TOP_AUPLL_DIV1           GLB_CGEN_TOP_AUPLL_DIV1
#define GLB_CGEN_TOP_AUPLL_DIV1_POS       (16U)
#define GLB_CGEN_TOP_AUPLL_DIV1_LEN       (1U)
#define GLB_CGEN_TOP_AUPLL_DIV1_MSK       (((1U << GLB_CGEN_TOP_AUPLL_DIV1_LEN) - 1) << GLB_CGEN_TOP_AUPLL_DIV1_POS)
#define GLB_CGEN_TOP_AUPLL_DIV1_UMSK      (~(((1U << GLB_CGEN_TOP_AUPLL_DIV1_LEN) - 1) << GLB_CGEN_TOP_AUPLL_DIV1_POS))



/* 0x130 : dma_cfg0 */
#define GLB_DMA_CFG0_OFFSET (0x130)
#define GLB_DMA_CLK_EN      GLB_DMA_CLK_EN
#define GLB_DMA_CLK_EN_POS  (24U)
#define GLB_DMA_CLK_EN_LEN  (8U)
#define GLB_DMA_CLK_EN_MSK  (((1U << GLB_DMA_CLK_EN_LEN) - 1) << GLB_DMA_CLK_EN_POS)
#define GLB_DMA_CLK_EN_UMSK (~(((1U << GLB_DMA_CLK_EN_LEN) - 1) << GLB_DMA_CLK_EN_POS))

/* 0x134 : dma_cfg1 */
#define GLB_DMA_CFG1_OFFSET  (0x134)
#define GLB_DMA2_CLK_EN      GLB_DMA2_CLK_EN
#define GLB_DMA2_CLK_EN_POS  (24U)
#define GLB_DMA2_CLK_EN_LEN  (8U)
#define GLB_DMA2_CLK_EN_MSK  (((1U << GLB_DMA2_CLK_EN_LEN) - 1) << GLB_DMA2_CLK_EN_POS)
#define GLB_DMA2_CLK_EN_UMSK (~(((1U << GLB_DMA2_CLK_EN_LEN) - 1) << GLB_DMA2_CLK_EN_POS))

/* 0x138 : dma_cfg2 */
#define GLB_DMA_CFG2_OFFSET     (0x138)
#define GLB_REG_DMA_CN_SEL      GLB_REG_DMA_CN_SEL
#define GLB_REG_DMA_CN_SEL_POS  (0U)
#define GLB_REG_DMA_CN_SEL_LEN  (32U)
#define GLB_REG_DMA_CN_SEL_MSK  (((1U << GLB_REG_DMA_CN_SEL_LEN) - 1) << GLB_REG_DMA_CN_SEL_POS)
#define GLB_REG_DMA_CN_SEL_UMSK (~(((1U << GLB_REG_DMA_CN_SEL_LEN) - 1) << GLB_REG_DMA_CN_SEL_POS))





/* 0x8C4 : gpio_cfg0 */
#define GLB_GPIO_CFG0_OFFSET             (0x8C4)
#define GLB_REG_GPIO_0_IE                GLB_REG_GPIO_0_IE
#define GLB_REG_GPIO_0_IE_POS            (0U)
#define GLB_REG_GPIO_0_IE_LEN            (1U)
#define GLB_REG_GPIO_0_IE_MSK            (((1U << GLB_REG_GPIO_0_IE_LEN) - 1) << GLB_REG_GPIO_0_IE_POS)
#define GLB_REG_GPIO_0_IE_UMSK           (~(((1U << GLB_REG_GPIO_0_IE_LEN) - 1) << GLB_REG_GPIO_0_IE_POS))
#define GLB_REG_GPIO_0_SMT               GLB_REG_GPIO_0_SMT
#define GLB_REG_GPIO_0_SMT_POS           (1U)
#define GLB_REG_GPIO_0_SMT_LEN           (1U)
#define GLB_REG_GPIO_0_SMT_MSK           (((1U << GLB_REG_GPIO_0_SMT_LEN) - 1) << GLB_REG_GPIO_0_SMT_POS)
#define GLB_REG_GPIO_0_SMT_UMSK          (~(((1U << GLB_REG_GPIO_0_SMT_LEN) - 1) << GLB_REG_GPIO_0_SMT_POS))
#define GLB_REG_GPIO_0_DRV               GLB_REG_GPIO_0_DRV
#define GLB_REG_GPIO_0_DRV_POS           (2U)
#define GLB_REG_GPIO_0_DRV_LEN           (2U)
#define GLB_REG_GPIO_0_DRV_MSK           (((1U << GLB_REG_GPIO_0_DRV_LEN) - 1) << GLB_REG_GPIO_0_DRV_POS)
#define GLB_REG_GPIO_0_DRV_UMSK          (~(((1U << GLB_REG_GPIO_0_DRV_LEN) - 1) << GLB_REG_GPIO_0_DRV_POS))
#define GLB_REG_GPIO_0_PU                GLB_REG_GPIO_0_PU
#define GLB_REG_GPIO_0_PU_POS            (4U)
#define GLB_REG_GPIO_0_PU_LEN            (1U)
#define GLB_REG_GPIO_0_PU_MSK            (((1U << GLB_REG_GPIO_0_PU_LEN) - 1) << GLB_REG_GPIO_0_PU_POS)
#define GLB_REG_GPIO_0_PU_UMSK           (~(((1U << GLB_REG_GPIO_0_PU_LEN) - 1) << GLB_REG_GPIO_0_PU_POS))
#define GLB_REG_GPIO_0_PD                GLB_REG_GPIO_0_PD
#define GLB_REG_GPIO_0_PD_POS            (5U)
#define GLB_REG_GPIO_0_PD_LEN            (1U)
#define GLB_REG_GPIO_0_PD_MSK            (((1U << GLB_REG_GPIO_0_PD_LEN) - 1) << GLB_REG_GPIO_0_PD_POS)
#define GLB_REG_GPIO_0_PD_UMSK           (~(((1U << GLB_REG_GPIO_0_PD_LEN) - 1) << GLB_REG_GPIO_0_PD_POS))
#define GLB_REG_GPIO_0_OE                GLB_REG_GPIO_0_OE
#define GLB_REG_GPIO_0_OE_POS            (6U)
#define GLB_REG_GPIO_0_OE_LEN            (1U)
#define GLB_REG_GPIO_0_OE_MSK            (((1U << GLB_REG_GPIO_0_OE_LEN) - 1) << GLB_REG_GPIO_0_OE_POS)
#define GLB_REG_GPIO_0_OE_UMSK           (~(((1U << GLB_REG_GPIO_0_OE_LEN) - 1) << GLB_REG_GPIO_0_OE_POS))
#define GLB_REG_GPIO_0_FUNC_SEL          GLB_REG_GPIO_0_FUNC_SEL
#define GLB_REG_GPIO_0_FUNC_SEL_POS      (8U)
#define GLB_REG_GPIO_0_FUNC_SEL_LEN      (5U)
#define GLB_REG_GPIO_0_FUNC_SEL_MSK      (((1U << GLB_REG_GPIO_0_FUNC_SEL_LEN) - 1) << GLB_REG_GPIO_0_FUNC_SEL_POS)
#define GLB_REG_GPIO_0_FUNC_SEL_UMSK     (~(((1U << GLB_REG_GPIO_0_FUNC_SEL_LEN) - 1) << GLB_REG_GPIO_0_FUNC_SEL_POS))
#define GLB_REG_GPIO_0_INT_MODE_SET      GLB_REG_GPIO_0_INT_MODE_SET
#define GLB_REG_GPIO_0_INT_MODE_SET_POS  (16U)
#define GLB_REG_GPIO_0_INT_MODE_SET_LEN  (4U)
#define GLB_REG_GPIO_0_INT_MODE_SET_MSK  (((1U << GLB_REG_GPIO_0_INT_MODE_SET_LEN) - 1) << GLB_REG_GPIO_0_INT_MODE_SET_POS)
#define GLB_REG_GPIO_0_INT_MODE_SET_UMSK (~(((1U << GLB_REG_GPIO_0_INT_MODE_SET_LEN) - 1) << GLB_REG_GPIO_0_INT_MODE_SET_POS))
#define GLB_REG_GPIO_0_INT_CLR           GLB_REG_GPIO_0_INT_CLR
#define GLB_REG_GPIO_0_INT_CLR_POS       (20U)
#define GLB_REG_GPIO_0_INT_CLR_LEN       (1U)
#define GLB_REG_GPIO_0_INT_CLR_MSK       (((1U << GLB_REG_GPIO_0_INT_CLR_LEN) - 1) << GLB_REG_GPIO_0_INT_CLR_POS)
#define GLB_REG_GPIO_0_INT_CLR_UMSK      (~(((1U << GLB_REG_GPIO_0_INT_CLR_LEN) - 1) << GLB_REG_GPIO_0_INT_CLR_POS))
#define GLB_GPIO_0_INT_STAT              GLB_GPIO_0_INT_STAT
#define GLB_GPIO_0_INT_STAT_POS          (21U)
#define GLB_GPIO_0_INT_STAT_LEN          (1U)
#define GLB_GPIO_0_INT_STAT_MSK          (((1U << GLB_GPIO_0_INT_STAT_LEN) - 1) << GLB_GPIO_0_INT_STAT_POS)
#define GLB_GPIO_0_INT_STAT_UMSK         (~(((1U << GLB_GPIO_0_INT_STAT_LEN) - 1) << GLB_GPIO_0_INT_STAT_POS))
#define GLB_REG_GPIO_0_INT_MASK          GLB_REG_GPIO_0_INT_MASK
#define GLB_REG_GPIO_0_INT_MASK_POS      (22U)
#define GLB_REG_GPIO_0_INT_MASK_LEN      (1U)
#define GLB_REG_GPIO_0_INT_MASK_MSK      (((1U << GLB_REG_GPIO_0_INT_MASK_LEN) - 1) << GLB_REG_GPIO_0_INT_MASK_POS)
#define GLB_REG_GPIO_0_INT_MASK_UMSK     (~(((1U << GLB_REG_GPIO_0_INT_MASK_LEN) - 1) << GLB_REG_GPIO_0_INT_MASK_POS))
#define GLB_REG_GPIO_0_O                 GLB_REG_GPIO_0_O
#define GLB_REG_GPIO_0_O_POS             (24U)
#define GLB_REG_GPIO_0_O_LEN             (1U)
#define GLB_REG_GPIO_0_O_MSK             (((1U << GLB_REG_GPIO_0_O_LEN) - 1) << GLB_REG_GPIO_0_O_POS)
#define GLB_REG_GPIO_0_O_UMSK            (~(((1U << GLB_REG_GPIO_0_O_LEN) - 1) << GLB_REG_GPIO_0_O_POS))
#define GLB_REG_GPIO_0_SET               GLB_REG_GPIO_0_SET
#define GLB_REG_GPIO_0_SET_POS           (25U)
#define GLB_REG_GPIO_0_SET_LEN           (1U)
#define GLB_REG_GPIO_0_SET_MSK           (((1U << GLB_REG_GPIO_0_SET_LEN) - 1) << GLB_REG_GPIO_0_SET_POS)
#define GLB_REG_GPIO_0_SET_UMSK          (~(((1U << GLB_REG_GPIO_0_SET_LEN) - 1) << GLB_REG_GPIO_0_SET_POS))
#define GLB_REG_GPIO_0_CLR               GLB_REG_GPIO_0_CLR
#define GLB_REG_GPIO_0_CLR_POS           (26U)
#define GLB_REG_GPIO_0_CLR_LEN           (1U)
#define GLB_REG_GPIO_0_CLR_MSK           (((1U << GLB_REG_GPIO_0_CLR_LEN) - 1) << GLB_REG_GPIO_0_CLR_POS)
#define GLB_REG_GPIO_0_CLR_UMSK          (~(((1U << GLB_REG_GPIO_0_CLR_LEN) - 1) << GLB_REG_GPIO_0_CLR_POS))
#define GLB_REG_GPIO_0_I                 GLB_REG_GPIO_0_I
#define GLB_REG_GPIO_0_I_POS             (28U)
#define GLB_REG_GPIO_0_I_LEN             (1U)
#define GLB_REG_GPIO_0_I_MSK             (((1U << GLB_REG_GPIO_0_I_LEN) - 1) << GLB_REG_GPIO_0_I_POS)
#define GLB_REG_GPIO_0_I_UMSK            (~(((1U << GLB_REG_GPIO_0_I_LEN) - 1) << GLB_REG_GPIO_0_I_POS))
#define GLB_REG_GPIO_0_MODE              GLB_REG_GPIO_0_MODE
#define GLB_REG_GPIO_0_MODE_POS          (30U)
#define GLB_REG_GPIO_0_MODE_LEN          (2U)
#define GLB_REG_GPIO_0_MODE_MSK          (((1U << GLB_REG_GPIO_0_MODE_LEN) - 1) << GLB_REG_GPIO_0_MODE_POS)
#define GLB_REG_GPIO_0_MODE_UMSK         (~(((1U << GLB_REG_GPIO_0_MODE_LEN) - 1) << GLB_REG_GPIO_0_MODE_POS))






#define HBN_XTAL_FLAG_VALUE        (0x8)





















#endif /* __GLB_REG_H__ */
