
#ifndef __MSP_BL606P_GLB_H__
#define __MSP_BL606P_GLB_H__

/* 0x340 : audio_cfg0 */
#define GLB_AUDIO_CFG0_OFFSET          (0x340)
#define GLB_REG_AUDIO_PDM_CLK_DIV      GLB_REG_AUDIO_PDM_CLK_DIV
#define GLB_REG_AUDIO_PDM_CLK_DIV_POS  (0U)
#define GLB_REG_AUDIO_PDM_CLK_DIV_LEN  (6U)
#define GLB_REG_AUDIO_PDM_CLK_DIV_MSK  (((1U << GLB_REG_AUDIO_PDM_CLK_DIV_LEN) - 1) << GLB_REG_AUDIO_PDM_CLK_DIV_POS)
#define GLB_REG_AUDIO_PDM_CLK_DIV_UMSK (~(((1U << GLB_REG_AUDIO_PDM_CLK_DIV_LEN) - 1) << GLB_REG_AUDIO_PDM_CLK_DIV_POS))
#define GLB_REG_AUDIO_PDM_CLK_EN       GLB_REG_AUDIO_PDM_CLK_EN
#define GLB_REG_AUDIO_PDM_CLK_EN_POS   (7U)
#define GLB_REG_AUDIO_PDM_CLK_EN_LEN   (1U)
#define GLB_REG_AUDIO_PDM_CLK_EN_MSK   (((1U << GLB_REG_AUDIO_PDM_CLK_EN_LEN) - 1) << GLB_REG_AUDIO_PDM_CLK_EN_POS)
#define GLB_REG_AUDIO_PDM_CLK_EN_UMSK  (~(((1U << GLB_REG_AUDIO_PDM_CLK_EN_LEN) - 1) << GLB_REG_AUDIO_PDM_CLK_EN_POS))
#define GLB_REG_AUDIO_ADC_CLK_DIV      GLB_REG_AUDIO_ADC_CLK_DIV
#define GLB_REG_AUDIO_ADC_CLK_DIV_POS  (8U)
#define GLB_REG_AUDIO_ADC_CLK_DIV_LEN  (6U)
#define GLB_REG_AUDIO_ADC_CLK_DIV_MSK  (((1U << GLB_REG_AUDIO_ADC_CLK_DIV_LEN) - 1) << GLB_REG_AUDIO_ADC_CLK_DIV_POS)
#define GLB_REG_AUDIO_ADC_CLK_DIV_UMSK (~(((1U << GLB_REG_AUDIO_ADC_CLK_DIV_LEN) - 1) << GLB_REG_AUDIO_ADC_CLK_DIV_POS))
#define GLB_REG_AUDIO_ADC_CLK_EN       GLB_REG_AUDIO_ADC_CLK_EN
#define GLB_REG_AUDIO_ADC_CLK_EN_POS   (15U)
#define GLB_REG_AUDIO_ADC_CLK_EN_LEN   (1U)
#define GLB_REG_AUDIO_ADC_CLK_EN_MSK   (((1U << GLB_REG_AUDIO_ADC_CLK_EN_LEN) - 1) << GLB_REG_AUDIO_ADC_CLK_EN_POS)
#define GLB_REG_AUDIO_ADC_CLK_EN_UMSK  (~(((1U << GLB_REG_AUDIO_ADC_CLK_EN_LEN) - 1) << GLB_REG_AUDIO_ADC_CLK_EN_POS))
#define GLB_REG_AUDIO_DAC_CLK_DIV      GLB_REG_AUDIO_DAC_CLK_DIV
#define GLB_REG_AUDIO_DAC_CLK_DIV_POS  (16U)
#define GLB_REG_AUDIO_DAC_CLK_DIV_LEN  (6U)
#define GLB_REG_AUDIO_DAC_CLK_DIV_MSK  (((1U << GLB_REG_AUDIO_DAC_CLK_DIV_LEN) - 1) << GLB_REG_AUDIO_DAC_CLK_DIV_POS)
#define GLB_REG_AUDIO_DAC_CLK_DIV_UMSK (~(((1U << GLB_REG_AUDIO_DAC_CLK_DIV_LEN) - 1) << GLB_REG_AUDIO_DAC_CLK_DIV_POS))
#define GLB_REG_AUDIO_DAC_CLK_EN       GLB_REG_AUDIO_DAC_CLK_EN
#define GLB_REG_AUDIO_DAC_CLK_EN_POS   (23U)
#define GLB_REG_AUDIO_DAC_CLK_EN_LEN   (1U)
#define GLB_REG_AUDIO_DAC_CLK_EN_MSK   (((1U << GLB_REG_AUDIO_DAC_CLK_EN_LEN) - 1) << GLB_REG_AUDIO_DAC_CLK_EN_POS)
#define GLB_REG_AUDIO_DAC_CLK_EN_UMSK  (~(((1U << GLB_REG_AUDIO_DAC_CLK_EN_LEN) - 1) << GLB_REG_AUDIO_DAC_CLK_EN_POS))
#define GLB_REG_AUDIO_AUTO_DIV_EN      GLB_REG_AUDIO_AUTO_DIV_EN
#define GLB_REG_AUDIO_AUTO_DIV_EN_POS  (31U)
#define GLB_REG_AUDIO_AUTO_DIV_EN_LEN  (1U)
#define GLB_REG_AUDIO_AUTO_DIV_EN_MSK  (((1U << GLB_REG_AUDIO_AUTO_DIV_EN_LEN) - 1) << GLB_REG_AUDIO_AUTO_DIV_EN_POS)
#define GLB_REG_AUDIO_AUTO_DIV_EN_UMSK (~(((1U << GLB_REG_AUDIO_AUTO_DIV_EN_LEN) - 1) << GLB_REG_AUDIO_AUTO_DIV_EN_POS))

/* 0x344 : audio_cfg1 */
#define GLB_AUDIO_CFG1_OFFSET     (0x344)
#define GLB_REG_PADC_CLK_DIV      GLB_REG_PADC_CLK_DIV
#define GLB_REG_PADC_CLK_DIV_POS  (0U)
#define GLB_REG_PADC_CLK_DIV_LEN  (10U)
#define GLB_REG_PADC_CLK_DIV_MSK  (((1U << GLB_REG_PADC_CLK_DIV_LEN) - 1) << GLB_REG_PADC_CLK_DIV_POS)
#define GLB_REG_PADC_CLK_DIV_UMSK (~(((1U << GLB_REG_PADC_CLK_DIV_LEN) - 1) << GLB_REG_PADC_CLK_DIV_POS))
#define GLB_REG_PADC_CLK_EN       GLB_REG_PADC_CLK_EN
#define GLB_REG_PADC_CLK_EN_POS   (10U)
#define GLB_REG_PADC_CLK_EN_LEN   (1U)
#define GLB_REG_PADC_CLK_EN_MSK   (((1U << GLB_REG_PADC_CLK_EN_LEN) - 1) << GLB_REG_PADC_CLK_EN_POS)
#define GLB_REG_PADC_CLK_EN_UMSK  (~(((1U << GLB_REG_PADC_CLK_EN_LEN) - 1) << GLB_REG_PADC_CLK_EN_POS))

typedef enum {
    GLB_AHB_CLOCK_IP_CPU,
    GLB_AHB_CLOCK_IP_SDU,
    GLB_AHB_CLOCK_IP_SEC,
    GLB_AHB_CLOCK_IP_DMA_0,
    GLB_AHB_CLOCK_IP_DMA_1,
    GLB_AHB_CLOCK_IP_DMA_2,
    GLB_AHB_CLOCK_IP_CCI,
    GLB_AHB_CLOCK_IP_RF_TOP,
    GLB_AHB_CLOCK_IP_GPIP,
    GLB_AHB_CLOCK_IP_TZC,
    GLB_AHB_CLOCK_IP_EF_CTRL,
    GLB_AHB_CLOCK_IP_SF_CTRL,
    GLB_AHB_CLOCK_IP_EMAC,
    GLB_AHB_CLOCK_IP_UART0,
    GLB_AHB_CLOCK_IP_UART1,
    GLB_AHB_CLOCK_IP_UART2,
    GLB_AHB_CLOCK_IP_UART3,
    GLB_AHB_CLOCK_IP_SPI,
    GLB_AHB_CLOCK_IP_I2C,
    GLB_AHB_CLOCK_IP_PWM,
    GLB_AHB_CLOCK_IP_TIMER,
    GLB_AHB_CLOCK_IP_IR,
    GLB_AHB_CLOCK_IP_CHECKSUM,
    GLB_AHB_CLOCK_IP_QDEC,
    GLB_AHB_CLOCK_IP_KYS,
    GLB_AHB_CLOCK_IP_I2S,
    GLB_AHB_CLOCK_IP_USB11,
    GLB_AHB_CLOCK_IP_CAM,
    GLB_AHB_CLOCK_IP_MJPEG,
    GLB_AHB_CLOCK_IP_BT_BLE_NORMAL,
    GLB_AHB_CLOCK_IP_BT_BLE_LP,
    GLB_AHB_CLOCK_IP_ZB_NORMAL,
    GLB_AHB_CLOCK_IP_ZB_LP,
    GLB_AHB_CLOCK_IP_WIFI_NORMAL,
    GLB_AHB_CLOCK_IP_WIFI_LP,
    GLB_AHB_CLOCK_IP_BT_BLE_2_NORMAL,
    GLB_AHB_CLOCK_IP_BT_BLE_2_LP,
    GLB_AHB_CLOCK_IP_EMI_MISC,
    GLB_AHB_CLOCK_IP_PSRAM0_CTRL,
    GLB_AHB_CLOCK_IP_PSRAM1_CTRL,
    GLB_AHB_CLOCK_IP_USB20,
    GLB_AHB_CLOCK_IP_MIX2,
    GLB_AHB_CLOCK_IP_AUDIO,
    GLB_AHB_CLOCK_IP_SDH,
    GLB_AHB_CLOCK_IP_ZB2_NORMAL,
    GLB_AHB_CLOCK_IP_ZB2_LP,
    GLB_AHB_CLOCK_IP_I2C1,
    GLB_AHB_CLOCK_IP_WIFI_PHY,
    GLB_AHB_CLOCK_IP_WIFI_MAC_PHY,
    GLB_AHB_CLOCK_IP_WIFI_PLATFORM,
    GLB_AHB_CLOCK_IP_LZ4,
    GLB_AHB_CLOCK_IP_AUPDM,
    GLB_AHB_CLOCK_IP_GAUGE,
} GLB_AHB_CLOCK_IP_Type;


#define GLB_AHB_CLOCK_DMA_0           (0x1ULL<<GLB_AHB_CLOCK_IP_DMA_0)
#define GLB_AHB_CLOCK_DMA_1           (0x1ULL<<GLB_AHB_CLOCK_IP_DMA_1)
#define GLB_AHB_CLOCK_DMA_2           (0x1ULL<<GLB_AHB_CLOCK_IP_DMA_2)


BL_Err_Type msp_GLB_Set_Audio_ADC_CLK(uint8_t enable, uint8_t div);

#endif
