#ifndef _CLOCK_CONFIG_H
#define _CLOCK_CONFIG_H

#define BSP_ROOT_CLOCK_SOURCE   ROOT_CLOCK_SOURCE_DLL_144M

#if defined(BSP_ROOT_CLOCK_SOURCE)
#define BSP_HCLK_DIV  0
#define BSP_BCLK_DIV  1
#endif

#if defined(BSP_USING_UART0)||defined(BSP_USING_UART1)
#define BSP_UART_CLOCK_SOURCE  ROOT_CLOCK_SOURCE_DLL_96M
#define BSP_UART_CLOCK_DIV  0
#endif    
#if defined(BSP_USING_I2C0)
#define BSP_I2C_CLOCK_SOURCE  ROOT_CLOCK_SOURCE_DLL_BCLK
#define BSP_I2C_CLOCK_DIV  0
#endif
#if defined(BSP_USING_SPI0)
#define BSP_SPI_CLOCK_SOURCE  ROOT_CLOCK_SOURCE_DLL_BCLK
#define BSP_SPI_CLOCK_DIV  0
#endif
#if defined(BSP_USING_PWM)
#define BSP_PWM_CLOCK_SOURCE  ROOT_CLOCK_SOURCE_DLL_XCLK
#define BSP_PWM_CLOCK_DIV  0
#endif
#if defined(BSP_USING_IR)
#define BSP_IR_CLOCK_SOURCE  ROOT_CLOCK_SOURCE_DLL_XCLK
#define BSP_IR_CLOCK_DIV  0
#endif
#if defined(BSP_USING_I2S0)
#define BSP_I2S_CLOCK_SOURCE  ROOT_CLOCK_SOURCE_DLL_XCLK
#define BSP_I2S_CLOCK_DIV  0
#endif
#if defined(BSP_USING_ADC0)
#define BSP_ADC_CLOCK_SOURCE  ROOT_CLOCK_SOURCE_DLL_XCLK
#define BSP_ADC_CLOCK_DIV  0
#endif
#if defined(BSP_USING_DAC0)
#define BSP_DAC_CLOCK_SOURCE  ROOT_CLOCK_SOURCE_DLL_XCLK
#define BSP_DAC_CLOCK_DIV  0
#endif

#endif