
## 第一部分： 基础信息
name: xav                                            # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: v7.5.y                                    # <必选项> 组件版本号
description: av是一个轻量级的多媒体组件，主要包含AV基础框架、播放器和音频服务三部分。 # <必选项> 建议至少20字以上
type: common                                        # <必选项> 组件类型，为：solution, chip, board, common, sdk
tag: 多媒体播放器                                   # <可选项> 组件分类，缺省值： ''
keywords:                                           # <可选项> 标签，会影响到组件被搜索的效果，合理的标签很重要
  - base
license: Apache license v2.0                        # <可选项> 源代码的许可证，要确保所有代码、文件的许可证不冲突。如：MIT，Apache license v2.0，BSD

## 第二部分：依赖信息
#           指定该组件依赖的组件及版本
# sdk_chip:                                # <可选项> 该组件依赖sdk组件，合理的依赖才能保证组件能编译、使用
#   - sdk_chip_csky_dummy: v7.4.0
#   - sdk_chip_riscv_dummy: v7.4.0
# depends:                                 # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
#   - minilibc: v7.4.0
#   - aos: v7.4.0

## 第四部分：编译连接信息
# build_config:                            # <可选项> 编译配置项
#   include:                               # <可选项> 编译时，影响编译器的-I 参数 ,全局有效
#     - src                                #        include 只能是该软件包下的目录，不能使用外部目录
#   internal_include:                      # <可选项> 编译时，影响编译器的-I 参数 ,组件内有效
#     - include
#   cflag: ''                              # <可选项> C 编译器所需要要的编译参数
#   cxxflag: ''                            # <可选项> CXX 编译器所需要要的编译参数
#   asmflag: ''                            # <可选项> 汇编器所需要要参数
#   define:                                # <可选项> 宏定义, 增加编译器的-D 选项,如：
#     XXX: 1                               #   -DXXX=1
#     AAA: 1                               #   -DAAA
#     STR: "abc"                           #   -DSTR="abc"
#   libs:                                  # 该组件中支持的二进制静态库,如：libxxx.a, libyyy.a
#     - xxx                                #   -lxxx
#     - yyy                                #   -lyyy
#   libpath:                               # 指定静态库所在的路径（相对于该组件路径）
#     - libs                               #   -Llibs
build_config:
  cflag: >
    -Wno-nonnull-compare -Wno-unused-function -Wno-unused-but-set-variable
  define:
    - ATEMPO_FREQ_REDUCE=1
  include:
    - include
  libpath:
    - libs/aef/<cpu>
    - libs/<cpu>
  libs:
    - xav_prebuild

# source_file:                             # <可选项> 指定参与编译的源代码文件，支持通配符，采用相对路径
#   - src/*.c                              # 例：组件 src 目录下所有的扩展名为 c 的源代码文件

## 第五部分：配置信息
# def_config:                              # 组件的可配置项
#   CONFIG_DEBUG: y
#   CONFIG_PARAM_NOT_CHECK: y
#   CONFIG_CLI: y
def_config:
  CONFIG_DEMUXER_OGG: 1
  CONFIG_MCAXER_LOCAL: 0
  CONFIG_STREAMER_FILE: 1
  CONFIG_DEMUXER_AMR: 1
  CONFIG_AV_STREAM_INNER_BUF_SIZE: 2048
  CONFIG_DECODER_ALAW: 1
  CONFIG_DECODER_AMRNB: 1
  CONFIG_STREAMER_FIFO: 1
  CONFIG_DECODER_AMRWB: 1
  CONFIG_DECODER_PCM: 1
  CONFIG_ATEMPOER_IPC: 0
  CONFIG_AV_AO_ALSA: 1
  CONFIG_AV_AO_DUMMY: 0
  CONFIG_AV_AO_ALSA_STANDARD: 0
  TMALL_PATCH: 0
  XIAOYA_PATCH: 1
  CONFIG_AV_AEF_DEBUG: 0
  CONFIG_AV_AO_CHANNEL_NUM: 1
  CONFIG_DECODER_OPUS: 1
  CONFIG_DECODER_VORBIS: 1
  CONFIG_AV_ERRNO_DEBUG: 0
  CONFIG_AEFXER_IPC: 0
  CONFIG_AVPARSER_MP3: 1
  CONFIG_DECODER_AAC : 1
  CONFIG_DEMUXER_MP4: 1
  CONFIG_DEMUXER_ASF: 1
  CONFIG_AO_DIFF_SUPPORT: 0
  CONFIG_DECODER_MULAW: 1
  CONFIG_EQXER_IPC: 0
  CONFIG_AEFXER_SONA: 1
  CONFIG_STREAMER_HLS: 1
  CONFIG_DEMUXER_WAV: 1
  CONFIG_STREAMER_HTTP: 1
  CONFIG_DECODER_PVMP3: 1
  CONFIG_FFTXER_IPC: 0
  CONFIG_AVPARSER_ADTS: 1
  CONFIG_MCAXER_IPC: 0
  CONFIG_ATEMPOER_SONIC: 1
  CONFIG_RESAMPLER_SPEEX: 1
  CONFIG_DECODER_SPEEX: 1
  CONFIG_STREAMER_CRYPTO: 1
  CONFIG_DECODER_ADPCM_MS: 1
  CONFIG_DEMUXER_RAWAUDIO: 1
  CONFIG_AV_MP4_IDX_OPT: 1
  CONFIG_RESAMPLER_IPC: 0
  CONFIG_DECODER_IPC: 0
  CONFIG_DEMUXER_MP3: 1
  CONFIG_DEMUXER_TS: 1
  CONFIG_DEMUXER_ADTS: 1
  CONFIG_EQXER_SILAN: 0
  CONFIG_DECODER_FLAC: 1
  CONFIG_AO_MIXER_SUPPORT: 1
  CONFIG_STREAMER_MEM: 1
  CONFIG_FFTXER_SPEEX: 0
  CONFIG_DEMUXER_FLAC: 1
  CONFIG_PLAYER_YOC: 1
  CONFIG_PLAYER_TPLAYER: 0
  CONFIG_AV_AUDIO_ONLY_SUPPORT: 0
  CONFIG_AV_DBUS_SUPPORT: 0

## 第六部分：安装信息
# install:
#   - dest: include/                       # 安装的目的路径 dest是相对路径，通常是相对于YoC SDK 安装目录
#     source:                              # 安装源列表
#      - src/*.h                           # 支持通配符，相对路径
install:
  - dest: "include/avutil"
    source:
      - "include/avutil/*.h"
  - dest: "include/avcodec"
    source:
      - "include/avcodec/*.h"
  - dest: "include/avformat"
    source:
      - "include/avformat/*.h"
  - dest: "include/output"
    source:
      - "include/output/*.h"
  - dest: "include/stream"
    source:
      - "include/stream/*.h"
  - dest: "include/swresample"
    source:
      - "include/swresample/*.h"
  - dest: "include/avfilter"
    source:
      - "include/avfilter/*.h"
  - dest: "include/aef"
    source:
      - "include/aef/*.h"
  - dest: "include/atempo"
    source:
      - "include/atempo/*.h"
  - dest: "include/mca"
    source:
      - "include/mca/*.h"
  - dest: "include/icore"
    source:
      - "include/icore/*.h"
  - dest: "include"
    source:
      - "include/*.h"
  - dest: "lib"
    source:
      - "libs/aef/<cpu>/libSonaAef_mca.a"
  - dest: "lib"
    source:
      - "libs/<cpu>/*.a"

## 第七部分：导出部分
# export:
#   - dest: "<SOLUTION_PATH>/generated/data" # 安装的目的路径 dest是相对路径
#     source:                                # 安装源列表
#       - "bootimgs/boot"
#       - "bootimgs/tee"
#       - "bootimgs/mtb"
#       - "configs/config.yaml"
