SDK_DEMO_PATH ?= .
BL_SDK_BASE ?= $(abspath  $(SDK_DEMO_PATH)/../../../..)

export BL_SDK_BASE

CHIP ?= bl616
BOARD ?= bl616dk
CROSS_COMPILE ?= riscv64-unknown-elf-


include $(BL_SDK_BASE)/project.build
