#!/usr/bin/expect
# =========== user config start ===============
set timeout 10
set tty /dev/ttyACM1
# =========== user config end ===============

spawn -open [open $tty "r+"]
if {$argc < 1} {puts "Usage: $argv0 <ssid> \[password\]"; exit}
set ssid [lindex $argv 0]
set password [expr {$argc >= 2 ? [lindex $argv 1] : ""}]
set serial_id $spawn_id
# set mode, disable dhcp
send -i $serial_id "AT\r\n"
send -i $serial_id "AT+CWMODE=1\r\n"
expect -i $serial_id "OK"
send -i $serial_id "AT+CWDHCP=0,1\r\n"
expect -i $serial_id "OK"
# connect
send -i $serial_id "AT+CWJAP=\"$ssid\",\"$password\"\r\n"
expect {
    -i $serial_id "+CW:CONNECTED" {
    }
    -i $serial_id timeout {
        puts "✗ 超时，未按照预期收到响应"
    }
}
close -i $serial_id
