#include "stdint.h"
#include "bflb_lhal_romdriver.h"

#include "bflb_common.h"
#include "bflb_dma.h"
#include "bflb_ef_ctrl.h"
#include "bflb_gpio.h"
#include "bflb_irq.h"
#include "bflb_l1c.h"
#include "bflb_mtimer.h"
#include "bflb_rtc.h"
#include "bflb_uart.h"
#include "bflb_wdg.h"
#include "bflb_sf_cfg.h"
#include "bflb_xip_sflash.h"
#include "bflb_sflash.h"
#include "bflb_sf_ctrl.h"
#include "bflb_flash_secreg.h"



uint32_t const bflb_lhal_romapi_table[]={
    0x0616A002,
    0x00000000,
    0x00000000,
    0x00000000,

    [BFLB_LHAL_ROMAPI_INDEX_arch_strcmp]                                       = (uint32_t)arch_strcmp,
    [BFLB_LHAL_ROMAPI_INDEX_arch_memcpy]                                       = (uint32_t)arch_memcpy,
    [BFLB_LHAL_ROMAPI_INDEX_arch_memcpy4]                                      = (uint32_t)arch_memcpy4,
    [BFLB_LHAL_ROMAPI_INDEX_arch_memcpy_fast]                                  = (uint32_t)arch_memcpy_fast,
    [BFLB_LHAL_ROMAPI_INDEX_arch_memset]                                       = (uint32_t)arch_memset,
    [BFLB_LHAL_ROMAPI_INDEX_arch_memset4]                                      = (uint32_t)arch_memset4,
    [BFLB_LHAL_ROMAPI_INDEX_arch_memcmp]                                       = (uint32_t)arch_memcmp,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_check_cache_addr_aligned]                     = (uint32_t)bflb_check_cache_addr_aligned,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_soft_crc16]                                   = (uint32_t)bflb_soft_crc16,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_soft_crc32_ex]                                = (uint32_t)bflb_soft_crc32_ex,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_soft_crc32]                                   = (uint32_t)bflb_soft_crc32,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_get_app_version_from_efuse]                   = (uint32_t)bflb_get_app_version_from_efuse,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_set_app_version_to_efuse]                     = (uint32_t)bflb_set_app_version_to_efuse,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_get_boot2_version_from_efuse]                 = (uint32_t)bflb_get_boot2_version_from_efuse,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_set_boot2_version_to_efuse]                   = (uint32_t)bflb_set_boot2_version_to_efuse,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_dma_channel_init]                             = (uint32_t)bflb_dma_channel_init,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_dma_channel_deinit]                           = (uint32_t)bflb_dma_channel_deinit,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_dma_channel_lli_reload]                       = (uint32_t)bflb_dma_channel_lli_reload,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_dma_channel_lli_link_head]                    = (uint32_t)bflb_dma_channel_lli_link_head,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_dma_channel_start]                            = (uint32_t)bflb_dma_channel_start,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_dma_channel_stop]                             = (uint32_t)bflb_dma_channel_stop,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_dma_channel_isbusy]                           = (uint32_t)bflb_dma_channel_isbusy,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_dma_channel_tcint_mask]                       = (uint32_t)bflb_dma_channel_tcint_mask,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_dma_channel_get_tcint_status]                 = (uint32_t)bflb_dma_channel_get_tcint_status,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_dma_channel_tcint_clear]                      = (uint32_t)bflb_dma_channel_tcint_clear,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_rx_cycle_dma_process]                         = (uint32_t)bflb_rx_cycle_dma_process,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_dma_feature_control]                          = (uint32_t)bflb_dma_feature_control,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_ef_ctrl_busy]                                 = (uint32_t)bflb_ef_ctrl_busy,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_ef_ctrl_autoload_done]                        = (uint32_t)bflb_ef_ctrl_autoload_done,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_ef_ctrl_set_para]                             = (uint32_t)bflb_ef_ctrl_set_para,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_ef_ctrl_write_direct]                         = (uint32_t)bflb_ef_ctrl_write_direct,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_ef_ctrl_read_direct]                          = (uint32_t)bflb_ef_ctrl_read_direct,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_ef_ctrl_read_common_trim]                     = (uint32_t)bflb_ef_ctrl_read_common_trim,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_ef_ctrl_write_common_trim]                    = (uint32_t)bflb_ef_ctrl_write_common_trim,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_ef_ctrl_is_all_bits_zero]                     = (uint32_t)bflb_ef_ctrl_is_all_bits_zero,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_ef_ctrl_get_byte_zero_cnt]                    = (uint32_t)bflb_ef_ctrl_get_byte_zero_cnt,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_ef_ctrl_get_trim_parity]                      = (uint32_t)bflb_ef_ctrl_get_trim_parity,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_gpio_init]                                    = (uint32_t)bflb_gpio_init,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_gpio_deinit]                                  = (uint32_t)bflb_gpio_deinit,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_gpio_output_value_mode_enable]                = (uint32_t)bflb_gpio_output_value_mode_enable,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_gpio_pin0_31_output]                          = (uint32_t)bflb_gpio_pin0_31_output,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_gpio_pin32_63_output]                         = (uint32_t)bflb_gpio_pin32_63_output,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_gpio_set]                                     = (uint32_t)bflb_gpio_set,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_gpio_pin0_31_set]                             = (uint32_t)bflb_gpio_pin0_31_set,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_gpio_pin32_63_set]                            = (uint32_t)bflb_gpio_pin32_63_set,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_gpio_reset]                                   = (uint32_t)bflb_gpio_reset,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_gpio_pin0_31_reset]                           = (uint32_t)bflb_gpio_pin0_31_reset,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_gpio_pin32_63_reset]                          = (uint32_t)bflb_gpio_pin32_63_reset,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_gpio_read]                                    = (uint32_t)bflb_gpio_read,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_gpio_pin0_31_read]                            = (uint32_t)bflb_gpio_pin0_31_read,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_gpio_pin32_63_read]                           = (uint32_t)bflb_gpio_pin32_63_read,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_gpio_int_init]                                = (uint32_t)bflb_gpio_int_init,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_gpio_int_mask]                                = (uint32_t)bflb_gpio_int_mask,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_gpio_get_intstatus]                           = (uint32_t)bflb_gpio_get_intstatus,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_gpio_get_intstatus_pin0_31]                   = (uint32_t)bflb_gpio_get_intstatus_pin0_31,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_gpio_get_intstatus_pin32_63]                  = (uint32_t)bflb_gpio_get_intstatus_pin32_63,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_gpio_int_clear]                               = (uint32_t)bflb_gpio_int_clear,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_gpio_int_clear_pin0_31]                       = (uint32_t)bflb_gpio_int_clear_pin0_31,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_gpio_int_clear_pin32_63]                      = (uint32_t)bflb_gpio_int_clear_pin32_63,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_gpio_uart_init]                               = (uint32_t)bflb_gpio_uart_init,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_gpio_feature_control]                         = (uint32_t)bflb_gpio_feature_control,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_irq_restore]                                  = (uint32_t)bflb_irq_restore,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_irq_enable]                                   = (uint32_t)bflb_irq_enable,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_irq_disable]                                  = (uint32_t)bflb_irq_disable,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_irq_set_pending]                              = (uint32_t)bflb_irq_set_pending,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_irq_clear_pending]                            = (uint32_t)bflb_irq_clear_pending,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_irq_set_nlbits]                               = (uint32_t)bflb_irq_set_nlbits,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_irq_set_priority]                             = (uint32_t)bflb_irq_set_priority,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_l1c_icache_enable]                            = (uint32_t)bflb_l1c_icache_enable,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_l1c_icache_disable]                           = (uint32_t)bflb_l1c_icache_disable,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_l1c_icache_invalid_all]                       = (uint32_t)bflb_l1c_icache_invalid_all,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_l1c_icache_invalid_range]                     = (uint32_t)bflb_l1c_icache_invalid_range,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_l1c_dcache_enable]                            = (uint32_t)bflb_l1c_dcache_enable,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_l1c_dcache_disable]                           = (uint32_t)bflb_l1c_dcache_disable,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_l1c_dcache_clean_all]                         = (uint32_t)bflb_l1c_dcache_clean_all,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_l1c_dcache_invalidate_all]                    = (uint32_t)bflb_l1c_dcache_invalidate_all,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_l1c_dcache_clean_invalidate_all]              = (uint32_t)bflb_l1c_dcache_clean_invalidate_all,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_l1c_dcache_clean_range]                       = (uint32_t)bflb_l1c_dcache_clean_range,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_l1c_dcache_invalidate_range]                  = (uint32_t)bflb_l1c_dcache_invalidate_range,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_l1c_dcache_clean_invalidate_range]            = (uint32_t)bflb_l1c_dcache_clean_invalidate_range,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_mtimer_delay_us]                              = (uint32_t)bflb_mtimer_delay_us,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_mtimer_delay_ms]                              = (uint32_t)bflb_mtimer_delay_ms,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_rtc_disable]                                  = (uint32_t)bflb_rtc_disable,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_rtc_set_time]                                 = (uint32_t)bflb_rtc_set_time,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_uart_init]                                    = (uint32_t)bflb_uart_init,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_uart_deinit]                                  = (uint32_t)bflb_uart_deinit,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_uart_enable]                                  = (uint32_t)bflb_uart_enable,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_uart_disable]                                 = (uint32_t)bflb_uart_disable,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_uart_link_txdma]                              = (uint32_t)bflb_uart_link_txdma,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_uart_link_rxdma]                              = (uint32_t)bflb_uart_link_rxdma,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_uart_putchar]                                 = (uint32_t)bflb_uart_putchar,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_uart_getchar]                                 = (uint32_t)bflb_uart_getchar,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_uart_put]                                     = (uint32_t)bflb_uart_put,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_uart_put_block]                               = (uint32_t)bflb_uart_put_block,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_uart_get]                                     = (uint32_t)bflb_uart_get,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_uart_wait_tx_done]                            = (uint32_t)bflb_uart_wait_tx_done,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_uart_txready]                                 = (uint32_t)bflb_uart_txready,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_uart_txempty]                                 = (uint32_t)bflb_uart_txempty,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_uart_rxavailable]                             = (uint32_t)bflb_uart_rxavailable,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_uart_txint_mask]                              = (uint32_t)bflb_uart_txint_mask,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_uart_rxint_mask]                              = (uint32_t)bflb_uart_rxint_mask,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_uart_errint_mask]                             = (uint32_t)bflb_uart_errint_mask,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_uart_get_intstatus]                           = (uint32_t)bflb_uart_get_intstatus,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_uart_int_clear]                               = (uint32_t)bflb_uart_int_clear,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_uart_feature_control]                         = (uint32_t)bflb_uart_feature_control,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_wdg_init]                                     = (uint32_t)bflb_wdg_init,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_wdg_start]                                    = (uint32_t)bflb_wdg_start,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_wdg_stop]                                     = (uint32_t)bflb_wdg_stop,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_wdg_get_countervalue]                         = (uint32_t)bflb_wdg_get_countervalue,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_wdg_set_countervalue]                         = (uint32_t)bflb_wdg_set_countervalue,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_wdg_reset_countervalue]                       = (uint32_t)bflb_wdg_reset_countervalue,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_wdg_compint_clear]                            = (uint32_t)bflb_wdg_compint_clear,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_flash_secreg_callapi_before]                  = (uint32_t)bflb_flash_secreg_callapi_before,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_flash_secreg_callapi_after]                   = (uint32_t)bflb_flash_secreg_callapi_after,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_flash_secreg_get_param]                       = (uint32_t)bflb_flash_secreg_get_param,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_flash_secreg_region_foreach]                  = (uint32_t)bflb_flash_secreg_region_foreach,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_flash_secreg_get_lockbits]                    = (uint32_t)bflb_flash_secreg_get_lockbits,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_flash_secreg_set_lockbits]                    = (uint32_t)bflb_flash_secreg_set_lockbits,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_flash_secreg_get_locked]                      = (uint32_t)bflb_flash_secreg_get_locked,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_flash_secreg_set_locked]                      = (uint32_t)bflb_flash_secreg_set_locked,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_flash_secreg_get_info_by_idx]                 = (uint32_t)bflb_flash_secreg_get_info_by_idx,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_flash_secreg_valid_by_idx]                    = (uint32_t)bflb_flash_secreg_valid_by_idx,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_flash_secreg_read_by_idx]                     = (uint32_t)bflb_flash_secreg_read_by_idx,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_flash_secreg_write_by_idx]                    = (uint32_t)bflb_flash_secreg_write_by_idx,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_flash_secreg_erase_by_idx]                    = (uint32_t)bflb_flash_secreg_erase_by_idx,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_flash_secreg_get_info]                        = (uint32_t)bflb_flash_secreg_get_info,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_flash_secreg_valid]                           = (uint32_t)bflb_flash_secreg_valid,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_flash_secreg_read]                            = (uint32_t)bflb_flash_secreg_read,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_flash_secreg_write]                           = (uint32_t)bflb_flash_secreg_write,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_flash_secreg_erase]                           = (uint32_t)bflb_flash_secreg_erase,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_cfg_init_ext_flash_gpio]                   = (uint32_t)bflb_sf_cfg_init_ext_flash_gpio,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_cfg_deinit_ext_flash_gpio]                 = (uint32_t)bflb_sf_cfg_deinit_ext_flash_gpio,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_cfg_init_flash_gpio]                       = (uint32_t)bflb_sf_cfg_init_flash_gpio,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_cfg_init_flash2_gpio]                      = (uint32_t)bflb_sf_cfg_init_flash2_gpio,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_cfg_flash_identify]                        = (uint32_t)bflb_sf_cfg_flash_identify,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_cfg_get_flash_cfg_need_lock]               = (uint32_t)bflb_sf_cfg_get_flash_cfg_need_lock,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_cfg_flash_init]                            = (uint32_t)bflb_sf_cfg_flash_init,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_cfg_sbus2_flash_init]                      = (uint32_t)bflb_sf_cfg_sbus2_flash_init,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_enable]                               = (uint32_t)bflb_sf_ctrl_enable,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_set_io_delay]                         = (uint32_t)bflb_sf_ctrl_set_io_delay,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_get_io_delay]                         = (uint32_t)bflb_sf_ctrl_get_io_delay,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_set_cs_clk_delay]                     = (uint32_t)bflb_sf_ctrl_set_cs_clk_delay,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_get_cs_clk_delay]                     = (uint32_t)bflb_sf_ctrl_get_cs_clk_delay,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_set_flash_io_cs_clk_delay]            = (uint32_t)bflb_sf_ctrl_set_flash_io_cs_clk_delay,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_get_flash_io_cs_clk_delay]            = (uint32_t)bflb_sf_ctrl_get_flash_io_cs_clk_delay,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_set_dqs_delay]                        = (uint32_t)bflb_sf_ctrl_set_dqs_delay,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_bank2_enable]                         = (uint32_t)bflb_sf_ctrl_bank2_enable,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_sbus2_hold_sram]                      = (uint32_t)bflb_sf_ctrl_sbus2_hold_sram,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_sbus2_release_sram]                   = (uint32_t)bflb_sf_ctrl_sbus2_release_sram,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_sbus2_replace]                        = (uint32_t)bflb_sf_ctrl_sbus2_replace,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_sbus2_revoke_replace]                 = (uint32_t)bflb_sf_ctrl_sbus2_revoke_replace,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_sbus2_set_delay]                      = (uint32_t)bflb_sf_ctrl_sbus2_set_delay,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_remap_set]                            = (uint32_t)bflb_sf_ctrl_remap_set,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_32bits_addr_en]                       = (uint32_t)bflb_sf_ctrl_32bits_addr_en,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_get_clock_delay]                      = (uint32_t)bflb_sf_ctrl_get_clock_delay,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_set_clock_delay]                      = (uint32_t)bflb_sf_ctrl_set_clock_delay,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_get_wrap_queue_value]                 = (uint32_t)bflb_sf_ctrl_get_wrap_queue_value,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_cmds_set]                             = (uint32_t)bflb_sf_ctrl_cmds_set,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_select_pad]                           = (uint32_t)bflb_sf_ctrl_select_pad,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_sbus_select_bank]                     = (uint32_t)bflb_sf_ctrl_sbus_select_bank,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_set_owner]                            = (uint32_t)bflb_sf_ctrl_set_owner,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_get_owner]                            = (uint32_t)bflb_sf_ctrl_get_owner,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_set_owner_flag]                       = (uint32_t)bflb_sf_ctrl_set_owner_flag,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_get_owner_flag]                       = (uint32_t)bflb_sf_ctrl_get_owner_flag,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_disable]                              = (uint32_t)bflb_sf_ctrl_disable,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_aes_enable_be]                        = (uint32_t)bflb_sf_ctrl_aes_enable_be,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_aes_enable_le]                        = (uint32_t)bflb_sf_ctrl_aes_enable_le,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_aes_set_region]                       = (uint32_t)bflb_sf_ctrl_aes_set_region,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_aes_set_key]                          = (uint32_t)bflb_sf_ctrl_aes_set_key,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_aes_set_key_be]                       = (uint32_t)bflb_sf_ctrl_aes_set_key_be,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_aes_set_iv]                           = (uint32_t)bflb_sf_ctrl_aes_set_iv,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_aes_set_iv_be]                        = (uint32_t)bflb_sf_ctrl_aes_set_iv_be,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_aes_set_region_offset]                = (uint32_t)bflb_sf_ctrl_aes_set_region_offset,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_aes_xts_set_key]                      = (uint32_t)bflb_sf_ctrl_aes_xts_set_key,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_aes_xts_set_key_be]                   = (uint32_t)bflb_sf_ctrl_aes_xts_set_key_be,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_aes_xts_set_iv]                       = (uint32_t)bflb_sf_ctrl_aes_xts_set_iv,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_aes_xts_set_iv_be]                    = (uint32_t)bflb_sf_ctrl_aes_xts_set_iv_be,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_aes_set_mode]                         = (uint32_t)bflb_sf_ctrl_aes_set_mode,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_aes_enable]                           = (uint32_t)bflb_sf_ctrl_aes_enable,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_aes_disable]                          = (uint32_t)bflb_sf_ctrl_aes_disable,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_is_aes_enable]                        = (uint32_t)bflb_sf_ctrl_is_aes_enable,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_set_flash_image_offset]               = (uint32_t)bflb_sf_ctrl_set_flash_image_offset,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_get_flash_image_offset]               = (uint32_t)bflb_sf_ctrl_get_flash_image_offset,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_lock_flash_image_offset]              = (uint32_t)bflb_sf_ctrl_lock_flash_image_offset,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_select_clock]                         = (uint32_t)bflb_sf_ctrl_select_clock,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_sendcmd]                              = (uint32_t)bflb_sf_ctrl_sendcmd,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_disable_wrap_access]                  = (uint32_t)bflb_sf_ctrl_disable_wrap_access,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_xip_set]                              = (uint32_t)bflb_sf_ctrl_xip_set,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_get_busy_state]                       = (uint32_t)bflb_sf_ctrl_get_busy_state,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_aes_get_iv_be]                        = (uint32_t)bflb_sf_ctrl_aes_get_iv_be,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_aes_get_iv_le]                        = (uint32_t)bflb_sf_ctrl_aes_get_iv_le,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_aes_set_decrypt_region_be]            = (uint32_t)bflb_sf_ctrl_aes_set_decrypt_region_be,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sf_ctrl_aes_set_decrypt_region_le]            = (uint32_t)bflb_sf_ctrl_aes_set_decrypt_region_le,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_init]                                  = (uint32_t)bflb_sflash_init,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_set_spi_mode]                          = (uint32_t)bflb_sflash_set_spi_mode,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_read_reg]                              = (uint32_t)bflb_sflash_read_reg,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_write_reg]                             = (uint32_t)bflb_sflash_write_reg,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_read_reg_with_cmd]                     = (uint32_t)bflb_sflash_read_reg_with_cmd,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_write_reg_with_cmd]                    = (uint32_t)bflb_sflash_write_reg_with_cmd,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_busy]                                  = (uint32_t)bflb_sflash_busy,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_write_enable]                          = (uint32_t)bflb_sflash_write_enable,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_qspi_enable]                           = (uint32_t)bflb_sflash_qspi_enable,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_qspi_disable]                          = (uint32_t)bflb_sflash_qspi_disable,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_volatile_reg_write_enable]             = (uint32_t)bflb_sflash_volatile_reg_write_enable,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_chip_erase]                            = (uint32_t)bflb_sflash_chip_erase,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_sector_erase]                          = (uint32_t)bflb_sflash_sector_erase,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_blk32_erase]                           = (uint32_t)bflb_sflash_blk32_erase,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_blk64_erase]                           = (uint32_t)bflb_sflash_blk64_erase,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_erase]                                 = (uint32_t)bflb_sflash_erase,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_get_uniqueid]                          = (uint32_t)bflb_sflash_get_uniqueid,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_get_jedecid]                           = (uint32_t)bflb_sflash_get_jedecid,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_get_deviceid]                          = (uint32_t)bflb_sflash_get_deviceid,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_powerdown]                             = (uint32_t)bflb_sflash_powerdown,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_release_powerdown]                     = (uint32_t)bflb_sflash_release_powerdown,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_restore_from_powerdown]                = (uint32_t)bflb_sflash_restore_from_powerdown,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_set_burst_wrap]                        = (uint32_t)bflb_sflash_set_burst_wrap,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_disable_burst_wrap]                    = (uint32_t)bflb_sflash_disable_burst_wrap,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_set_32bits_addr_mode]                  = (uint32_t)bflb_sflash_set_32bits_addr_mode,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_software_reset]                        = (uint32_t)bflb_sflash_software_reset,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_reset_continue_read]                   = (uint32_t)bflb_sflash_reset_continue_read,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_set_xip_cfg]                           = (uint32_t)bflb_sflash_set_xip_cfg,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_xip_read_enable]                       = (uint32_t)bflb_sflash_xip_read_enable,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_xip_read_disable]                      = (uint32_t)bflb_sflash_xip_read_disable,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_rcv_enable]                            = (uint32_t)bflb_sflash_rcv_enable,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_erase_security_register]               = (uint32_t)bflb_sflash_erase_security_register,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_program_security_register]             = (uint32_t)bflb_sflash_program_security_register,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_read_security_register]                = (uint32_t)bflb_sflash_read_security_register,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_clear_status_register]                 = (uint32_t)bflb_sflash_clear_status_register,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_read]                                  = (uint32_t)bflb_sflash_read,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_sflash_program]                               = (uint32_t)bflb_sflash_program,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_xip_sflash_state_save]                        = (uint32_t)bflb_xip_sflash_state_save,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_xip_sflash_state_restore]                     = (uint32_t)bflb_xip_sflash_state_restore,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_xip_sflash_erase_need_lock]                   = (uint32_t)bflb_xip_sflash_erase_need_lock,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_xip_sflash_write_need_lock]                   = (uint32_t)bflb_xip_sflash_write_need_lock,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_xip_sflash_read_need_lock]                    = (uint32_t)bflb_xip_sflash_read_need_lock,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_xip_sflash_get_jedecid_need_lock]             = (uint32_t)bflb_xip_sflash_get_jedecid_need_lock,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_xip_sflash_get_deviceid_need_lock]            = (uint32_t)bflb_xip_sflash_get_deviceid_need_lock,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_xip_sflash_get_uniqueid_need_lock]            = (uint32_t)bflb_xip_sflash_get_uniqueid_need_lock,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_xip_sflash_clear_status_register_need_lock]   = (uint32_t)bflb_xip_sflash_clear_status_register_need_lock,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_xip_sflash_read_via_cache_need_lock]          = (uint32_t)bflb_xip_sflash_read_via_cache_need_lock,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_xip_sflash_opt_enter]                         = (uint32_t)bflb_xip_sflash_opt_enter,
    [BFLB_LHAL_ROMAPI_INDEX_bflb_xip_sflash_opt_exit]                          = (uint32_t)bflb_xip_sflash_opt_exit,

    [BFLB_LHAL_ROMAPI_INDEX_FUNC_EMPTY_START ... BFLB_LHAL_ROMAPI_INDEX_FUNC_EMPTY_END] = 0xdeedbeef,
};
