target remote :1025
set mem inaccessible-by-default off
set architecture riscv:rv32
set remotetimeout 250
#set disassemble-next-line on
#mon gdb_breakpoint_override [hard|soft|disable]

#mon reset

set $pc=0xA0000000
set $mie=0
set $mstatus=0x1880

thb main

mem 0x22FC0000 0x23010000 rw
mem 0x62FC0000 0x63010000 rw
#rom
mem 0x90000000 0x90020000 ro
#psram
mem 0xA8000000 0xA8800000 rw
#flash
mem 0xA0000000 0xA0400000 ro
