#!/bin/bash

killall DebugServerConsole.elf
DebugServerConsole &

cd ..
# 获取当前文件夹的名字
current_folder=$(basename "$PWD")

current_dir=$PWD
riscv64-unknown-elf-gdb $current_dir/build/build_out/${current_folder}_bl616.elf -x ./gdb/gdbinit

