SDK_DEMO_PATH ?= $(abspath .)
BL_SDK_BASE = $(SDK_DEMO_PATH)/../../..

export BL_SDK_BASE

CHIP ?= bl808
BOARD ?= bl808dk
CPU_ID ?= d0
CROSS_COMPILE ?= riscv64-unknown-elf-


include $(BL_SDK_BASE)/project.build
