#ifndef BLCRYPTO_SUITE_TOP_CONFIG_H_YJ9KRAA4
#define BLCRYPTO_SUITE_TOP_CONFIG_H_YJ9KRAA4

//XXX TODO remove bl606p/bl808
#define USE_HWCRYPTO 1

#endif /* end of include guard: BLCRYPTO_SUITE_TOP_CONFIG_H_YJ9KRAA4 */
