SDK_DEMO_PATH ?= $(abspath .)
BL_SDK_BASE ?= $(abspath  ./../../../../..)

export BL_SDK_BASE

CPU_ID ?= ap
BOARD ?= bl618dgdk
CROSS_COMPILE ?= riscv64-unknown-elf-


include $(BL_SDK_BASE)/project.build
