[cfg]
# 0: no erase, 1: programmed section erase, 2: chip erase
erase = 1
# skip mode: skip address and length
skip_mode = 0x0, 0x0
# 0: not use ISP mode, 1: ISP mode
boot2_isp_mode = 0

[FW]
filedir = ./build/build_out/pm_demo*_$(CHIPNAME)*.bin
address = 0x000000
