#ifndef FLASHLOADER_PORT_CONFIG_H
#define FLASHLOADER_PORT_CONFIG_H

/* Fixed non-cacheable aliases in the last 32 KiB of BL618DG B0 AP RAM. */
#define FLASHLOADER_RESERVED_RAM_START 0x21068000UL
#define FLASHLOADER_RESERVED_RAM_END   0x21070000UL
#define FLASHLOADER_DESCRIPTOR_ADDR    0x2106AFE0UL
#define FLASHLOADER_MAILBOX_ADDR       0x2106AFF0UL
#define FLASHLOADER_DATA_ADDR          0x2106B000UL
#define FLASHLOADER_SHARED_SIZE        (20U * 1024U)
#define FLASHLOADER_REQUEST_BUFFER_SIZE FLASHLOADER_SHARED_SIZE
#define FLASHLOADER_RESPONSE_BUFFER_SIZE FLASHLOADER_SHARED_SIZE
#define FLASHLOADER_SHA_CHUNK_SIZE     4096U
#define FLASHLOADER_XZ_OUTPUT_SIZE     4096U
#define FLASHLOADER_XZ_HEAP_SIZE       (80U * 1024U)
#define FLASHLOADER_CAPABILITIES       \
    (FLASHLOADER_CAP_FLASH | FLASHLOADER_CAP_FLASH_PARAMETER | \
     FLASHLOADER_CAP_FLASH_XZ | FLASHLOADER_CAP_FLASH_OTP | \
     FLASHLOADER_CAP_EFUSE | FLASHLOADER_CAP_RESET | \
     FLASHLOADER_CAP_FLASH_XIP | FLASHLOADER_CAP_HOST_ACK)

#endif
