#define PIKA_LWIP_ENABLE 1
#define PIKA_FREERTOS_ENABLE 1
#define PIKA_THREAD_STACK_SIZE 4096
#define PIKA_SHELL_SAVE_APP_ENABLE 1
#define PIKA_STACK_BUFF_SIZE 512
#define PIKA_OPTIMIZE PIKA_OPTIMIZE_SPEED
#define PIKA_ASSERT_ENABLE 1
#define PIKA_GC_MARK_SWEEP_ENABLE 1
#define PIKA_KERNAL_DEBUG_ENABLE 1
// #define PIKA_DEBUG_ENABLE 1
