#ifndef _POWER_CONFIG_H
#define _POWER_CONFIG_H


#define DEAULT_LP_XTAL_TYPE                 GLB_DLL_XTAL_32M
#define DEFAULT_LP_LDO_LEVEL                PDS_LDO_LEVEL_1P10V
#define DEFAULT_LP_PDS_AON_GPIO_WAKE_UP_SRC    PDS_AON_WAKEUP_GPIO_NONE
#define DEFAULT_LP_PDS_AON_GPIO_TRIG_TYPE      PDS_AON_GPIO_INT_TRIGGER_SYNC_FALLING_EDGE

#define DEFAULT_LP_PDS_FLASH_POWER_DOWN        1
#define DEFAULT_LP_PDS_HOLD_GPIO               0
#define DEFAULT_LP_PDS_TURN_OFF_FLASH_PAD      1
#define DEFAULT_LP_PDS_TURN_OFF_XTAL_32M       1
#define DEFAULT_LP_PDS_TURN_OFF_DLL            1
#define DEFAULT_LP_PDS_TURN_OFF_RF             1
#define DEFAULT_LP_PDS_USE_XTAL_32K            0
#endif