#ifndef _USB_CONFIG_H
#define _USB_CONFIG_H

//#define USE_EXTERNAL_TRANSCEIVER
#define USE_INTERNAL_TRANSCEIVER
#define ENABLE_LPM_INT
//#define ENABLE_SOF3MS_INT
//#define ENABLE_ERROR_INT

#endif
