// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_LabelMarquee = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Slider2 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Image8 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x4B4444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image1, &ui_img_fastforward_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 210);
    lv_obj_set_y(ui_Image1, 415);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_Image1, 900);
    lv_image_set_scale(ui_Image1, 128);

    ui_Image3 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image3, &ui_img_fastforward_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, 210);
    lv_obj_set_y(ui_Image3, -415);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_Image3, 2700);
    lv_image_set_scale(ui_Image3, 128);

    ui_Image2 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image2, &ui_img_play_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, 217);
    lv_obj_set_y(ui_Image2, -453);
    lv_obj_set_align(ui_Image2, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_Image2, 2700);
    lv_image_set_scale(ui_Image2, 100);

    /* Marquee: replaces the former tall vertical slider. The whole UI is drawn on
     * a portrait framebuffer but viewed in landscape, so every widget is rotated
     * 2700 (=270 deg, same as the icons). This label is rotated the same way, so
     * in landscape it reads as a horizontal banner scrolling along the top. Its
     * "width" is the visible scroll length = the old slider's length (880); height
     * is one text line. Circular scroll is driven by LVGL; anim_duration sets the
     * speed (larger = slower). Pivot at the label's own origin so the rotation
     * matches the icons' transform. */
    ui_LabelMarquee = lv_label_create(ui_Screen1);
    lv_label_set_long_mode(ui_LabelMarquee, LV_LABEL_LONG_MODE_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabelMarquee,
                      "Bouffalo Lab (Nanjing) Co., Ltd. was established in Nanjing in 2016. "
                      "It is a company focusing on the research and development of world-leading "
                      "ultra-low power consumption, intelligent Internet of Things and edge "
                      "computing SoCs, as well as providing overall solutions for intelligent "
                      "cloud platforms. enterprise. At the same time, the company has complete "
                      "multi-mode wireless connection technology, audio and video processing and "
                      "artificial intelligence algorithm technology, which can fully realize the "
                      "chip research and development of single-chip integration.   ");
    lv_obj_set_width(ui_LabelMarquee, 880); /* visible scroll length = old slider length */
    lv_obj_set_height(ui_LabelMarquee, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_LabelMarquee, -210); /* +x in fb = "down" in the landscape view */
    lv_obj_set_y(ui_LabelMarquee, 0);
    lv_obj_set_align(ui_LabelMarquee, LV_ALIGN_CENTER);
    lv_obj_set_style_transform_rotation(ui_LabelMarquee, 2700, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_pivot_x(ui_LabelMarquee, lv_pct(50), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_pivot_y(ui_LabelMarquee, lv_pct(50), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_anim_duration(ui_LabelMarquee, 128000, LV_PART_MAIN | LV_STATE_DEFAULT); /* slow scroll */
    lv_obj_set_style_text_color(ui_LabelMarquee, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMarquee, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMarquee, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Image4 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image4, &ui_img_sound_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, -59);
    lv_obj_set_y(ui_Image4, 435);
    lv_obj_set_align(ui_Image4, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_Image4, 909);
    lv_image_set_scale(ui_Image4, 150);

    ui_Slider2 = lv_slider_create(ui_Screen1);
    lv_slider_set_range(ui_Slider2, -100, 0);
    lv_slider_set_value(ui_Slider2, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 290);
    lv_obj_set_height(ui_Slider2, 10);
    lv_obj_set_x(ui_Slider2, -30);
    lv_obj_set_y(ui_Slider2, 434);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider2, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider2,
                                                                                              lv_obj_get_style_pad_right(ui_Slider2, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 384);
    lv_obj_set_height(ui_Panel1, 768);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image5, &ui_img_wifi_png);
    lv_obj_set_width(ui_Image5, 50);
    lv_obj_set_height(ui_Image5, 50);
    lv_obj_set_x(ui_Image5, -117);
    lv_obj_set_y(ui_Image5, -433);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_Image5, 2700);
    lv_image_set_scale(ui_Image5, 200);

    ui_Image6 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image6, &ui_img_bluetooth_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image6, -34);
    lv_obj_set_y(ui_Image6, -435);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_Image6, 2700);

    ui_Image7 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image7, &ui_img_comment_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image7, 54);
    lv_obj_set_y(ui_Image7, -434);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_Image7, 2700);
    lv_image_set_scale(ui_Image7, 200);

    ui_Image8 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image8, &ui_img_speed_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image8, 134);
    lv_obj_set_y(ui_Image8, -434);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_Image8, 2700);
    lv_image_set_scale(ui_Image8, 400);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Image1 = NULL;
    ui_Image3 = NULL;
    ui_Image2 = NULL;
    ui_LabelMarquee = NULL;
    ui_Image4 = NULL;
    ui_Slider2 = NULL;
    ui_Panel1 = NULL;
    ui_Image5 = NULL;
    ui_Image6 = NULL;
    ui_Image7 = NULL;
    ui_Image8 = NULL;

}
