#define JS_ATOM_null 0
#define JS_ATOM_false 3
#define JS_ATOM_true 6
#define JS_ATOM_if 9
#define JS_ATOM_else 11
#define JS_ATOM_return 14
#define JS_ATOM_var 17
#define JS_ATOM_this 19
#define JS_ATOM_delete 22
#define JS_ATOM_void 25
#define JS_ATOM_typeof 28
#define JS_ATOM_new 31
#define JS_ATOM_in 33
#define JS_ATOM_instanceof 35
#define JS_ATOM_do 39
#define JS_ATOM_while 41
#define JS_ATOM_for 44
#define JS_ATOM_break 46
#define JS_ATOM_continue 49
#define JS_ATOM_switch 53
#define JS_ATOM_case 56
#define JS_ATOM_default 59
#define JS_ATOM_throw 62
#define JS_ATOM_try 65
#define JS_ATOM_catch 67
#define JS_ATOM_finally 70
#define JS_ATOM_function 73
#define JS_ATOM_debugger 77
#define JS_ATOM_with 81
#define JS_ATOM_class 84
#define JS_ATOM_const 87
#define JS_ATOM_enum 90
#define JS_ATOM_export 93
#define JS_ATOM_extends 96
#define JS_ATOM_import 99
#define JS_ATOM_super 102
#define JS_ATOM_implements 105
#define JS_ATOM_interface 109
#define JS_ATOM_let 113
#define JS_ATOM_package 115
#define JS_ATOM_private 118
#define JS_ATOM_protected 121
#define JS_ATOM_public 125
#define JS_ATOM_static 128
#define JS_ATOM_yield 131
#define JS_ATOM_empty 134
#define JS_ATOM_toString 136
#define JS_ATOM_valueOf 140
#define JS_ATOM_number 143
#define JS_ATOM_object 146
#define JS_ATOM_undefined 149
#define JS_ATOM_string 153
#define JS_ATOM_boolean 156
#define JS_ATOM__ret_ 159
#define JS_ATOM__eval_ 162
#define JS_ATOM_eval 165
#define JS_ATOM_arguments 168
#define JS_ATOM_value 172
#define JS_ATOM_get 175
#define JS_ATOM_set 177
#define JS_ATOM_prototype 179
#define JS_ATOM_constructor 183
#define JS_ATOM_length 187
#define JS_ATOM_target 190
#define JS_ATOM_of 193
#define JS_ATOM_NaN 195
#define JS_ATOM_Infinity 197
#define JS_ATOM__Infinity 201
#define JS_ATOM_name 205
#define JS_ATOM_Error 208
#define JS_ATOM___proto__ 211
#define JS_ATOM_index 215
#define JS_ATOM_input 218

#define JS_ATOM_END 221

