#ifndef NH_PROFILE_BUILTIN_H
#define NH_PROFILE_BUILTIN_H

#include "nh_filter.h"

#ifndef CONFIG_NETHUB_FILTER_LOCAL_PORT_MIN
#define CONFIG_NETHUB_FILTER_LOCAL_PORT_MIN 0
#endif

#ifndef CONFIG_NETHUB_FILTER_LOCAL_PORT_MAX
#define CONFIG_NETHUB_FILTER_LOCAL_PORT_MAX 0
#endif

#if ((CONFIG_NETHUB_FILTER_LOCAL_PORT_MIN != 0) || (CONFIG_NETHUB_FILTER_LOCAL_PORT_MAX != 0))
#define NH_PROFILE_BUILTIN_WIFI_RX_RULE_COUNT (6)
#else
#define NH_PROFILE_BUILTIN_WIFI_RX_RULE_COUNT (4)
#endif

#define NH_PROFILE_BUILTIN_WIFI_RX_DEFAULT_ACTION NH_FILTER_ACTION_HOST

extern const nh_filter_rule_t g_nh_profile_builtin_wifi_rx_rules[];

#endif
