#include <stdio.h>
#include <string.h>

#include "https_fota_server.h"
#include "lwip/apps/fs.h"

#define STRINGIFY_VALUE_(value) #value
#define STRINGIFY_VALUE(value)  STRINGIFY_VALUE_(value)

static const char index_html[] =
    "<!doctype html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "  <meta charset=\"utf-8\">\n"
    "  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
    "  <meta name=\"theme-color\" content=\"#171c19\">\n"
    "  <title>Bouffalo Lab | Firmware Update</title>\n"
    "  <link rel=\"stylesheet\" href=\"/style.css\">\n"
    "</head>\n"
    "<body>\n"
    "  <header class=\"topbar\">\n"
    "    <div class=\"brand\">BOUFFALO LAB</div>\n"
    "    <div id=\"deviceState\" class=\"state busy\">\n"
    "      <i></i><span>Checking for updates</span>\n"
    "    </div>\n"
    "  </header>\n"
    "  <main>\n"
    "    <h1>Firmware Update</h1>\n"
    "    <section class=\"update-panel\">\n"
    "      <div class=\"version-flow\">\n"
    "        <div class=\"version\">\n"
    "          <span>Installed version</span>\n"
    "          <strong id=\"currentVersion\">--</strong>\n"
    "        </div>\n"
    "        <div class=\"flow-mark\"><span>OTA</span><i></i></div>\n"
    "        <div class=\"version target\">\n"
    "          <span>Available version</span>\n"
    "          <strong id=\"availableVersion\">--</strong>\n"
    "        </div>\n"
    "      </div>\n"
    "      <dl class=\"details\">\n"
    "        <div><dt>Update package</dt><dd id=\"packageName\">--</dd></div>\n"
    "        <div><dt>Download size</dt><dd id=\"packageSize\">--</dd></div>\n"
    "        <div><dt>Status</dt><dd id=\"validation\">Checking for updates</dd></div>\n"
    "      </dl>\n"
    "      <div id=\"progressWrap\" class=\"status-block\" hidden>\n"
    "        <div class=\"status-line\">\n"
    "          <span id=\"statusLabel\">Sending to device</span>\n"
    "          <strong id=\"progressValue\">0%</strong>\n"
    "        </div>\n"
    "        <progress id=\"progress\" max=\"100\" value=\"0\"></progress>\n"
    "      </div>\n"
    "      <p id=\"message\" role=\"status\">Checking for updates...</p>\n"
    "      <button id=\"updateButton\" type=\"button\" disabled>\n"
    "        Update now\n"
    "      </button>\n"
    "    </section>\n"
    "  </main>\n"
    "  <script>\n"
    "    window.OTA_CONFIG = {\n"
    "      currentVersion: \""
    STRINGIFY_VALUE(APP_VER_X) "."
    STRINGIFY_VALUE(APP_VER_Y) "."
    STRINGIFY_VALUE(APP_VER_Z)
    "\"\n"
    "    };\n"
    "  </script>\n"
    "  <script src=\"/app.js\"></script>\n"
    "</body>\n"
    "</html>\n";

static const char style_css[] =
    ":root {\n"
    "  color-scheme: light;\n"
    "  --ink: #171c19;\n"
    "  --muted: #68706b;\n"
    "  --line: #d9dedb;\n"
    "  --paper: #f4f6f4;\n"
    "  --white: #ffffff;\n"
    "  --green: #167348;\n"
    "  --green-dark: #0e5635;\n"
    "  --red: #a12b2b;\n"
    "}\n"
    "* { box-sizing: border-box; letter-spacing: 0; }\n"
    "body {\n"
    "  margin: 0;\n"
    "  background: var(--paper);\n"
    "  color: var(--ink);\n"
    "  font-family: Inter, system-ui, -apple-system, sans-serif;\n"
    "  font-size: 14px;\n"
    "}\n"
    ".topbar {\n"
    "  min-height: 72px;\n"
    "  padding: 0 max(24px, calc((100% - 760px) / 2));\n"
    "  display: flex;\n"
    "  align-items: center;\n"
    "  justify-content: space-between;\n"
    "  gap: 24px;\n"
    "  background: var(--ink);\n"
    "  color: var(--white);\n"
    "  border-bottom: 3px solid #3a9a67;\n"
    "}\n"
    ".brand { font-size: 20px; font-weight: 800; }\n"
    ".state {\n"
    "  display: flex;\n"
    "  align-items: center;\n"
    "  gap: 8px;\n"
    "  color: #d5ddd8;\n"
    "  font-size: 12px;\n"
    "  font-weight: 650;\n"
    "}\n"
    ".state i {\n"
    "  width: 8px;\n"
    "  height: 8px;\n"
    "  border-radius: 50%;\n"
    "  background: #aab3ad;\n"
    "}\n"
    ".state.busy i { background: #e0a64e; }\n"
    ".state.ready i, .state.success i { background: #53bc7d; }\n"
    ".state.error i { background: #e16767; }\n"
    "main { width: min(760px, calc(100% - 32px)); margin: 34px auto 26px; }\n"
    "h1 { margin: 0 0 18px; font-size: 28px; font-weight: 680; }\n"
    ".update-panel {\n"
    "  overflow: hidden;\n"
    "  border: 1px solid var(--line);\n"
    "  border-radius: 6px;\n"
    "  background: var(--white);\n"
    "}\n"
    ".version-flow {\n"
    "  display: grid;\n"
    "  grid-template-columns: 1fr 92px 1fr;\n"
    "  align-items: center;\n"
    "  min-height: 142px;\n"
    "  padding: 26px 30px;\n"
    "  border-bottom: 1px solid var(--line);\n"
    "}\n"
    ".version { min-width: 0; }\n"
    ".version span { display: block; margin-bottom: 9px; color: var(--muted); }\n"
    ".version strong { display: block; font-size: 25px; overflow-wrap: anywhere; }\n"
    ".version.target { text-align: right; }\n"
    ".version.target strong { color: var(--green-dark); }\n"
    ".flow-mark { display: flex; flex-direction: column; align-items: center; gap: 10px; color: #69756e; }\n"
    ".flow-mark span { font-size: 10px; font-weight: 800; }\n"
    ".flow-mark i { position: relative; width: calc(100% - 14px); height: 1px; background: #bcc4bf; }\n"
    ".flow-mark i::after {\n"
    "  position: absolute;\n"
    "  top: -3px;\n"
    "  right: 0;\n"
    "  width: 6px;\n"
    "  height: 6px;\n"
    "  content: '';\n"
    "  border-top: 1px solid #89938d;\n"
    "  border-right: 1px solid #89938d;\n"
    "  transform: rotate(45deg);\n"
    "}\n"
    ".details { margin: 0; padding: 8px 30px; }\n"
    ".details div {\n"
    "  display: grid;\n"
    "  grid-template-columns: 150px minmax(0, 1fr);\n"
    "  gap: 20px;\n"
    "  padding: 12px 0;\n"
    "  border-bottom: 1px solid #edf0ee;\n"
    "}\n"
    ".details div:last-child { border-bottom: 0; }\n"
    ".details dt { color: var(--muted); }\n"
    ".details dd { margin: 0; font-weight: 620; overflow-wrap: anywhere; }\n"
    ".status-block { padding: 18px 30px 22px; border-top: 1px solid var(--line); }\n"
    ".status-line { display: flex; justify-content: space-between; margin-bottom: 8px; }\n"
    ".status-line span, .status-line strong { font-size: 11px; }\n"
    ".status-line span { color: var(--muted); }\n"
    "progress {\n"
    "  display: block;\n"
    "  width: 100%;\n"
    "  height: 8px;\n"
    "  overflow: hidden;\n"
    "  border: 0;\n"
    "  border-radius: 4px;\n"
    "  background: #e5e9e6;\n"
    "}\n"
    "progress::-webkit-progress-bar { background: #e5e9e6; }\n"
    "progress::-webkit-progress-value { background: var(--green); }\n"
    "progress::-moz-progress-bar { background: var(--green); }\n"
    "p { min-height: 20px; margin: 0 30px 18px; color: #505954; line-height: 1.45; }\n"
    "p.ok { color: var(--green-dark); }\n"
    "p.error { color: var(--red); }\n"
    "button {\n"
    "  width: calc(100% - 60px);\n"
    "  min-height: 48px;\n"
    "  margin: 0 30px 30px;\n"
    "  border: 0;\n"
    "  border-radius: 4px;\n"
    "  background: var(--green);\n"
    "  color: var(--white);\n"
    "  font: inherit;\n"
    "  font-weight: 750;\n"
    "  cursor: pointer;\n"
    "}\n"
    "button:hover { background: var(--green-dark); }\n"
    "button:focus-visible { outline: 3px solid #9bcab0; outline-offset: 2px; }\n"
    "button:disabled { cursor: not-allowed; background: #b0b7b2; }\n"
    "button.success:disabled { cursor: default; background: var(--green); }\n"
    "@media (max-width: 560px) {\n"
    "  .topbar { min-height: 64px; padding: 12px 18px; gap: 8px 16px; flex-wrap: wrap; }\n"
    "  .state { margin-left: auto; }\n"
    "  main { margin-top: 26px; }\n"
    "  h1 { font-size: 24px; }\n"
    "  .version-flow { grid-template-columns: 1fr 56px 1fr; padding: 22px 20px; }\n"
    "  .version strong { font-size: 20px; }\n"
    "  .details { padding: 6px 20px; }\n"
    "  .details div { grid-template-columns: 108px minmax(0, 1fr); gap: 12px; }\n"
    "  .status-block { padding: 18px 20px 20px; }\n"
    "  p { margin: 0 20px 18px; }\n"
    "  button { width: calc(100% - 40px); margin: 0 20px 20px; }\n"
    "}\n"
    "@media (max-width: 380px) {\n"
    "  .version-flow { grid-template-columns: 1fr; gap: 18px; }\n"
    "  .flow-mark { width: 68px; justify-self: center; }\n"
    "  .flow-mark i { width: 32px; transform: rotate(90deg); }\n"
    "  .version.target { text-align: left; }\n"
    "  .details div { grid-template-columns: 1fr; gap: 4px; }\n"
    "}\n";

static const char app_js[] =
    "'use strict';\n"
    "\n"
    "const cfg = window.OTA_CONFIG;\n"
    "const currentVersion = document.getElementById('currentVersion');\n"
    "const availableVersion = document.getElementById('availableVersion');\n"
    "const updateButton = document.getElementById('updateButton');\n"
    "const message = document.getElementById('message');\n"
    "const deviceState = document.getElementById('deviceState');\n"
    "const packageName = document.getElementById('packageName');\n"
    "const packageSize = document.getElementById('packageSize');\n"
    "const validation = document.getElementById('validation');\n"
    "const progressWrap = document.getElementById('progressWrap');\n"
    "const statusLabel = document.getElementById('statusLabel');\n"
    "const progress = document.getElementById('progress');\n"
    "const progressValue = document.getElementById('progressValue');\n"
    "let firmware;\n"
    "let rebootAfterUpdate;\n"
    "let uploadUri;\n"
    "\n"
    "currentVersion.textContent = 'v' + cfg.currentVersion;\n"
    "\n"
    "function showMessage(text, type = '') {\n"
    "  message.textContent = text;\n"
    "  message.className = type;\n"
    "}\n"
    "\n"
    "function setState(text, type) {\n"
    "  deviceState.className = 'state ' + type;\n"
    "  deviceState.querySelector('span').textContent = text;\n"
    "}\n"
    "\n"
    "function formatBytes(value) {\n"
    "  if (value < 1024) return value + ' B';\n"
    "  if (value < 1024 * 1024) return (value / 1024).toFixed(1) + ' KB';\n"
    "  return (value / (1024 * 1024)).toFixed(2) + ' MB';\n"
    "}\n"
    "\n"
    "async function readVersion(blob) {\n"
    "  const buffer = await blob.slice(48, 64).arrayBuffer();\n"
    "  const bytes = new Uint8Array(buffer);\n"
    "  const value = new TextDecoder('ascii').decode(\n"
    "    bytes.slice(0, bytes.indexOf(0))\n"
    "  );\n"
    "  if (!/^\\d+\\.\\d+\\.\\d+$/.test(value)) {\n"
    "    throw new Error('Invalid firmware version');\n"
    "  }\n"
    "  return value;\n"
    "}\n"
    "\n"
    "async function loadFirmware() {\n"
    "  try {\n"
    "    const configResponse = await fetch('/ota-config.txt', { cache: 'no-store' });\n"
    "    if (!configResponse.ok) throw new Error('OTA configuration unavailable');\n"
    "    const serverConfig = (await configResponse.text()).trim().split('\\n');\n"
    "    const firmwareUrl = serverConfig[0];\n"
    "    rebootAfterUpdate = serverConfig[1] !== '0';\n"
    "    uploadUri = serverConfig[2];\n"
    "    const parsedUrl = new URL(firmwareUrl);\n"
    "    packageName.textContent = decodeURIComponent(parsedUrl.pathname.split('/').pop()) || 'Firmware package';\n"
    "\n"
    "    const response = await fetch(firmwareUrl, { cache: 'no-store' });\n"
    "    if (!response.ok) throw new Error('Firmware download failed');\n"
    "\n"
    "    firmware = await response.blob();\n"
    "    const version = await readVersion(firmware);\n"
    "    availableVersion.textContent = 'v' + version;\n"
    "    packageSize.textContent = formatBytes(firmware.size);\n"
    "    validation.textContent = 'Ready to update';\n"
    "    setState('Update available', 'ready');\n"
    "    updateButton.disabled = false;\n"
    "    showMessage('The update is ready.', 'ok');\n"
    "  } catch {\n"
    "    firmware = null;\n"
    "    availableVersion.textContent = 'Unavailable';\n"
    "    packageSize.textContent = '--';\n"
    "    validation.textContent = 'Update unavailable';\n"
    "    setState('Update unavailable', 'error');\n"
    "    showMessage('Unable to retrieve the update.', 'error');\n"
    "  }\n"
    "}\n"
    "\n"
    "async function postOta(path, body) {\n"
    "  let response;\n"
    "  try {\n"
    "    response = await fetch(path, { method: 'POST', body: body === undefined ? '' : body, cache: 'no-store' });\n"
    "  } catch { throw { disconnected: true }; }\n"
    "  if (!response.ok || !(await response.json()).ok) throw new Error('OTA failed');\n"
    "}\n"
    "\n"
    "async function uploadFirmware(blob) {\n"
    "  let finishing = false;\n"
    "  try {\n"
    "    await postOta(uploadUri + '/start?size=' + blob.size);\n"
    "    for (let offset = 0; offset < blob.size; offset += 16384) {\n"
    "      const end = Math.min(offset + 16384, blob.size);\n"
    "      await postOta(uploadUri + '/chunk', blob.slice(offset, end));\n"
    "      const percent = Math.min(99, Math.floor(end * 100 / blob.size));\n"
    "      progress.value = percent;\n"
    "      progressValue.textContent = percent + '%';\n"
    "    }\n"
    "    finishing = true;\n"
    "    await postOta(uploadUri + '/finish');\n"
    "  } catch (error) {\n"
    "    if (!finishing) {\n"
    "      try { await postOta(uploadUri + '/abort'); } catch {}\n"
    "    }\n"
    "    throw { sent: finishing && error.disconnected };\n"
    "  }\n"
    "}\n"
    "\n"
    "async function updateFirmware() {\n"
    "  updateButton.disabled = true;\n"
    "  updateButton.textContent = 'Updating...';\n"
    "  validation.textContent = 'Installing update';\n"
    "  progressWrap.hidden = false;\n"
    "  progress.value = 0;\n"
    "  progressValue.textContent = '0%';\n"
    "  statusLabel.textContent = 'Sending to device';\n"
    "  setState('Updating device', 'busy');\n"
    "  showMessage('Installing the update...');\n"
    "  try {\n"
    "    await uploadFirmware(firmware);\n"
    "    firmware = null;\n"
    "\n"
    "    validation.textContent = rebootAfterUpdate ? 'Restarting device' : 'Update accepted';\n"
    "    progress.value = 100;\n"
    "    progressValue.textContent = '100%';\n"
    "    statusLabel.textContent = 'Transfer complete';\n"
    "    setState('Update accepted', 'success');\n"
    "    updateButton.classList.add('success');\n"
    "    updateButton.textContent = 'Update accepted';\n"
    "    showMessage(rebootAfterUpdate ? 'Reconnect and refresh after restart.' : 'Restart the device to apply the update.', 'ok');\n"
    "  } catch (error) {\n"
    "    if (error.sent) {\n"
    "      firmware = null;\n"
    "      validation.textContent = 'Restart not confirmed';\n"
    "      setState('Check device status', 'error');\n"
    "      showMessage('Connection lost. Reconnect and refresh to check the device.', 'error');\n"
    "    } else {\n"
    "      progressWrap.hidden = true;\n"
    "      updateButton.disabled = true;\n"
    "      updateButton.textContent = 'Update failed';\n"
    "      validation.textContent = 'Unable to update';\n"
    "      setState('Update failed', 'error');\n"
    "      showMessage('The update failed.', 'error');\n"
    "    }\n"
    "  }\n"
    "}\n"
    "\n"
    "updateButton.addEventListener('click', updateFirmware);\n"
    "loadFirmware();\n";

static const char ota_success_json[] = "{\"ok\":true}";
static const char ota_error_json[] =
    "{\"ok\":false,\"error\":\"OTA failed.\"}";
#define OTA_CONFIG_TEXT_MAX (OTA_FIRMWARE_URL_MAX + (3 * HTTPS_FOTA_SERVER_URI_MAX) + 16)
static char ota_config_text[OTA_CONFIG_TEXT_MAX];

#define FS_ROOT NULL

static int open_static_file(struct fs_file *file, const char *data, int len)
{
    memset(file, 0, sizeof(*file));
    file->data = data;
    file->len = len;
    file->index = len;
    return 1;
}

int fs_open_custom(struct fs_file *file, const char *name)
{
    const struct https_fota_server_config *config =
        https_fota_server_get_config();

    if (!strcmp(name, "/") || !strcmp(name, "/index.html")) {
        return open_static_file(file, index_html, sizeof(index_html) - 1);
    }
    if (!strcmp(name, "/style.css")) {
        return open_static_file(file, style_css, sizeof(style_css) - 1);
    }
    if (!strcmp(name, "/app.js")) {
        return open_static_file(file, app_js, sizeof(app_js) - 1);
    }
    if (!strcmp(name, "/ota-config.txt")) {
        int len = snprintf(ota_config_text, sizeof(ota_config_text),
                           "%s\n%d\n%s\n",
                           https_fota_server_url(),
                           config && config->reboot ? 1 : 0,
                           config ? config->upload_uri :
                           HTTPS_FOTA_SERVER_DEFAULT_UPLOAD_URI);
        return open_static_file(file, ota_config_text, len);
    }
    if (!strcmp(name, config ? config->success_uri :
                       HTTPS_FOTA_SERVER_DEFAULT_SUCCESS_URI)) {
        return open_static_file(file, ota_success_json,
                                sizeof(ota_success_json) - 1);
    }
    if (!strcmp(name, config ? config->error_uri :
                       HTTPS_FOTA_SERVER_DEFAULT_ERROR_URI)) {
        return open_static_file(file, ota_error_json,
                                sizeof(ota_error_json) - 1);
    }

    return 0;
}

void fs_close_custom(struct fs_file *file)
{
    (void)file;
}
